Repository doctrine/dbal, pull requests merged in 2018-07, with the labels that each got.

#3200 [minor] SCA
  lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/Schema/AbstractAsset.php
  lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php
  lib/Doctrine/DBAL/Tools/Dumper.php
Labels: Improvement

#3205 Ignore OCI-* classes in static analysis (no stubs)
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Improvement

#3204 Fix typo in AbstractPlatform
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
Labels: Improvement

#3199 Allow symfony/console 4.x dev-dependency
  composer.json
  composer.lock
Labels: Improvement

#3207 Drop legacy submodules, empty README and ORM leftovers
  .gitattributes
  .gitmodules
  lib/Doctrine/DBAL/README.markdown
  tests/.gitignore
  tests/README.markdown
Labels: Improvement

#3212 Deprecated usage of DB-generated UUIDs
  UPGRADE.md
  docs/en/reference/sharding.rst
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/DrizzlePlatform.php
  lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
Labels: Deprecation, Platforms

#3219 GitHub template grammar/spelling fixes
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Support_Question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#3232 Removed NOW() from QueryBuilder usage examples
  lib/Doctrine/DBAL/Query/QueryBuilder.php
Labels: Documentation, Improvement, Query
