Repository doctrine/dbal, pull requests merged in 2018-02, with the labels that each got.

#3024 [DBAL-2953] Fixed unqualified PDO class name
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
Labels: Bug

#3013 Escape LIKE metacharacters
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2008Platform.php
  lib/Doctrine/DBAL/Query/Expression/ExpressionBuilder.php
  tests/Doctrine/Tests/DBAL/Functional/LikeWildcardsEscapingTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Query/Expression/ExpressionBuilderTest.php
Labels: Improvement, Platforms, Query, Quoting

#3026 Bump CS version to 3.0
  composer.json
Labels: Code Style

#3027 Documentation: Warn against using object fields in MySQL and MariaDB
  docs/en/reference/types.rst
Labels: Columns, Documentation, MySQL, Schema Definition
