Repository doctrine/dbal, pull requests merged in 2019-11, with the labels that each got.

#3713 Fix branch-alias (master is now 3.0)
  composer.json
Labels: Compatibility, Improvement

#3716 Update releases documentation
  .doctrine-project.json
Labels: Documentation

#3719 Remove phpunit-bridge specific annotations
  tests/Doctrine/Tests/DBAL/Functional/PDOStatementTest.php
  tests/Doctrine/Tests/DBAL/Schema/ColumnTest.php
Labels: Improvement, Test Suite, Testing

#3723 Fix annotations
  lib/Doctrine/DBAL/Types/Type.php
  lib/Doctrine/DBAL/Types/Types.php
Labels: Bug, Deprecation, Documentation, Types

#3726 Add .doctrine-project.json to .gitattributes
  .gitattributes
Labels: Improvement

#3729 Fix upgrade comment about MariaDB
  UPGRADE.md
Labels: Documentation, MariaDB

#3734 Fix of branch names for doctrine website config
  .doctrine-project.json
Labels: Documentation

#3739 Update deprecation messages to refer to DBAL
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Schema/Column.php
  tests/Doctrine/Tests/DBAL/Functional/PDOStatementTest.php
  tests/Doctrine/Tests/DBAL/Schema/ColumnTest.php
Labels: Deprecation, Documentation

#3745 Remove temporary SQLite file on teardown
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
Labels: Bug, SQLite, Test Suite

#3720 Switched from PHPBrew-based configuration to the Docker-based
  tests/continuousphp/install-pdo-oci.sh
Labels: CI, Improvement, pdo_oracle

#3750 VersionAwarePlatformDriver now extends Driver
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/VersionAwarePlatformDriver.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
Labels: BC Break, Drivers, Improvement, Platform Detection

#3752 PingableConnection and ServerInfoAwareConnection now extend Connection
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/PingableConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/ServerInfoAwareConnection.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
Labels: BC Break, Connections, Improvement

#3753 Allow build failures for unstable dependencies
  .travis.yml
Labels: CI, Improvement

#3754 Locked the PHP_CodeSniffer version to 3.5 for better compatibility with PHP 7.4
  composer.lock
  phpcs.xml.dist
  tests/Doctrine/Tests/DBAL/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
Labels: Code Style, Improvement
