Repository doctrine/dbal, pull requests merged in 2019-12, with the labels that each got.

#3756 Dropped SQL Server 2008 support
  .appveyor.yml
  UPGRADE.md
  docs/en/reference/platforms.rst
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2012Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServerKeywords.php
  lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLServerDriverTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
Labels: BC Break, Improvement, SQL Server

#3760 Develop branch is gone
  README.md
Labels: Documentation, Improvement

#3778 [GH-3777] Don't remove composer lock travis on stable 2.10 branch
  .appveyor.yml
  .travis.yml
Labels: CI, Improvement

#3784 Use PHP 7.4 instead of a snapshot on Travis
  .travis.yml
Labels: CI, Improvement

#3785 Test primarily against PHP 7.4 on Travis
  .travis.yml
Labels: CI, Improvement, PHP

#3786 Test against PHP 7.4 on AppVeyor
  .appveyor.yml
Labels: CI, Improvement, PHP

#3788 Switching Travis CI builds to Ubuntu Bionic Beaver
  .travis.yml
Labels: CI, Improvement

#3738 Fix breaks named parameters in Oracle
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/OCI8/StatementTest.php
Labels: Bug, Prepared Statements, Regression, oci8

#3795 Document MySQL error codes
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Labels: Code Style, Improvement, MySQL

#3793 Remove superfluous Configuration instance
  docs/en/reference/configuration.rst
Labels: Documentation, Improvement

#3790 fixed unqualified table name of fk constraints when using schemas
  lib/Doctrine/DBAL/Schema/ForeignKeyConstraint.php
  tests/Doctrine/Tests/DBAL/Schema/ForeignKeyConstraintTest.php
Labels: Bug, Regression, Schema

#3797 Fix typos in SQLite
  tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
Labels: Improvement, Test Suite

#3794 Support ForeignKeyConstraintViolationException in SQLite
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLiteDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
Labels: Error Handling, Foreign Keys, Improvement, SQLite

#3579 Remove deprecated stuff for 3.0
  lib/Doctrine/DBAL/Configuration.php
  lib/Doctrine/DBAL/Driver/Exception/UnknownFetchMode.php
  lib/Doctrine/DBAL/Driver/Exception/UnknownParamType.php
  lib/Doctrine/DBAL/Driver/Mysqli/Exception/UnknownFetchMode.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Schema/Column.php
  lib/Doctrine/DBAL/Schema/Exception/UnknownColumnOption.php
  lib/Doctrine/DBAL/Types/BinaryType.php
  lib/Doctrine/DBAL/Types/BlobType.php
  lib/Doctrine/DBAL/Types/Type.php
  lib/Doctrine/DBAL/Types/Types.php
  tests/Doctrine/Tests/DBAL/Functional/PDOStatementTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSqlPlatformTest.php
  tests/Doctrine/Tests/DBAL/Schema/ColumnTest.php
  tests/Doctrine/Tests/DBAL/Schema/TableTest.php
Labels: BC Break, Improvement
