Repository doctrine/dbal, pull requests merged in 2019-05, with the labels that each got.

#3542 Deprecate SQLSrvStatement::LAST_INSERT_ID_SQL constant.
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
Labels: Deprecation

#3541 Deprecate the public constants in SQLParserUtils
  UPGRADE.md
  lib/Doctrine/DBAL/SQLParserUtils.php
Labels: Deprecation

#3546 Reworked driver exception tests
  composer.json
  composer.lock
  tests/Doctrine/Tests/DBAL/DBALExceptionTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractMySQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractOracleDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractPostgreSQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLAnywhereDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLiteDriverTest.php
Labels: Improvement, Test Suite

#3548 Remove user provided PDO functionality
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Exception/InvalidPdoInstance.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOExceptionTest.php
  tests/Doctrine/Tests/DBAL/DriverManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/PDOStatementTest.php
Labels: BC Break, Configuration, Connections, PDO

#3547 Default column expressions do not work on SQL Server
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  tests/Doctrine/Tests/DBAL/Functional/Platform/DefaultExpressionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
Labels: Bug, Columns, SQL Server, Schema Definition

#3552 Enforced parameter and return value types in Statement classes
  lib/Doctrine/DBAL/Cache/ArrayStatement.php
  lib/Doctrine/DBAL/Cache/QueryCacheProfile.php
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Statement.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Driver/Statement.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Statement.php
Labels: BC Break, Improvement, Prepared Statements, Strict Typing

#3518 Remove @​deprecated stuff
  UPGRADE.md
  lib/Doctrine/DBAL/Configuration.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Event/Listeners/MysqlSessionInit.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php
  lib/Doctrine/DBAL/Schema/Comparator.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/Table.php
  lib/Doctrine/DBAL/Types/JsonArrayType.php
  lib/Doctrine/DBAL/Types/Type.php
  tests/Doctrine/Tests/DBAL/Events/MysqlSessionInitTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/TypeConversionTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
  tests/Doctrine/Tests/DBAL/Schema/ComparatorTest.php
  tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Schema/Platforms/MySQLSchemaTest.php
  tests/Doctrine/Tests/DBAL/Types/JsonArrayTest.php
Labels: BC Break, Improvement

#3554 The usage of user-provided PDO instance is deprecated
  UPGRADE.md
Labels: Configuration, Connections, Deprecation, PDO

#3555 Removed the rest of mock classes
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractMySQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractPostgreSQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Portability/StatementTest.php
  tests/Doctrine/Tests/Mocks/DriverConnectionMock.php
  tests/Doctrine/Tests/Mocks/DriverResultStatementMock.php
  tests/Doctrine/Tests/Mocks/DriverStatementMock.php
  tests/Doctrine/Tests/Mocks/ServerInfoAwareConnectionMock.php
  tests/Doctrine/Tests/Mocks/VersionAwarePlatformDriverMock.php
Labels: Improvement, Test Suite

#3556 Removed 2.8 from README
  README.md
Labels: Documentation, Improvement

#3553 Removed Driver::getName()
  UPGRADE.md
  lib/Doctrine/DBAL/Driver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Driver.php
  lib/Doctrine/DBAL/Driver/Mysqli/Driver.php
  lib/Doctrine/DBAL/Driver/OCI8/Driver.php
  lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOOracle/Driver.php
  lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Driver.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/Driver.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php
  tests/Doctrine/Tests/DBAL/Driver/IBMDB2/DB2DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/Mysqli/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/OCI8/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOMySql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOOracle/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOPgSql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOSqlite/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/SQLAnywhere/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/SQLSrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/StatementTest.php
Labels: BC Break, Drivers

#3558 Deprecated Driver::getName()
  UPGRADE.md
  lib/Doctrine/DBAL/Driver.php
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Driver.php
  lib/Doctrine/DBAL/Driver/OCI8/Driver.php
  lib/Doctrine/DBAL/Driver/PDOIbm/Driver.php
  lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Driver.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/Driver.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Deprecation, Drivers

#3560 Enforced parameter and return value types in Driver classes
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  lib/Doctrine/DBAL/Driver.php
  lib/Doctrine/DBAL/Driver/AbstractDB2Driver.php
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Driver/ExceptionConverterDriver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Driver.php
  lib/Doctrine/DBAL/Driver/Mysqli/Driver.php
  lib/Doctrine/DBAL/Driver/OCI8/Driver.php
  lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOOracle/Driver.php
  lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Driver.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/Driver.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php
  lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php
  lib/Doctrine/DBAL/VersionAwarePlatformDriver.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOPgSql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
Labels: BC Break, Drivers, Improvement, Strict Typing

#3562 Enforced parameter and return value types in Platform classes
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/DB2Platform.php
  lib/Doctrine/DBAL/Platforms/Keywords/DB2Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/KeywordList.php
  lib/Doctrine/DBAL/Platforms/Keywords/MySQL57Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/MySQL80Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/MySQLKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/OracleKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQL94Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQLKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/ReservedKeywordsValidator.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhereKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2012Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServerKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLiteKeywords.php
  lib/Doctrine/DBAL/Platforms/MySQL57Platform.php
  lib/Doctrine/DBAL/Platforms/MySQL80Platform.php
  lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL100Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL94Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAzurePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlite/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
  tests/Doctrine/Tests/DBAL/Types/DateImmutableTypeTest.php
  tests/Doctrine/Tests/DBAL/Types/TimeImmutableTypeTest.php
Labels: BC Break, Improvement, Platforms, Strict Typing

#3566 Upgraded to PHPUnit 8.1.6 and reworked the remaining driver exception mock
  composer.json
  composer.lock
  tests/Doctrine/Tests/DBAL/Driver/AbstractDriverTest.php
Labels: Improvement, Test Suite

#3569 Add proper types to Doctrine\DBAL\Types namespace.
  lib/Doctrine/DBAL/Types/ArrayType.php
  lib/Doctrine/DBAL/Types/BigIntType.php
  lib/Doctrine/DBAL/Types/BinaryType.php
  lib/Doctrine/DBAL/Types/BlobType.php
  lib/Doctrine/DBAL/Types/BooleanType.php
  lib/Doctrine/DBAL/Types/DateImmutableType.php
  lib/Doctrine/DBAL/Types/DateIntervalType.php
  lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
  lib/Doctrine/DBAL/Types/DateTimeType.php
  lib/Doctrine/DBAL/Types/DateTimeTzImmutableType.php
  lib/Doctrine/DBAL/Types/DateTimeTzType.php
  lib/Doctrine/DBAL/Types/DateType.php
  lib/Doctrine/DBAL/Types/DecimalType.php
  lib/Doctrine/DBAL/Types/Exception/ValueNotConvertible.php
  lib/Doctrine/DBAL/Types/FloatType.php
  lib/Doctrine/DBAL/Types/GuidType.php
  lib/Doctrine/DBAL/Types/IntegerType.php
  lib/Doctrine/DBAL/Types/JsonType.php
  lib/Doctrine/DBAL/Types/ObjectType.php
  lib/Doctrine/DBAL/Types/SimpleArrayType.php
  lib/Doctrine/DBAL/Types/SmallIntType.php
  lib/Doctrine/DBAL/Types/StringType.php
  lib/Doctrine/DBAL/Types/TextType.php
  lib/Doctrine/DBAL/Types/TimeImmutableType.php
  lib/Doctrine/DBAL/Types/TimeType.php
  lib/Doctrine/DBAL/Types/Type.php
  lib/Doctrine/DBAL/Types/TypeRegistry.php
  lib/Doctrine/DBAL/Types/VarDateTimeImmutableType.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/Types/CommentedType.php
  tests/Doctrine/Tests/Types/MySqlPointType.php
Labels: Improvement, Strict Typing, Types

#3568 Enforced parameter and return value types in Connection classes
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  lib/Doctrine/DBAL/Driver.php
  lib/Doctrine/DBAL/Driver/Connection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/LastInsertId.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/ServerInfoAwareConnection.php
  lib/Doctrine/DBAL/Portability/Connection.php
  lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php
  lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
  lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/OCI8/OCI8ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/OracleSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/WriteTest.php
  tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardConnectionTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardManagerTest.php
Labels: BC Break, Connections, Improvement, Strict Typing

#3570 Add proper types to Doctrine\DBAL\Tools namespace.
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
  lib/Doctrine/DBAL/Tools/Console/ConsoleRunner.php
  lib/Doctrine/DBAL/Tools/Console/Helper/ConnectionHelper.php
  lib/Doctrine/DBAL/Tools/Dumper.php
Labels: BC Break, Improvement, Strict Typing, Tools

#3571 Add proper types to the Doctrine\DBAL\Sharding namespace.
  lib/Doctrine/DBAL/Sharding/PoolingShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureFederationsSynchronizer.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/Schema/MultiTenantVisitor.php
  lib/Doctrine/DBAL/Sharding/ShardManager.php
Labels: Improvement, Sharding, Strict Typing

#3573 Add proper types to Doctrine\DBAL\Id namespace.
  lib/Doctrine/DBAL/Id/TableGenerator.php
  lib/Doctrine/DBAL/Id/TableGeneratorSchemaVisitor.php
Labels: BC Break, Improvement, Strict Typing

#3576 Add proper types to root Doctrine\DBAL namespace.
  lib/Doctrine/DBAL/Configuration.php
  lib/Doctrine/DBAL/DBALException.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  tests/Doctrine/Tests/DBAL/ConfigurationTest.php
Labels: BC Break, Improvement, Strict Typing

#3574 Add proper types to Doctrine\DBAL\Query namespace.
  lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php
  lib/Doctrine/DBAL/Query/Expression/ExpressionBuilder.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
Labels: BC Break, Improvement, Query, Strict Typing

#3577 Enforced parameter and return value types in event-related classes
  UPGRADE.md
  lib/Doctrine/DBAL/Event/ConnectionEventArgs.php
  lib/Doctrine/DBAL/Event/Listeners/OracleSessionInit.php
  lib/Doctrine/DBAL/Event/Listeners/SQLSessionInit.php
  lib/Doctrine/DBAL/Event/SchemaAlterTableAddColumnEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaAlterTableChangeColumnEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaAlterTableEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaAlterTableRemoveColumnEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaAlterTableRenameColumnEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaColumnDefinitionEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaCreateTableColumnEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaCreateTableEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaDropTableEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaEventArgs.php
  lib/Doctrine/DBAL/Event/SchemaIndexDefinitionEventArgs.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
Labels: BC Break, Events, Improvement, Strict Typing

#3348 Enforce parameter and return value types in the codebase
  UPGRADE.md
  lib/Doctrine/DBAL/Schema/AbstractAsset.php
  lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php
  lib/Doctrine/DBAL/Schema/Column.php
  lib/Doctrine/DBAL/Schema/ForeignKeyConstraint.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLAnywhereSchemaManager.php
  lib/Doctrine/DBAL/Schema/Schema.php
  lib/Doctrine/DBAL/Schema/SchemaDiff.php
  lib/Doctrine/DBAL/Schema/Table.php
  lib/Doctrine/DBAL/Schema/Visitor/SchemaDiffVisitor.php
  phpcs.xml.dist
  tests/Doctrine/Tests/DBAL/Driver/AbstractOracleDriver/EasyConnectStringTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/WriteTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardConnectionTest.php
Labels: BC Break, Code Style, Improvement, Strict Typing
