Repository doctrine/dbal, pull requests merged in 2020-05, with the labels that each got.

#3762 [GH-1204] Add full support for foreign key constraints for SQLite
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Internal/DependencyOrderCalculator.php
  lib/Doctrine/DBAL/Internal/DependencyOrderEdge.php
  lib/Doctrine/DBAL/Internal/DependencyOrderNode.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Schema/SchemaDiff.php
  lib/Doctrine/DBAL/Schema/Visitor/DropSchemaSqlCollector.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Internal/DependencyOrderCalculatorTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaDiffTest.php
Labels: Bug, Foreign Keys, Improvement, SQLite

#3979 Move phpcs from Travis to GitHub Actions
  .github/workflows/continuous-integration.yml
  .travis.yml
Labels: CI

#3998 move PHPStan to GitHub Actions
  .github/workflows/continuous-integration.yml
  .travis.yml
Labels: CI

#3994 Use proper check in acceptForeignKey()
  lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/ForeignKeyTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Bug

#3999 Manually merge 2.10.x into 2.11.x
  .github/workflows/continuous-integration.yml
  .travis.yml
  lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/ForeignKeyTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#4000 Manually merge 2.11.x into 3.0.x
  .github/workflows/continuous-integration.yml
  .travis.yml
  src/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Functional/Schema/ForeignKeyTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#4001 Manual merge 3.0.x into master
  .github/workflows/continuous-integration.yml
  .travis.yml
  src/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Functional/Schema/ForeignKeyTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#3991 Extend RetryableException from Throwable interface
  lib/Doctrine/DBAL/Exception/RetryableException.php
Labels: Bug

#4006 Fix logging in functional tests in case of connection failure
  tests/FunctionalTestCase.php
Labels: Regression, Test Suite

#3956 allow using multiple connections for CLI commands
  bin/doctrine-dbal.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
  lib/Doctrine/DBAL/Tools/Console/ConnectionNotFound.php
  lib/Doctrine/DBAL/Tools/Console/ConnectionProvider.php
  lib/Doctrine/DBAL/Tools/Console/ConnectionProvider/SingleConnectionProvider.php
  lib/Doctrine/DBAL/Tools/Console/ConsoleRunner.php
  lib/Doctrine/DBAL/Tools/Console/Helper/ConnectionHelper.php
Labels: Connections, Console, Improvement

#3989 Remove useless rules
  phpcs.xml.dist
Labels: Code Style, Improvement

#4009 Coveralls integration
  .appveyor.yml
  .coveralls.yml
  .gitattributes
  .scrutinizer.yml
  .travis.yml
  README.md
  tests/continuousphp/bootstrap.php
Labels: CI

#4020 Deprecated Connection::project(), Statement::errorCode() and errorInfo()
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/Connection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Driver/Statement.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Statement.php
Labels: Connections, Deprecation, Prepared Statements

#4021 Manually merge 2.10.x into 2.11.x
  .appveyor.yml
  .coveralls.yml
  .gitattributes
  .scrutinizer.yml
  .travis.yml
  README.md
  docs/en/reference/configuration.rst
  lib/Doctrine/DBAL/Exception/RetryableException.php
  phpcs.xml.dist
  tests/continuousphp/bootstrap.php
Labels: Merge Up

#4023 Manually merge 2.11.x into 3.0.x
  .appveyor.yml
  .coveralls.yml
  .gitattributes
  .scrutinizer.yml
  .travis.yml
  README.md
  UPGRADE.md
  bin/doctrine-dbal.php
  ci/continuousphp/bootstrap.php
  docs/en/reference/configuration.rst
  phpcs.xml.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/SQLAnywhere/SQLAnywhereConnection.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Driver/Statement.php
  src/Exception/RetryableException.php
  src/Portability/Statement.php
  src/Statement.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
  src/Tools/Console/ConnectionNotFound.php
  src/Tools/Console/ConnectionProvider.php
  src/Tools/Console/ConnectionProvider/SingleConnectionProvider.php
  src/Tools/Console/ConsoleRunner.php
  src/Tools/Console/Helper/ConnectionHelper.php
Labels: Merge Up

#4019 Deprecated the concept of the fetch mode
  UPGRADE.md
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Cache/ArrayStatement.php
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/FetchUtils.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Driver/StatementIterator.php
  lib/Doctrine/DBAL/FetchMode.php
  lib/Doctrine/DBAL/ForwardCompatibility/Driver/ResultStatement.php
  lib/Doctrine/DBAL/ForwardCompatibility/ResultStatement.php
  lib/Doctrine/DBAL/Id/TableGenerator.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php
  lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
  lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  lib/Doctrine/DBAL/Sharding/PoolingShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureShardManager.php
  lib/Doctrine/DBAL/Statement.php
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
  tests/Doctrine/Tests/DBAL/Driver/StatementIteratorTest.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/BackwardCompatibility/Connection.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/BackwardCompatibility/FetchTest.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/BackwardCompatibility/Statement.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/FetchTest.php
  tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Schema/MySqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardManagerTest.php
  tests/Doctrine/Tests/DBAL/Tools/Console/RunSqlCommandTest.php
  tests/Doctrine/Tests/TestUtil.php
Labels: Deprecation, Improvement, Prepared Statements

#4029 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  composer.json
  composer.lock
  src/Cache/ArrayStatement.php
  src/Cache/ResultCacheStatement.php
  src/Connection.php
  src/Driver/FetchUtils.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/PDOSqlsrv/Connection.php
  src/Driver/PDOStatement.php
  src/Driver/ResultStatement.php
  src/Driver/SQLAnywhere/SQLAnywhereConnection.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Driver/StatementIterator.php
  src/FetchMode.php
  src/ForwardCompatibility/Driver/ResultStatement.php
  src/ForwardCompatibility/ResultStatement.php
  src/Id/TableGenerator.php
  src/Portability/Statement.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySqlSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSqlSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Statement.php
  src/Tools/Console/Command/RunSqlCommand.php
  tests/Driver/StatementIteratorTest.php
  tests/Functional/Connection/BackwardCompatibility/Connection.php
  tests/Functional/Connection/BackwardCompatibility/FetchTest.php
  tests/Functional/Connection/BackwardCompatibility/Statement.php
  tests/Functional/Connection/FetchTest.php
  tests/Schema/DB2SchemaManagerTest.php
  tests/Schema/MySqlSchemaManagerTest.php
  tests/TestUtil.php
  tests/Tools/Console/RunSqlCommandTest.php
Labels: Merge Up

#4031 Ignore all violations of the LowercasePHPFunctions sniff in SQLSrvStatement
  phpcs.xml.dist
Labels: Code Style, Improvement

#4030 Backport removal of some deprecated APIs
  UPGRADE.md
  phpstan.neon.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/PDOConnection.php
  src/Driver/PDOStatement.php
  src/Driver/SQLAnywhere/SQLAnywhereConnection.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Driver/Statement.php
  src/Portability/Statement.php
  src/Statement.php
  tests/Driver/OCI8/OCI8StatementTest.php
  tests/Portability/StatementTest.php
Labels: BC Break, Connections, Error Handling

#4022 Manual merge of 2.10.x into 2.11.x
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Logging/SQLLogger.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Portability/Connection.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  phpcs.xml.dist
  phpstan.neon.dist
  psalm.xml
  tests/Doctrine/Tests/DBAL/Cache/QueryCacheProfileTest.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/StatementIteratorTest.php
  tests/Doctrine/Tests/DBAL/DriverManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLSrv/StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/ResultCacheTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/WriteTest.php
  tests/Doctrine/Tests/DBAL/FutureVersionAwarePlatformDriver.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL92PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywhere12PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
  tests/Doctrine/Tests/DBAL/Schema/ComparatorTest.php
  tests/Doctrine/Tests/DBAL/Schema/MySqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/SQLAzure/SQLAzureShardManagerTest.php
  tests/Doctrine/Tests/DBAL/StatementTest.php
  tests/Doctrine/Tests/DBAL/Tools/Console/RunSqlCommandTest.php
  tests/Doctrine/Tests/DBAL/Types/TypeTest.php
Labels: Merge Up

#4035 Moved rowCount() from Statement to ResultStatement
  UPGRADE.md
  src/Cache/ArrayStatement.php
  src/Cache/ResultCacheStatement.php
  src/Driver/ResultStatement.php
  src/Driver/Statement.php
Labels: BC Break, Improvement, Prepared Statements

#4034 Additional changes based on the discussion in #4007
  docs/en/reference/caching.rst
  docs/en/reference/data-retrieval-and-manipulation.rst
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  tests/Doctrine/Tests/DBAL/Functional/ResultCacheTest.php
Labels: Bug, Documentation, Improvement, Prepared Statements

#4039 Refactor portability statement into a functional composition
  src/Portability/Connection.php
  src/Portability/Converter.php
  src/Portability/Statement.php
  tests/Portability/ConverterTest.php
  tests/Portability/StatementTest.php
Labels: Improvement, Portability, Prepared Statements

#4037 Introduce Statement::fetchFirstColumn()
  UPGRADE.md
  lib/Doctrine/DBAL/Cache/ArrayStatement.php
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/FetchUtils.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/ForwardCompatibility/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Statement.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/FetchTest.php
Labels: Deprecation, Improvement, Prepared Statements
