Repository doctrine/dbal, pull requests merged in 2020-04, with the labels that each got.

#3935 Deprecate EchoSQLLogger
  UPGRADE.md
  lib/Doctrine/DBAL/Logging/EchoSQLLogger.php
Labels: Deprecation, Logging

#3934 Removed EchoSQLLogger
  UPGRADE.md
  src/Logging/EchoSQLLogger.php
  tests/ConnectionTest.php
Labels: BC Break, Logging

#3933 Removed the hard-coded MySQL default port and the usage of ini-settings
  src/Driver/Mysqli/MysqliConnection.php
Labels: Drivers, Improvement, mysqli

#3939 Fix parsing column comments on SQLite
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Bug, SQLite, Schema Introspection, Schema Managers

#3941 Manually merge 2.10.x into 2.11.x
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Merge Up

#3943 Do not require hostname for non-persistent MySQL connection and require for persistent
  src/Driver/Mysqli/HostRequired.php
  src/Driver/Mysqli/MysqliConnection.php
  tests/Driver/Mysqli/MysqliConnectionTest.php
Labels: Bug, Connecting, Connections, mysqli

#3944 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Merge Up

#3946 Upgrade PHPUnit to 9.1
  composer.json
  composer.lock
  tests/Functional/Schema/SQLAnywhereSchemaManagerTest.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Tools/Console/RunSqlCommandTest.php
  tests/Types/ConversionExceptionTest.php
Labels: Improvement, Test Suite

#3070 Dropped support of fetching objects and non-zero column
  UPGRADE.md
  phpstan.neon.dist
  src/Cache/ArrayStatement.php
  src/Cache/ResultCacheStatement.php
  src/Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/PDOStatement.php
  src/Driver/ResultStatement.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/FetchMode.php
  src/Portability/Statement.php
  src/Statement.php
  tests/ConnectionTest.php
  tests/Functional/DataAccessTest.php
  tests/Functional/Types/BinaryTest.php
  tests/Portability/StatementTest.php
  tests/StatementTest.php
Labels: BC Break, Prepared Statements, RFC

#3949 Make table and column comments non-nullable strings
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLAnywhere16Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/Column.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySqlSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSqlSchemaManager.php
  src/Schema/SQLAnywhereSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/Table.php
  tests/Functional/Schema/ColumnCommentTest.php
  tests/Functional/Schema/Db2SchemaManagerTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Functional/Ticket/DBAL461Test.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Platforms/SQLAnywhere16PlatformTest.php
  tests/Schema/ColumnTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/SqliteSchemaManagerTest.php
Labels: BC Break, Improvement, Schema, Schema Introspection, Schema Managers

#3948 Manually merge 3.0.x into master
  UPGRADE.md
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Cache/ArrayStatement.php
  src/Cache/ResultCacheStatement.php
  src/Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/PDOStatement.php
  src/Driver/ResultStatement.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Exception/InvalidColumnIndex.php
  src/FetchMode.php
  src/Portability/Statement.php
  src/Statement.php
  tests/Cache/ArrayStatementTest.php
  tests/ConnectionTest.php
  tests/Exception/InvalidColumnIndexTest.php
  tests/Functional/DataAccessTest.php
  tests/Functional/Schema/SQLAnywhereSchemaManagerTest.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Functional/StatementTest.php
  tests/Functional/Types/BinaryTest.php
  tests/Portability/StatementTest.php
  tests/StatementTest.php
  tests/Tools/Console/RunSqlCommandTest.php
  tests/Types/Exception/TypeAlreadyRegisteredTest.php
  tests/Types/Exception/TypeNotRegisteredTest.php
Labels: Merge Up

#3951 Setup static analysis with Psalm
  .github/workflows/continuous-integration.yml
  baseline.xml
  composer.json
  composer.lock
  psalm.xml
Labels: CI, Improvement, Static Analysis

#3952 Manually merge 2.10.x into 2.11.x
  .github/workflows/continuous-integration.yml
  baseline.xml
  composer.json
  composer.lock
  psalm.xml
Labels: Merge Up

#3953 Manually merge 2.11.x into 3.0.x
  .github/workflows/continuous-integration.yml
  baseline.xml
  composer.json
  composer.lock
  psalm.xml
Labels: Merge Up

#3955 Remove baseline
  baseline.xml
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/AbstractDriverException.php
  lib/Doctrine/DBAL/Driver/DriverException.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliException.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php
  lib/Doctrine/DBAL/Driver/PDOException.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereException.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvException.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  psalm.xml
  tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
Labels: CI

#3957 Reworked LoggingTest to be able to test Statement::executeUpdate()
  tests/Doctrine/Tests/DBAL/Connection/LoggingTest.php
  tests/Doctrine/Tests/DBAL/Functional/LoggingTest.php
Labels: Improvement, Logging, Test Suite

#3964 Mark every exception as immutable
  lib/Doctrine/DBAL/Cache/CacheException.php
  lib/Doctrine/DBAL/ConnectionException.php
  lib/Doctrine/DBAL/DBALException.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Exception.php
  lib/Doctrine/DBAL/Exception/ConnectionException.php
  lib/Doctrine/DBAL/Exception/ConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/DatabaseObjectExistsException.php
  lib/Doctrine/DBAL/Exception/DatabaseObjectNotFoundException.php
  lib/Doctrine/DBAL/Exception/DeadlockException.php
  lib/Doctrine/DBAL/Exception/DriverException.php
  lib/Doctrine/DBAL/Exception/ForeignKeyConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/InvalidArgumentException.php
  lib/Doctrine/DBAL/Exception/InvalidFieldNameException.php
  lib/Doctrine/DBAL/Exception/LockWaitTimeoutException.php
  lib/Doctrine/DBAL/Exception/NonUniqueFieldNameException.php
  lib/Doctrine/DBAL/Exception/NotNullConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/ReadOnlyException.php
  lib/Doctrine/DBAL/Exception/ServerException.php
  lib/Doctrine/DBAL/Exception/SyntaxErrorException.php
  lib/Doctrine/DBAL/Exception/TableExistsException.php
  lib/Doctrine/DBAL/Exception/TableNotFoundException.php
  lib/Doctrine/DBAL/Exception/UniqueConstraintViolationException.php
  lib/Doctrine/DBAL/Query/QueryException.php
  lib/Doctrine/DBAL/SQLParserUtilsException.php
  lib/Doctrine/DBAL/Schema/SchemaException.php
  lib/Doctrine/DBAL/Sharding/ShardingException.php
  lib/Doctrine/DBAL/Types/ConversionException.php
Labels: Improvement, Static Analysis

#3961 Stop relying on the master version of Psalm
  .github/workflows/continuous-integration.yml
Labels: CI, Improvement, Static Analysis

#3958 Manually merge 2.10.x into 2.11.x
  .github/workflows/continuous-integration.yml
  baseline.xml
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Cache/CacheException.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/ConnectionException.php
  lib/Doctrine/DBAL/DBALException.php
  lib/Doctrine/DBAL/Driver/AbstractDriverException.php
  lib/Doctrine/DBAL/Driver/DriverException.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Exception.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliException.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php
  lib/Doctrine/DBAL/Driver/PDOException.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereException.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvException.php
  lib/Doctrine/DBAL/Exception/ConnectionException.php
  lib/Doctrine/DBAL/Exception/ConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/DatabaseObjectExistsException.php
  lib/Doctrine/DBAL/Exception/DatabaseObjectNotFoundException.php
  lib/Doctrine/DBAL/Exception/DeadlockException.php
  lib/Doctrine/DBAL/Exception/DriverException.php
  lib/Doctrine/DBAL/Exception/ForeignKeyConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/InvalidArgumentException.php
  lib/Doctrine/DBAL/Exception/InvalidFieldNameException.php
  lib/Doctrine/DBAL/Exception/LockWaitTimeoutException.php
  lib/Doctrine/DBAL/Exception/NonUniqueFieldNameException.php
  lib/Doctrine/DBAL/Exception/NotNullConstraintViolationException.php
  lib/Doctrine/DBAL/Exception/ReadOnlyException.php
  lib/Doctrine/DBAL/Exception/ServerException.php
  lib/Doctrine/DBAL/Exception/SyntaxErrorException.php
  lib/Doctrine/DBAL/Exception/TableExistsException.php
  lib/Doctrine/DBAL/Exception/TableNotFoundException.php
  lib/Doctrine/DBAL/Exception/UniqueConstraintViolationException.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Query/QueryException.php
  lib/Doctrine/DBAL/SQLParserUtilsException.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  lib/Doctrine/DBAL/Schema/SchemaException.php
  lib/Doctrine/DBAL/Sharding/ShardingException.php
  lib/Doctrine/DBAL/Types/ConversionException.php
  psalm.xml
  tests/Doctrine/Tests/DBAL/Connection/LoggingTest.php
  tests/Doctrine/Tests/DBAL/Functional/LoggingTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
Labels: Merge Up

#3959 Manually merge 2.11.x into 3.0.x
  .github/workflows/continuous-integration.yml
  baseline.xml
  composer.json
  composer.lock
  psalm.xml
  src/Cache/CacheException.php
  src/Connection.php
  src/ConnectionException.php
  src/DBALException.php
  src/Driver/AbstractDriverException.php
  src/Driver/DriverException.php
  src/Driver/IBMDB2/DB2Exception.php
  src/Driver/Mysqli/HostRequired.php
  src/Driver/Mysqli/MysqliException.php
  src/Driver/OCI8/OCI8Exception.php
  src/Driver/PDOException.php
  src/Driver/SQLAnywhere/SQLAnywhereException.php
  src/Driver/SQLSrv/SQLSrvException.php
  src/Exception/ConnectionException.php
  src/Exception/ConstraintViolationException.php
  src/Exception/DatabaseObjectExistsException.php
  src/Exception/DatabaseObjectNotFoundException.php
  src/Exception/DeadlockException.php
  src/Exception/DriverException.php
  src/Exception/ForeignKeyConstraintViolationException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/InvalidFieldNameException.php
  src/Exception/LockWaitTimeoutException.php
  src/Exception/NonUniqueFieldNameException.php
  src/Exception/NotNullConstraintViolationException.php
  src/Exception/ReadOnlyException.php
  src/Exception/ServerException.php
  src/Exception/SyntaxErrorException.php
  src/Exception/TableExistsException.php
  src/Exception/TableNotFoundException.php
  src/Exception/UniqueConstraintViolationException.php
  src/Platforms/SqlitePlatform.php
  src/Query/QueryException.php
  src/SQLParserUtilsException.php
  src/Schema/OracleSchemaManager.php
  src/Schema/SchemaException.php
  src/Types/ConversionException.php
  tests/Functional/LoggingTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
Labels: Merge Up

#3965 Sync expected coverage report count
  .scrutinizer.yml
Labels: CI, Oracle, SQL Server, Testing

#3969 Psalm 7
  .scrutinizer.yml
  lib/Doctrine/DBAL/Driver/DriverException.php
  psalm.xml
Labels: Static Analysis

#3971 Manually merge 2.10.x into 2.11.x
  .scrutinizer.yml
  lib/Doctrine/DBAL/Driver/DriverException.php
  psalm.xml
Labels: Merge Up

#3972 Manually merge 2.11.x into 3.0.x
  psalm.xml
  src/Driver/DriverException.php
Labels: Merge Up

#3973 Manually merge 3.0.x into master
  psalm.xml
Labels: Merge Up

#3974 Remove unneeded and risky stubs parsing
  lib/Doctrine/DBAL/Driver/OCI8/Driver.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  phpstan.neon.dist
  tests/phpstan-polyfill.php
Labels: Improvement, Static Analysis

#3978 Use composer install in the Psalm job
  .github/workflows/continuous-integration.yml
Labels: CI
