Repository doctrine/dbal, pull requests merged in 2020-02, with the labels that each got.

#3885 Update branch metadata
  .doctrine-project.json
  README.md
Labels: Improvement

#3884 Use Docker consistently
  .scrutinizer.yml
  .travis.yml
  tests/travis/create-mysql-schema.sql
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/install-mariadb.sh
  tests/travis/install-mysql-5.7.sh
  tests/travis/install-mysql-8.0.sh
  tests/travis/mariadb.mysqli.travis.xml
  tests/travis/mariadb.travis.xml
  tests/travis/mysql.travis.xml
  tests/travis/mysqli.travis.xml
Labels: CI, Improvement, MariaDB, MySQL

#3878 Add missed end of comment
  docs/en/reference/sharding.rst
Labels: Documentation
