Repository doctrine/dbal, pull requests merged in 2020-06, with the labels that each got.

#4051 Fix final class member names according to the coding standard
  phpstan.neon.dist
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/OCI8/OCI8Statement.php
Labels: Code Style, Improvement, mysqli, oci8

#4048 Make caching layer not rely on closeCursor()
  docs/en/reference/caching.rst
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  tests/Doctrine/Tests/DBAL/Functional/ResultCacheTest.php
Labels: Cache, Improvement, Prepared Statements

#4049 Replace forward-compatible ResultStatement interfaces with Result
  UPGRADE.md
  lib/Doctrine/DBAL/Abstraction/Result.php
  lib/Doctrine/DBAL/Cache/ArrayStatement.php
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/FetchUtils.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/Result.php
  lib/Doctrine/DBAL/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/ForwardCompatibility/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Portability/Statement.php
  lib/Doctrine/DBAL/Statement.php
Labels: Cache, Deprecation, Improvement, Prepared Statements

#4045 Extract Result from the Statement interface
  UPGRADE.md
  phpcs.xml.dist
  phpstan.neon.dist
  src/Cache/ArrayResult.php
  src/Cache/CachingResult.php
  src/Connection.php
  src/Connections/MasterSlaveConnection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/IBMDB2/Result.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/Mysqli/Result.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/OCI8/Result.php
  src/Driver/PDO/Result.php
  src/Driver/PDOConnection.php
  src/Driver/PDOSqlsrv/Connection.php
  src/Driver/PDOStatement.php
  src/Driver/Result.php
  src/Driver/ResultStatement.php
  src/Driver/SQLAnywhere/Result.php
  src/Driver/SQLAnywhere/SQLAnywhereConnection.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/Driver/SQLSrv/Result.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Driver/Statement.php
  src/Portability/Connection.php
  src/Portability/Result.php
  src/Portability/Statement.php
  src/Query/QueryBuilder.php
  src/Result.php
  src/Statement.php
  tests/Connection/LoggingTest.php
  tests/ConnectionTest.php
  tests/Driver/AbstractMySQLDriverTest.php
  tests/Driver/AbstractPostgreSQLDriverTest.php
  tests/Functional/DataAccessTest.php
  tests/Functional/Driver/OCI8/StatementTest.php
  tests/Functional/Driver/PDOPgSql/DriverTest.php
  tests/Functional/LikeWildcardsEscapingTest.php
  tests/Functional/MasterSlaveConnectionTest.php
  tests/Functional/NamedParametersTest.php
  tests/Functional/PortabilityTest.php
  tests/Functional/ResultCacheTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Functional/StatementTest.php
  tests/Functional/Ticket/DBAL421Test.php
  tests/Functional/WriteTest.php
  tests/Portability/ResultTest.php
  tests/Portability/StatementTest.php
Labels: BC Break, Improvement, Prepared Statements

#4058 Add tests for fetch*() methods of Portability\Result
  tests/Portability/ResultTest.php
Labels: Portability, Test Suite

#4063 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  src/Connections/MasterSlaveConnection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/DriverManager.php
  src/Portability/Connection.php
  src/Portability/OptimizeFlags.php
  tests/DriverManagerTest.php
  tests/Functional/PrimaryReadReplicaConnectionTest.php
  tests/Portability/OptimizeFlagsTest.php
Labels: Merge Up

#4064 Remove platform-specific portability mode constants
  UPGRADE.md
  src/Portability/Connection.php
Labels: BC Break, Improvement, Portability

#4067 Simplify test suite configuration
  phpunit.xml.dist
  tests/Doctrine/Tests/DBAL/Driver/PDOPgSql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/OracleSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/SQLAzure/AbstractTestCase.php
  tests/Doctrine/Tests/TestUtil.php
  tests/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  tests/continuousphp/oci8.phpunit.continuousphp.xml
  tests/continuousphp/pdo-oci.phpunit.xml
  tests/travis/ibm_db2.travis.xml
  tests/travis/mariadb.docker.travis.xml
  tests/travis/mariadb.mysqli.docker.travis.xml
  tests/travis/mysql.docker.travis.xml
  tests/travis/mysqli.docker.travis.xml
  tests/travis/pdo_sqlsrv.travis.xml
  tests/travis/pgsql.travis.xml
  tests/travis/sqlsrv.travis.xml
Labels: Improvement, Test Suite

#4066 Fix DSN detection in the IBM DB2 driver
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Driver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DataSourceName.php
  tests/Doctrine/Tests/DBAL/Driver/IBMDB2/DataSourceNameTest.php
  tests/travis/ibm_db2.travis.xml
Labels: Bug, Connections, Improvement, ibm_db2

#4068 Deprecate Driver::getDatabase()
  UPGRADE.md
  lib/Doctrine/DBAL/Driver.php
  lib/Doctrine/DBAL/Driver/AbstractDB2Driver.php
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
Labels: Connections, Databases, Deprecation, Drivers

#4070 Manually merge 2.10.x into 2.11.x
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Driver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DataSourceName.php
  phpunit.xml.dist
  tests/Doctrine/Tests/DBAL/Driver/IBMDB2/DataSourceNameTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOPgSql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/OracleSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/SQLAzure/AbstractTestCase.php
  tests/Doctrine/Tests/TestUtil.php
  tests/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  tests/continuousphp/oci8.phpunit.continuousphp.xml
  tests/continuousphp/pdo-oci.phpunit.xml
  tests/travis/ibm_db2.travis.xml
  tests/travis/mariadb.docker.travis.xml
  tests/travis/mariadb.mysqli.docker.travis.xml
  tests/travis/mysql.docker.travis.xml
  tests/travis/mysqli.docker.travis.xml
  tests/travis/pdo_sqlsrv.travis.xml
  tests/travis/pgsql.travis.xml
  tests/travis/sqlsrv.travis.xml
Labels: Merge Up

#4071 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  ci/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  ci/continuousphp/oci8.phpunit.continuousphp.xml
  ci/continuousphp/pdo-oci.phpunit.xml
  ci/travis/ibm_db2.travis.xml
  ci/travis/mariadb.docker.travis.xml
  ci/travis/mariadb.mysqli.docker.travis.xml
  ci/travis/mysql.docker.travis.xml
  ci/travis/mysqli.docker.travis.xml
  ci/travis/pdo_sqlsrv.travis.xml
  ci/travis/pgsql.travis.xml
  ci/travis/sqlsrv.travis.xml
  phpunit.xml.dist
  src/Driver.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLAnywhereDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
  src/Driver/IBMDB2/DB2Driver.php
  src/Driver/IBMDB2/DataSourceName.php
  tests/Driver/IBMDB2/DataSourceNameTest.php
  tests/Driver/PDOPgSql/DriverTest.php
  tests/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/TestUtil.php
Labels: Merge Up

#4072 Driver::connect() should throw only driver-level exceptions
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver.php
  src/Driver/Mysqli/Driver.php
  src/Driver/OCI8/Driver.php
  src/Driver/PDOMySql/Driver.php
  src/Driver/PDOOracle/Driver.php
  src/Driver/PDOPgSql/Driver.php
  src/Driver/PDOSqlite/Driver.php
  src/Driver/SQLAnywhere/Driver.php
  tests/ConnectionTest.php
Labels: BC Break, Connecting, Drivers, Error Handling

#4074 Fix handling host and port configuration in sqlsrv and pdo_sqlsrv drivers
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver/PortWithoutHost.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Driver.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLServerDriverTest.php
Labels: Bug, Connecting, pdo_sqlsrv, sqlsrv

#4077 Remove SQL Anywhere platform and driver
  UPGRADE.md
  composer.json
  docs/en/reference/configuration.rst
  docs/en/reference/introduction.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/types.rst
  psalm.xml
  src/Driver/AbstractSQLAnywhereDriver.php
  src/Driver/SQLAnywhere/Driver.php
  src/Driver/SQLAnywhere/Result.php
  src/Driver/SQLAnywhere/SQLAnywhereConnection.php
  src/Driver/SQLAnywhere/SQLAnywhereException.php
  src/Driver/SQLAnywhere/SQLAnywhereStatement.php
  src/DriverManager.php
  src/Platforms/Keywords/SQLAnywhereKeywords.php
  src/Platforms/SQLAnywhere16Platform.php
  src/Portability/OptimizeFlags.php
  src/Schema/SQLAnywhereSchemaManager.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  tests/Driver/AbstractSQLAnywhereDriverTest.php
  tests/Driver/SQLAnywhere/DriverTest.php
  tests/Driver/SQLAnywhere/SQLAnywhereConnectionTest.php
  tests/Functional/Driver/SQLAnywhere/ConnectionTest.php
  tests/Functional/Driver/SQLAnywhere/DriverTest.php
  tests/Functional/Driver/SQLAnywhere/StatementTest.php
  tests/Functional/Schema/SQLAnywhereSchemaManagerTest.php
  tests/Functional/TemporaryTableTest.php
  tests/Platforms/SQLAnywhere16PlatformTest.php
Labels: BC Break, SQL Anywhere, sqlanywhere

#4078 Bump PHP requirement to 7.3 as of DBAL 2.11.0
  .travis.yml
  composer.json
  composer.lock
Labels: PHP

#4079 Forward compatibility with PHPUnit 9.3
  tests/Doctrine/Tests/DBAL/Driver/OCI8/OCI8StatementTest.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Doctrine/Tests/DBAL/Tools/Console/RunSqlCommandTest.php
Labels: Improvement, Test Suite

#4080 Update PHPUnit to 9.2
  composer.json
  composer.lock
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/PortabilityTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SQLAnywhereSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Tools/Console/RunSqlCommandTest.php
  tests/Doctrine/Tests/DBAL/Types/ConversionExceptionTest.php
Labels: Improvement, Test Suite

#4081 Simplify Driver::connect() signature
  UPGRADE.md
  phpcs.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/IBMDB2/DB2Driver.php
  src/Driver/Mysqli/Driver.php
  src/Driver/Mysqli/Exception/InvalidCharset.php
  src/Driver/Mysqli/Exception/InvalidOption.php
  src/Driver/Mysqli/Initializer.php
  src/Driver/Mysqli/Initializer/Charset.php
  src/Driver/Mysqli/Initializer/Options.php
  src/Driver/Mysqli/Initializer/Secure.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/OCI8/Driver.php
  src/Driver/PDOMySql/Driver.php
  src/Driver/PDOOracle/Driver.php
  src/Driver/PDOPgSql/Driver.php
  src/Driver/PDOSqlite/Driver.php
  src/Driver/PDOSqlsrv/Driver.php
  src/Driver/SQLSrv/Driver.php
  tests/Driver/Mysqli/MysqliConnectionTest.php
  tests/Driver/PDOPgSql/DriverTest.php
  tests/Functional/Driver/AbstractDriverTest.php
  tests/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Functional/Driver/PDOPgSql/DriverTest.php
  tests/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: BC Break, Connecting, Connections, Drivers, Improvement

#4084 Allow using on PHP 7.3 with Composer 2
  composer.json
Labels: Improvement, Tools

#4085 The IBM DB2 driver Exception class must implement the DriverException interface
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Exception.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/IBMDB2/Exception/ConnectionError.php
  lib/Doctrine/DBAL/Driver/IBMDB2/Exception/ConnectionFailed.php
  lib/Doctrine/DBAL/Driver/IBMDB2/Exception/PrepareFailed.php
  lib/Doctrine/DBAL/Driver/IBMDB2/Exception/StatementError.php
  phpcs.xml.dist
  tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2StatementTest.php
Labels: Bug, Drivers, ibm_db2

#4086 Mark Connection::getParams() internal
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Id/TableGenerator.php
Labels: Configuration, Connections

#4087 Manually merge 2.10.x into 2.11.x
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver/PortWithoutHost.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Driver.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLServerDriverTest.php
Labels: Merge Up

#4088 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  composer.json
  composer.lock
  phpcs.xml.dist
  src/Connection.php
  src/Driver/AbstractSQLServerDriver/PortWithoutHost.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/IBMDB2/DB2Exception.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/IBMDB2/Exception/ConnectionError.php
  src/Driver/IBMDB2/Exception/ConnectionFailed.php
  src/Driver/IBMDB2/Exception/PrepareFailed.php
  src/Driver/IBMDB2/Exception/StatementError.php
  src/Driver/PDOSqlsrv/Driver.php
  src/Driver/SQLSrv/Driver.php
  src/Id/TableGenerator.php
  tests/Driver/AbstractSQLServerDriverTest.php
  tests/Functional/DataAccessTest.php
  tests/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Functional/Driver/IBMDB2/DB2StatementTest.php
  tests/Schema/SchemaTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Tools/Console/RunSqlCommandTest.php
Labels: Merge Up

#4092 Remove Connection::$isConnected
  lib/Doctrine/DBAL/Connection.php
Labels: Connections, Improvement

#4089 Remove the CommentedType class from tests
  tests/Doctrine/Tests/Types/CommentedType.php
Labels: Test Suite

#4091 Get rid of the call to Connection::getParams() in Portability\Statement
  src/Portability/Connection.php
Labels: Configuration, Connections, Improvement

#4090 Make the $database argument of OracleSchemaManager::createDatabase() mandatory
  UPGRADE.md
  src/Schema/OracleSchemaManager.php
Labels: Oracle, Schema Managers

#4094 Bump Psalm level to 5
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/Statement.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  phpstan.neon.dist
  psalm.xml
  tests/Doctrine/Tests/DBAL/Driver/DrizzlePDOMySql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/StatementIteratorTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Ticket/DBAL630Test.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/DB2PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
Labels: Improvement, Static Analysis

#4099 Update PHPStan to 0.12.30
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  phpstan.neon.dist
Labels: Improvement, Static Analysis

#4101 Manually merge 2.10.x into 2.11.x
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  phpstan.neon.dist
Labels: Merge Up

#4107 Remove the suppressed errors that PHPStan no longer reports
  phpstan.neon.dist
Labels: Improvement, Static Analysis

#4110 Mark non-interface OCI8 driver methods internal
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
Labels: Deprecation, Prepared Statements, SQL Parser, oci8

#4112 Deprecate DriverException::getErrorCode()
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/Exception.php
Labels: Deprecation, Drivers, Error Handling

#4113 Remove DriverException::getErrorCode()
  UPGRADE.md
  src/Driver/AbstractException.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/Exception.php
  src/Driver/PDOException.php
  src/Driver/SQLSrv/Exception/Error.php
  src/Exception/DriverException.php
  src/Schema/OracleSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  tests/Driver/AbstractDriverTest.php
  tests/Driver/AbstractMySQLDriverTest.php
  tests/Driver/AbstractOracleDriverTest.php
  tests/Driver/AbstractPostgreSQLDriverTest.php
  tests/Driver/AbstractSQLiteDriverTest.php
  tests/Driver/PDO/ExceptionTest.php
  tests/Functional/WriteTest.php
Labels: BC Break, Drivers, Error Handling

#4109 Preparation to marking OCI8 driver classes final
  psalm.xml
  src/Driver/OCI8/ConvertPositionalToNamedPlaceholders.php
  src/Driver/OCI8/ExecutionMode.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/OCI8/OCI8Statement.php
  tests/Driver/OCI8/ConvertPositionalToNamedPlaceholdersTest.php
  tests/Driver/OCI8/ExecutionModeTest.php
  tests/Driver/OCI8/OCI8StatementTest.php
Labels: Improvement, Prepared Statements, SQL Parser, oci8

#4115 Remove ServerInfoAwareConnection#requiresQueryForServerVersion() as an implementation detail
  UPGRADE.md
  src/Connection.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/OCI8/OCI8Connection.php
  src/Driver/PDOConnection.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/ServerInfoAwareConnection.php
  tests/ConnectionTest.php
  tests/Driver/IBMDB2/DB2ConnectionTest.php
  tests/Driver/Mysqli/MysqliConnectionTest.php
  tests/Driver/OCI8/OCI8ConnectionTest.php
  tests/Driver/SQLSrv/SQLSrvConnectionTest.php
  tests/Functional/Driver/PDO/ConnectionTest.php
Labels: BC Break, Connections, Platform Detection

#4116 Update PHPStan to 0.12.31
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Improvement, Static Analysis

#4117 Fixes for the recently introduced driver-level deprecations
  lib/Doctrine/DBAL/Driver/IBMDB2/Connection.php
  lib/Doctrine/DBAL/Driver/IBMDB2/Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/Statement.php
  lib/Doctrine/DBAL/Driver/OCI8/Connection.php
  lib/Doctrine/DBAL/Driver/OCI8/Statement.php
  lib/Doctrine/DBAL/Driver/PDO/Connection.php
  lib/Doctrine/DBAL/Driver/PDO/Statement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Connection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/Statement.php
Labels: Bug, Connections, Improvement, Prepared Statements

#4118 Deprecate ExceptionConverterDriver
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/AbstractDB2Driver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/ExceptionConverterDriver.php
  phpcs.xml.dist
Labels: Deprecation, Drivers, Error Handling, Improvement

#4120 Update Slevomat Coding Standard to 6.3.10
  composer.lock
  tests/Doctrine/Tests/DBAL/Driver/StatementIteratorTest.php
Labels: Code Style, Improvement

#4119 Deprecate PingableConnection in favor of handling lost connection
  UPGRADE.md
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/PingableConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Exception/ConnectionLost.php
  lib/Doctrine/DBAL/Statement.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/Connection/ConnectionLostTest.php
  tests/Doctrine/Tests/DBAL/StatementTest.php
Labels: Connections, Deprecation, Error Handling, Improvement

#4121 Manually merge 2.10.x into 2.11.x
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Merge Up

#4114 Deprecate ServerInfoAwareConnection#requiresQueryForServerVersion() as an implementation detail
  UPGRADE.md
  lib/Doctrine/DBAL/Driver/ServerInfoAwareConnection.php
Labels: Connections, Deprecation, Platform Detection

#4123 Remove the no longer needed error suppressions
  phpcs.xml.dist
  phpstan.neon.dist
Labels: Code Style, Improvement, Static Analysis

#4124 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  composer.json
  composer.lock
  phpcs.xml.dist
  phpstan.neon.dist
  src/Connection.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/ExceptionConverterDriver.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/IBMDB2/DB2Statement.php
  src/Driver/IBMDB2/Statement.php
  src/Driver/Mysqli/Connection.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/Mysqli/Statement.php
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/OCI8Statement.php
  src/Driver/OCI8/Statement.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/Statement.php
  src/Driver/PDOStatement.php
  src/Driver/PingableConnection.php
  src/Driver/SQLSrv/Connection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Driver/SQLSrv/Statement.php
  src/Exception/ConnectionLost.php
  src/Result.php
  src/Statement.php
  tests/Functional/Connection/ConnectionLostTest.php
  tests/StatementTest.php
Labels: Merge Up

#4126 Use relative names in inline {@link} annotations where possible
  lib/Doctrine/DBAL/Driver/AbstractDB2Driver.php
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Driver/ExceptionConverterDriver.php
  lib/Doctrine/DBAL/Driver/ResultStatement.php
  lib/Doctrine/DBAL/Driver/Statement.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Sharding/ShardManager.php
  lib/Doctrine/DBAL/Types/Type.php
Labels: Documentation, Improvement

#4127 Rework extension detection in tests
  tests/Doctrine/Tests/DBAL/Driver/IBMDB2/DB2ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/Mysqli/MysqliConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/OCI8/OCI8ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/OCI8/OCI8StatementTest.php
  tests/Doctrine/Tests/DBAL/Driver/PDOExceptionTest.php
  tests/Doctrine/Tests/DBAL/Driver/SQLAnywhere/SQLAnywhereConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/SQLSrv/SQLSrvConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/OCI8/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/OCI8/OCI8ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/OCI8/StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOMySql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOOracle/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOPgSql/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOPgsqlConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlite/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLAnywhere/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLAnywhere/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLAnywhere/StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLSrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/SQLSrv/StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/PDOStatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Drivers, Improvement, Test Suite

#4128 Remove PingableConnection
  UPGRADE.md
  src/Connection.php
  src/Driver/Mysqli/Connection.php
  src/Driver/PingableConnection.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/Mysqli/ConnectionTest.php
Labels: BC Break, Connections

#4131 Restore the PortWithoutHost exception parent class
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver/Exception/PortWithoutHost.php
Labels: BC Break, Drivers, Error Handling, pdo_sqlsrv, sqlsrv

#4106 respect to platform restrictions when creating autoincrement identifier name
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  tests/Doctrine/Tests/DBAL/Functional/Platform/PlatformRestrictionsTest.php
Labels: Bug, Oracle, Platforms, Schema Managers

#4129 Remove ExceptionConverterDriver
  UPGRADE.md
  src/DBALException.php
  src/Driver.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
  src/Driver/ExceptionConverterDriver.php
  tests/Driver/AbstractDriverTest.php
  tests/Functional/ExceptionTest.php
Labels: BC Break, Drivers, Error Handling

#4133 Fix more issues introduced by the deprecation of driver classes
  lib/Doctrine/DBAL/Driver/PDOException.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
  phpcs.xml.dist
Labels: Code Style, Documentation
