Repository doctrine/dbal, pull requests merged in 2020-03, with the labels that each got.

#3886 Update readme
  README.md
Labels: Documentation, Improvement

#3222 Allow add previous exception in ConversionException
  lib/Doctrine/DBAL/Types/ConversionException.php
  tests/Doctrine/Tests/DBAL/Types/ConversionExceptionTest.php
Labels: Improvement

#3894 Make sure that the $types array has the same keys $params
  lib/Doctrine/DBAL/SQLParserUtils.php
  tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
Labels: Bug, Prepared Statements

#3896 Updated documentation for QueryBuilder::execute() return value type
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  phpstan.neon.dist
Labels: Bug, Documentation, Prepared Statements, Query

#3897 Manually merge 2.10.x into 2.11.x
  .scrutinizer.yml
  .travis.yml
  README.md
  docs/en/reference/sharding.rst
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Logging/DebugStack.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Schema/ForeignKeyConstraint.php
  lib/Doctrine/DBAL/Types/ConversionException.php
  lib/Doctrine/DBAL/Version.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
  tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
  tests/Doctrine/Tests/DBAL/Schema/ForeignKeyConstraintTest.php
  tests/Doctrine/Tests/DBAL/Types/ConversionExceptionTest.php
  tests/travis/create-mysql-schema.sql
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/install-mysql-5.7.sh
  tests/travis/install-mysql-8.0.sh
  tests/travis/install-sqlsrv-dependencies.sh
  tests/travis/mariadb.docker.travis.xml
  tests/travis/mariadb.mysqli.docker.travis.xml
  tests/travis/mariadb.mysqli.travis.xml
  tests/travis/mysqli.travis.xml
Labels: Merge Up

#3898 Bump version to 2.11.0-DEV
  lib/Doctrine/DBAL/Version.php
Labels: Improvement

#3900 Drop support for PHP 7.2
  .scrutinizer.yml
  .travis.yml
  composer.json
  composer.lock
Labels: CI, Improvement, PHP

#3902 Manually merge 2.11.x into 3.0.x
  .scrutinizer.yml
  .travis.yml
  README.md
  docs/en/reference/sharding.rst
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Logging/DebugStack.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Schema/ForeignKeyConstraint.php
  lib/Doctrine/DBAL/Types/ConversionException.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
  tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
  tests/Doctrine/Tests/DBAL/Schema/ForeignKeyConstraintTest.php
  tests/Doctrine/Tests/DBAL/Types/ConversionExceptionTest.php
  tests/travis/create-mysql-schema.sql
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/install-mysql-5.7.sh
  tests/travis/install-mysql-8.0.sh
  tests/travis/mariadb.mysqli.travis.xml
  tests/travis/mariadb.travis.xml
  tests/travis/mysql.travis.xml
  tests/travis/mysqli.travis.xml
Labels: Merge Up

#3903 Upgrade PHPUnit to 9.0
  UPGRADE.md
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/PingableConnection.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/ServerInfoAwareConnection.php
  lib/Doctrine/DBAL/VersionAwarePlatformDriver.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/OCI8/OCI8StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/PortabilityTest.php
Labels: BC Break, Connections, Drivers, Improvement, Test Suite

#3905 Deprecate the usage of the legacy platforms and drivers
  UPGRADE.md
  docs/en/reference/platforms.rst
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Connection.php
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOIbm/Driver.php
  lib/Doctrine/DBAL/Platforms/DrizzlePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL91Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL92Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere11Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere12Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAzurePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2005Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2008Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php
  lib/Doctrine/DBAL/Sharding/PoolingShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureFederationsSynchronizer.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/Schema/MultiTenantVisitor.php
  lib/Doctrine/DBAL/Sharding/ShardChoser/MultiTenantShardChoser.php
  lib/Doctrine/DBAL/Sharding/ShardChoser/ShardChoser.php
  lib/Doctrine/DBAL/Sharding/ShardManager.php
  lib/Doctrine/DBAL/Sharding/ShardingException.php
Labels: Azure, Deprecation, Drivers, Drizzle, MariaDB, Platforms, PostgreSQL, SQL Anywhere, SQL Server, Sharding, pdo_ibm

#3904 Manually merge 3.0.x into master
  .scrutinizer.yml
  .travis.yml
  UPGRADE.md
  composer.json
  composer.lock
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Logging/DebugStack.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Types/Exception/InvalidType.php
  lib/Doctrine/DBAL/Types/Exception/SerializationFailed.php
  lib/Doctrine/DBAL/Types/Exception/ValueNotConvertible.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/DB2StatementTest.php
  tests/Doctrine/Tests/DBAL/Functional/PortabilityTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
  tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
  tests/Doctrine/Tests/DBAL/Types/ConversionExceptionTest.php
  tests/travis/create-mysql-schema.sql
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/install-mysql-5.7.sh
  tests/travis/install-mysql-8.0.sh
  tests/travis/mariadb.mysqli.travis.xml
  tests/travis/mariadb.travis.xml
  tests/travis/mysql.travis.xml
  tests/travis/mysqli.travis.xml
Labels: Merge Up

#3908 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  docs/en/reference/platforms.rst
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Connection.php
  lib/Doctrine/DBAL/Driver/DrizzlePDOMySql/Driver.php
  lib/Doctrine/DBAL/Driver/PDOIbm/Driver.php
  lib/Doctrine/DBAL/Platforms/DrizzlePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL91Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL92Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere11Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere12Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAzurePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2005Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2008Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php
  lib/Doctrine/DBAL/Sharding/PoolingShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureFederationsSynchronizer.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/SQLAzureShardManager.php
  lib/Doctrine/DBAL/Sharding/SQLAzure/Schema/MultiTenantVisitor.php
  lib/Doctrine/DBAL/Sharding/ShardChoser/MultiTenantShardChoser.php
  lib/Doctrine/DBAL/Sharding/ShardChoser/ShardChoser.php
  lib/Doctrine/DBAL/Sharding/ShardManager.php
  lib/Doctrine/DBAL/Sharding/ShardingException.php
Labels: Merge Up

#3912 Made some platform class names reflect the lowest server version they support
  UPGRADE.md
  docs/en/reference/platforms.rst
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQL100Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQL94Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhere11Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhere12Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhere16Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhereKeywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2005Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2008Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2012Keywords.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL100Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL94Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere16Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2008Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLAnywhereSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Driver/AbstractPostgreSQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLAnywhereDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLServerDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOPgsqlConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL100PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL94PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywhere16PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
  tests/Doctrine/Tests/DBAL/Schema/ColumnTest.php
Labels: Improvement, Platforms, PostgreSQL, SQL Anywhere, SQL Server

#3914 Manually merge 3.0.x into master
  UPGRADE.md
  docs/en/reference/configuration.rst
  docs/en/reference/platforms.rst
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLAnywhereDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQL100Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/PostgreSQL94Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLAnywhere16Keywords.php
  lib/Doctrine/DBAL/Platforms/Keywords/SQLServer2012Keywords.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL100Platform.php
  lib/Doctrine/DBAL/Platforms/PostgreSQL94Platform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywhere16Platform.php
  lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLAnywhereSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractPostgreSQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLAnywhereDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLServerDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOPgsqlConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Platform/ColumnTest/PostgreSQL.php
  tests/Doctrine/Tests/DBAL/Functional/Platform/ColumnTest/SQLServer.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL100PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL94PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywhere16PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatform2012Test.php
  tests/Doctrine/Tests/DBAL/Schema/ColumnTest.php
Labels: Merge Up

#3893 Ensure the constructor arguments are passed to custom classes
  lib/Doctrine/DBAL/Statement.php
  tests/Doctrine/Tests/DBAL/StatementTest.php
Labels: Bug, Prepared Statements

#3923 Removed performance tests
  phpunit.xml.dist
  tests/Doctrine/Tests/DBAL/Performance/TypeConversionPerformanceTest.php
  tests/Doctrine/Tests/DbalPerformanceTestCase.php
  tests/Doctrine/Tests/DbalPerformanceTestListener.php
Labels: Improvement, Test Suite

#3924 Actualize the content of the .gitattributes file
  .gitattributes
Labels: Improvement, Packaging

#3799 Upgrade to PHPStan v0.12
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Cache/ArrayStatement.php
  lib/Doctrine/DBAL/Configuration.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  lib/Doctrine/DBAL/DBALException.php
  lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/LastInsertId.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/Event/Listeners/OracleSessionInit.php
  lib/Doctrine/DBAL/Id/TableGenerator.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/DB2Platform.php
  lib/Doctrine/DBAL/Platforms/DrizzlePlatform.php
  lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
  lib/Doctrine/DBAL/Schema/ForeignKeyConstraint.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SQLAnywhereSchemaManager.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  lib/Doctrine/DBAL/Schema/Synchronizer/AbstractSchemaSynchronizer.php
  lib/Doctrine/DBAL/Schema/Table.php
  lib/Doctrine/DBAL/Schema/Visitor/NamespaceVisitor.php
  lib/Doctrine/DBAL/Schema/Visitor/SchemaDiffVisitor.php
  lib/Doctrine/DBAL/Tools/Console/Command/ImportCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
  lib/Doctrine/DBAL/Tools/Console/ConsoleRunner.php
  lib/Doctrine/DBAL/Tools/Dumper.php
  lib/Doctrine/DBAL/Types/ConversionException.php
  phpstan.neon.dist
Labels: CI, Improvement

#3928 Manually merge 2.11.x into 3.0.x
  .gitattributes
  composer.json
  composer.lock
  phpstan.neon.dist
  phpunit.xml.dist
  src/Cache/ArrayStatement.php
  src/Configuration.php
  src/Connection.php
  src/Connections/MasterSlaveConnection.php
  src/DBALException.php
  src/Driver/IBMDB2/DB2Connection.php
  src/Driver/Mysqli/MysqliConnection.php
  src/Driver/Mysqli/MysqliStatement.php
  src/Driver/PDOStatement.php
  src/Driver/SQLSrv/LastInsertId.php
  src/Driver/SQLSrv/SQLSrvConnection.php
  src/Driver/SQLSrv/SQLSrvStatement.php
  src/Event/Listeners/OracleSessionInit.php
  src/Id/TableGenerator.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MySqlPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLAnywhere16Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Query/QueryBuilder.php
  src/Schema/DB2SchemaManager.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSqlSchemaManager.php
  src/Schema/SQLAnywhereSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/Synchronizer/AbstractSchemaSynchronizer.php
  src/Schema/Table.php
  src/Schema/Visitor/NamespaceVisitor.php
  src/Schema/Visitor/SchemaDiffVisitor.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
  src/Tools/Console/ConsoleRunner.php
  src/Tools/Dumper.php
  src/Types/ConversionException.php
  tests/Performance/TypeConversionPerformanceTest.php
  tests/PerformanceTestCase.php
  tests/PerformanceTestListener.php
  tests/StatementTest.php
Labels: Merge Up
