Repository doctrine/dbal, pull requests merged in 2020-12, with the labels that each got.

#4438 #4437 MSSQL adds a redundant ORDER BY clause when with subquery with …
  lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php
  tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
Labels: Query Limit/Offset Modification, SQL Server

#4260 Fix and improve docs
  docs/en/reference/caching.rst
  docs/en/reference/platforms.rst
  docs/en/reference/schema-manager.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/sharding_azure_tutorial.rst
  docs/en/reference/supporting-other-databases.rst
Labels: Documentation

#4457 Add note about lost connections to UPGRADE guide.
  UPGRADE.md
Labels: Connections, Documentation, Error Handling

#4463 Use the ramsey/composer-install action to install dependencies
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
Labels: CI

#4466 Update PHPUnit to 9.5
  composer.json
  composer.lock
Labels: Test Suite
