Repository doctrine/dbal, pull requests merged in 2020-09, with the labels that each got.

#3980 [3.0] Segregated support of unique index and unique constraint.
  UPGRADE.md
  src/Platforms/AbstractPlatform.php
  src/Platforms/MySqlPlatform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Index.php
  src/Schema/SchemaException.php
  src/Schema/Table.php
  src/Schema/UniqueConstraint.php
  tests/Functional/ExceptionTest.php
  tests/Functional/Platform/NewPrimaryKeyWithNewAutoIncrementColumnTest.php
  tests/Functional/Schema/MySqlSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Schema/ComparatorTest.php
  tests/Schema/TableTest.php
Labels: Blocker, Compatibility, Improvement, New Feature

#4241 Manually merge 2.10.x into 2.11.x
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/travis/install-mssql.sh
Labels: Merge Up

#4246 SQLite: Fix wrongly detected reference constraint name on schema change
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Bug, Foreign Keys, SQLite, Schema Managers

#4268 Handle both ways of PDO reporting failed connection
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
Labels: Bug, PHP, pdo_pgsql

#4255 Revert full support for foreign key constraints for SQLite
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Internal/DependencyOrderCalculator.php
  lib/Doctrine/DBAL/Internal/DependencyOrderEdge.php
  lib/Doctrine/DBAL/Internal/DependencyOrderNode.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Schema/SchemaDiff.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php
  lib/Doctrine/DBAL/Schema/Visitor/DropSchemaSqlCollector.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/ForeignKeyTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Internal/DependencyOrderCalculatorTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaDiffTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Foreign Keys, Regression, SQLite

#4273 Manually merge 2.10.x into 2.11.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php
  lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
  lib/Doctrine/DBAL/Internal/DependencyOrderCalculator.php
  lib/Doctrine/DBAL/Internal/DependencyOrderEdge.php
  lib/Doctrine/DBAL/Internal/DependencyOrderNode.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
  lib/Doctrine/DBAL/Schema/SchemaDiff.php
  lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php
  lib/Doctrine/DBAL/Schema/Visitor/DropSchemaSqlCollector.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/ForeignKeyTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Internal/DependencyOrderCalculatorTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaDiffTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#4251 Setup automatic release workflow
  .github/workflows/release-on-milestone-closed.yml
Labels: CI

#4274 Support ASCII parameter binding
  docs/en/reference/types.rst
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
  lib/Doctrine/DBAL/Driver/PDOSqlsrv/Statement.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php
  lib/Doctrine/DBAL/ParameterType.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Types/AsciiStringType.php
  lib/Doctrine/DBAL/Types/Type.php
  lib/Doctrine/DBAL/Types/Types.php
  tests/Doctrine/Tests/DBAL/Functional/ParameterTypes/AsciiTest.php
  tests/Doctrine/Tests/DBAL/Functional/Types/AsciiStringTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
  tests/Doctrine/Tests/DBAL/Types/AsciiStringTest.php
Labels: Improvement, Prepared Statements, SQL Server, Types, pdo_sqlsrv, sqlsrv

#4271 Add explanation about implicit indexes
  docs/en/explanation/implicit-indexes.rst
  docs/en/sidebar.rst
  lib/Doctrine/DBAL/Schema/Table.php
Labels: Documentation

#4278 Remove deprecated APIs
  UPGRADE.md
  src/DBALException.php
  src/Driver/SQLSrv/Statement.php
  src/Exception.php
  src/Platforms/AbstractPlatform.php
  src/Types/StringType.php
  src/Types/Type.php
  tests/ExceptionTest.php
  tests/Types/StringTest.php
Labels: BC Break, Error Handling, Platforms, Types

#4286 Fix BC break: QueryBuilder::andWhere() etc. should ignore empty strings
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
Labels: BC Fix, Query

#4285 Fix phpdoc on deprecated functions
  lib/Doctrine/DBAL/Connection.php
Labels: Bug, Documentation, Prepared Statements

#4287 Restore PDOStatement::quote() for backward compatibility
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  phpcs.xml.dist
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDO/ConnectionTest.php
Labels: BC Fix, Quoting

#4291 Deprecate Abstraction\Result
  UPGRADE.md
  lib/Doctrine/DBAL/Abstraction/Result.php
Labels: Deprecation, Prepared Statements

#4173 Fix Third parameter not allowed for PDO::FETCH_COLUMN
  lib/Doctrine/DBAL/Statement.php
  tests/Doctrine/Tests/DBAL/Functional/ExternalPDOInstanceTest.php
  tests/Doctrine/Tests/DBAL/Functional/StatementTestModel.php
Labels: Bug, PDO, Prepared Statements

#4297 Fix ExceptionTest::testConnectionExceptionSqLite() on macOS
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
Labels: SQLite, Test Suite, pdo_sqlite

#4299 Link to contributing guide
  CONTRIBUTING.md
Labels: Documentation

#4300 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  src/Abstraction/Result.php
Labels: Merge Up

#4293 Add Result::fetchAllKeyValue() and ::iterateKeyValue()
  docs/en/reference/data-retrieval-and-manipulation.rst
  src/Abstraction/Result.php
  src/Connection.php
  src/Exception/NoKeyValue.php
  src/Result.php
  tests/Functional/Connection/FetchTest.php
Labels: Improvement, Prepared Statements

#4301 Remove irrelevant deprecation message from console runner
  src/Tools/Console/ConsoleRunner.php
Labels: Console, Documentation

#4294 Remove Abstraction\Result
  UPGRADE.md
  src/Abstraction/Result.php
  src/Cache/CachingResult.php
  src/Connection.php
  src/Query/QueryBuilder.php
  src/Result.php
  tests/ConnectionTest.php
  tests/Functional/ResultCacheTest.php
  tests/Functional/StatementTest.php
Labels: BC Break, Prepared Statements

#4307 Adapt StatementTest::testExecWithRedundantParameters() to PHP 8
  src/Driver/Mysqli/Statement.php
  tests/Functional/StatementTest.php
Labels: Documentation, Error Handling, PHP, Test Suite, mysqli
