Repository doctrine/dbal, pull requests merged in 2020-08, with the labels that each got.

#4201 Update PHPUnit to 9.3
  ci/github/phpunit.oci8.xml
  ci/github/phpunit.pdo-oci.xml
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Doctrine/Tests/DBAL/Connection/LoggingTest.php
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/OCI8/OCI8StatementTest.php
  tests/Doctrine/Tests/DBAL/Schema/ComparatorTest.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardManagerTest.php
  tests/Doctrine/Tests/DBAL/Sharding/SQLAzure/SQLAzureShardManagerTest.php
  tests/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  tests/travis/ibm_db2.travis.xml
  tests/travis/mariadb.docker.travis.xml
  tests/travis/mariadb.mysqli.docker.travis.xml
  tests/travis/mysql.docker.travis.xml
  tests/travis/mysqli.docker.travis.xml
  tests/travis/pdo_sqlsrv.travis.xml
  tests/travis/pgsql.travis.xml
  tests/travis/sqlite.travis.xml
  tests/travis/sqlsrv.travis.xml
Labels: Blocker, Improvement, Test Suite

#4202 Manually merge 2.11.x into 3.0.x
  ci/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  ci/github/phpunit.oci8.xml
  ci/github/phpunit.pdo-oci.xml
  ci/travis/ibm_db2.travis.xml
  ci/travis/mariadb.docker.travis.xml
  ci/travis/mariadb.mysqli.docker.travis.xml
  ci/travis/mysql.docker.travis.xml
  ci/travis/mysqli.docker.travis.xml
  ci/travis/pdo_sqlsrv.travis.xml
  ci/travis/pgsql.travis.xml
  ci/travis/sqlite.travis.xml
  ci/travis/sqlsrv.travis.xml
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Connection/LoggingTest.php
  tests/ConnectionTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/SchemaTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#4203 Remove --ignore-platform-reqs from PHP 8.0 builds
  .travis.yml
Labels: Blocker, CI, Improvement, PHP

#4204 Remove slash from const name in transactions documentation
  docs/en/reference/transactions.rst
Labels: Documentation

#4207 Update locked composer/package-versions-deprecated for compatibility with PHP 8.0
  composer.lock
Labels: Blocker, PHP

#4208 Manually merge 3.0.x into master
  .travis.yml
  ci/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  ci/github/phpunit.oci8.xml
  ci/github/phpunit.pdo-oci.xml
  ci/travis/ibm_db2.travis.xml
  ci/travis/mariadb.docker.travis.xml
  ci/travis/mariadb.mysqli.docker.travis.xml
  ci/travis/mysql.docker.travis.xml
  ci/travis/mysqli.docker.travis.xml
  ci/travis/pdo_sqlsrv.travis.xml
  ci/travis/pgsql.travis.xml
  ci/travis/sqlite.travis.xml
  ci/travis/sqlsrv.travis.xml
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Connection/LoggingTest.php
  tests/ConnectionTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/SchemaTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
Labels: Merge Up

#4209 Test MySQLi connection via TLS on Travis
  .travis.yml
  tests/Doctrine/Tests/DBAL/Functional/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Doctrine/Tests/TestUtil.php
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/mysqli-tls.docker.travis.xml
Labels: Connections, Improvement, Test Suite, mysqli

#4214 Manually merge 2.10.x into 2.11.x
  .travis.yml
  docs/en/reference/transactions.rst
  tests/Doctrine/Tests/DBAL/Functional/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDOSqlsrv/DriverTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Doctrine/Tests/TestUtil.php
  tests/travis/docker-run-mysql-or-mariadb.sh
  tests/travis/mysqli-tls.docker.travis.xml
Labels: Merge Up

#4213 Deprecate the Synchronizer package
  UPGRADE.md
  docs/en/reference/sharding.rst
  lib/Doctrine/DBAL/Schema/Synchronizer/AbstractSchemaSynchronizer.php
  lib/Doctrine/DBAL/Schema/Synchronizer/SchemaSynchronizer.php
  lib/Doctrine/DBAL/Schema/Synchronizer/SingleDatabaseSynchronizer.php
Labels: Deprecation, Schema

#4215 Remove test group configuration leftovers
  tests/appveyor/mssql.sql2008r2sp2.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2012sp1.sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  tests/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  tests/travis/ibm_db2.travis.xml
  tests/travis/mariadb.docker.travis.xml
  tests/travis/mariadb.mysqli.docker.travis.xml
  tests/travis/mysql.docker.travis.xml
  tests/travis/mysqli-tls.docker.travis.xml
  tests/travis/mysqli.docker.travis.xml
  tests/travis/pdo_sqlsrv.travis.xml
  tests/travis/pgsql.travis.xml
  tests/travis/sqlite.travis.xml
  tests/travis/sqlsrv.travis.xml
Labels: Improvement, Test Suite

#4217 Remove the Synchronizer package
  UPGRADE.md
  src/Schema/Synchronizer/AbstractSchemaSynchronizer.php
  src/Schema/Synchronizer/SchemaSynchronizer.php
  src/Schema/Synchronizer/SingleDatabaseSynchronizer.php
  tests/Schema/Synchronizer/SingleDatabaseSynchronizerTest.php
Labels: BC Break, Schema

#4226 Manually merge 3.0.x into master
  composer.json
  composer.lock
  psalm.xml
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Mysqli/Connection.php
  src/Driver/PDO/Connection.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MySqlPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Portability/Connection.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySqlSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSqlSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: Merge Up

#4229 Deprecate more AbstractPlatform methods
  UPGRADE.md
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/DB2Platform.php
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
Labels: Deprecation, Platforms

#4231 Mark testDropsDatabaseWithActiveConnections() as incomplete on OraclePlatform
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Bug, Oracle, Schema Managers

#4230 Deprecate the functionality of dropping client connections when dropping a database
  UPGRADE.md
  lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
Labels: Deprecation, Schema Managers

#4232 Manually merge 2.10.x into 2.11.x
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#4233 Manually merge 2.11.x into 3.0.x
  UPGRADE.md
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#4235 Update PHPStan to 0.12.40
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Improvement, Static Analysis

#4234 Remove deprecated APIs
  UPGRADE.md
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSqlSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/PostgreSQL94PlatformTest.php
Labels: BC Break, Improvement, Platforms, Schema Managers

#4238 Fix errors with case sensitive collation on mssql: not existing procedures and tables (sp_RENAME, SysObjects, SysColumns)
  .travis.yml
  lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/travis/install-mssql-cs.sh
Labels: Bug, SQL Server, Schema Managers

#4239 Cleanup Travis scripts and configuration
  .travis.yml
  tests/travis/install-mssql-cs.sh
  tests/travis/install-mssql.sh
Labels: CI, Improvement
