Repository doctrine/dbal, pull requests merged in 2021-11, with the labels that each got.

#4942 Do not mark issues as stale
  .github/workflows/stale.yml
Labels: CI

#4943 PHPStan 1.0.2
  composer.json
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/DBALException.php
  lib/Doctrine/DBAL/Driver/Connection.php
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/SQLParserUtils.php
  lib/Doctrine/DBAL/Schema/SQLServerSchemaManager.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/Functional/WriteTest.php
Labels: Static Analysis

#4951 Detect driver in tests based on configured driver name
  tests/Functional/BlobTest.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Functional/Driver/IBMDB2/DriverTest.php
  tests/Functional/Driver/IBMDB2/StatementTest.php
  tests/Functional/Driver/Mysqli/ConnectionTest.php
  tests/Functional/Driver/Mysqli/DriverTest.php
  tests/Functional/Driver/OCI8/ConnectionTest.php
  tests/Functional/Driver/OCI8/DriverTest.php
  tests/Functional/Driver/OCI8/ResultTest.php
  tests/Functional/Driver/OCI8/StatementTest.php
  tests/Functional/Driver/PDO/ConnectionTest.php
  tests/Functional/Driver/PDO/MySQL/DriverTest.php
  tests/Functional/Driver/PDO/OCI/DriverTest.php
  tests/Functional/Driver/PDO/PgSQL/ConnectionTest.php
  tests/Functional/Driver/PDO/PgSQL/DriverTest.php
  tests/Functional/Driver/PDO/SQLSrv/DriverTest.php
  tests/Functional/Driver/PDO/SQLite/DriverTest.php
  tests/Functional/Driver/SQLSrv/DriverTest.php
  tests/Functional/Driver/SQLSrv/StatementTest.php
  tests/Functional/ExceptionTest.php
  tests/Functional/LockMode/NoneTest.php
  tests/Functional/ParameterTypes/AsciiTest.php
  tests/Functional/ResultTest.php
  tests/Functional/SQL/ParserTest.php
  tests/Functional/StatementTest.php
  tests/Functional/TypeConversionTest.php
  tests/Functional/Types/BinaryTest.php
  tests/TestUtil.php
Labels: Test Suite

#4950 Accept driver-level statement as a wrapper-level statement constructor argument
  src/Connection.php
  src/Statement.php
  tests/StatementTest.php
Labels: Improvement, Prepared Statements

#4948 Accept PDO as a Connection constructor argument
  src/Driver/PDO/Connection.php
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLite/Driver.php
Labels: Improvement, Connections, PDO

#4949 Accept connection object/resource as a driver connection constructor argument
  src/Driver/IBMDB2/Connection.php
  src/Driver/IBMDB2/Driver.php
  src/Driver/Mysqli/Connection.php
  src/Driver/Mysqli/Driver.php
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Driver.php
  src/Driver/SQLSrv/Connection.php
  src/Driver/SQLSrv/Driver.php
  tests/Functional/Driver/IBMDB2/ConnectionTest.php
Labels: Improvement, mysqli, oci8, ibm_db2, sqlsrv, Connections

#4952 Merge 2.13.x into 3.1.x
  composer.json
  phpstan.neon.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/Mysqli/Result.php
  src/Schema/SQLServerSchemaManager.php
  tests/Driver/OCI8/ExecutionModeTest.php
  tests/Functional/WriteTest.php
Labels: Merge Up

#4953 Merge 3.1.x into 3.2.x
  .github/workflows/stale.yml
  composer.json
  phpstan.neon.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Platforms/SQLServerPlatform.php
  src/SQL/Parser.php
  src/SQL/Parser/Exception.php
  src/SQL/Parser/Exception/RegularExpressionError.php
  src/Schema/SQLServerSchemaManager.php
  tests/Driver/OCI8/ExecutionModeTest.php
  tests/Functional/Platform/ConcatExpressionTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/WriteTest.php
Labels: Merge Up

#4954 Use willReturn() in mocks instead of will(returnValue())
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractMySQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractOracleDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractPostgreSQLDriverTest.php
  tests/Doctrine/Tests/DBAL/Driver/AbstractSQLiteDriverTest.php
  tests/Doctrine/Tests/DBAL/Portability/StatementTest.php
  tests/Doctrine/Tests/DBAL/Query/Expression/ExpressionBuilderTest.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
  tests/Doctrine/Tests/DBAL/Schema/ComparatorTest.php
  tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Schema/ForeignKeyConstraintTest.php
  tests/Doctrine/Tests/DBAL/Schema/SchemaDiffTest.php
  tests/Doctrine/Tests/DBAL/Schema/TableDiffTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/CreateSchemaSqlCollectorTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Doctrine/Tests/DBAL/Schema/Visitor/SchemaSqlCollectorTest.php
  tests/Doctrine/Tests/DBAL/Sharding/PoolingShardManagerTest.php
  tests/Doctrine/Tests/DBAL/StatementTest.php
  tests/Doctrine/Tests/DBAL/Types/GuidTypeTest.php
Labels: Test Suite

#4958 Rework DBAL630Test
  tests/Functional/FetchBooleanTest.php
  tests/Functional/Ticket/DBAL630Test.php
Labels: Test Suite, PostgreSQL, Prepared Statements

#4947 [Docs] Removing paragraph about PDO similarity
  README.md
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/introduction.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/security.rst
  docs/en/reference/transactions.rst
Labels: Documentation

#4957 Accept the underlying statement as an oci8 statement constructor argument
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Statement.php
Labels: Improvement, oci8

#4960 Merge 2.13.x into 3.1.x
  tests/ConnectionTest.php
  tests/Portability/StatementTest.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Query/QueryBuilderTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/DB2SchemaManagerTest.php
  tests/Schema/ForeignKeyConstraintTest.php
  tests/Schema/SchemaDiffTest.php
  tests/Schema/TableDiffTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
  tests/StatementTest.php
  tests/Types/GuidTypeTest.php
Labels: Merge Up

#4961 Merge 3.1.x into 3.2.x
  README.md
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/introduction.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/security.rst
  docs/en/reference/transactions.rst
  tests/ConnectionTest.php
  tests/Functional/FetchBooleanTest.php
  tests/Functional/Ticket/DBAL630Test.php
  tests/Portability/StatementTest.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Query/QueryBuilderTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/DB2SchemaManagerTest.php
  tests/Schema/ForeignKeyConstraintTest.php
  tests/Schema/SchemaDiffTest.php
  tests/Schema/TableDiffTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
  tests/StatementTest.php
  tests/Types/GuidTypeTest.php
Labels: Merge Up

#4962 Merge 3.2.x into 4.0.x
  README.md
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/introduction.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/security.rst
  docs/en/reference/transactions.rst
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Statement.php
  tests/ConnectionTest.php
  tests/Functional/FetchBooleanTest.php
  tests/Functional/Ticket/DBAL630Test.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Query/QueryBuilderTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/DB2SchemaManagerTest.php
  tests/Schema/ForeignKeyConstraintTest.php
  tests/Schema/SchemaDiffTest.php
  tests/Schema/TableDiffTest.php
  tests/Schema/Visitor/CreateSchemaSqlCollectorTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
  tests/StatementTest.php
  tests/Types/GuidTypeTest.php
  tests/Types/VarDateTimeImmutableTypeTest.php
Labels: Merge Up

#4959 Psalm 4.12.0, PHPStan 1.1.1
  composer.json
Labels: Static Analysis

#4964 Remove redundant PHPUnit mocks
  tests/Connection/LoggingTest.php
  tests/ConnectionTest.php
  tests/Schema/MySQLInheritCharsetTest.php
Labels: Test Suite

#4970 Fix a deprecation in console command return types
  lib/Doctrine/DBAL/Tools/Console/Command/ImportCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/ReservedWordsCommand.php
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
Labels: Tools

#4969 Declare SQLite as not supporting CREATE|DROP DATABASE
  UPGRADE.md
  src/Platforms/SqlitePlatform.php
  src/Schema/SqliteSchemaManager.php
  tests/TestUtil.php
Labels: SQLite, Platforms, Schema Management, Deprecation

#4972 Merge 2.13.x into 3.1.x
  composer.json
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
Labels: Merge Up

#4973 Remove `ReturnTypeWillChange` attribute
  psalm.xml.dist
  src/Query/Expression/CompositeExpression.php
Labels: PHP

#4974 Merge 3.1.x into 3.2.x
  composer.json
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
Labels: Merge Up

#4976 Merge 3.2.x into 4.0.x
  UPGRADE.md
  composer.json
  src/Platforms/SqlitePlatform.php
  src/Schema/SqliteSchemaManager.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
  tests/TestUtil.php
Labels: Merge Up

#4965 Drop support for CREATE|DROP DATABASE in SQLite schema manager
  UPGRADE.md
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: SQLite, Platforms, Schema Management, BC Break

#4979 Remove unwanted colon in code samples
  src/Query/QueryBuilder.php
Labels: Documentation

#4984 Cast LIMIT and OFFSET to int when building limit query
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
Labels: Bug, QueryBuilder

#4978 Use correct column order for composite foreign keys
  src/Platforms/MySQLPlatform.php
  src/Platforms/SQLServer2012Platform.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Bug, MySQL, Schema Introspection

#4986 Add return types to private and final methods
  src/Connection.php
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/IBMDB2/Statement.php
  src/Driver/Mysqli/Connection.php
  src/Driver/Mysqli/Statement.php
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Driver.php
  src/Driver/OCI8/Statement.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLSrv/Statement.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/PDO/Statement.php
  src/Driver/SQLSrv/Connection.php
  src/Driver/SQLSrv/Statement.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/ReservedKeywordsValidator.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Query/QueryBuilder.php
  src/Schema/Comparator.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/Index.php
  src/Schema/OracleSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/Table.php
  src/Schema/Visitor/Graphviz.php
  src/Types/AsciiStringType.php
Labels: Improvement, Strict Typing

#4991 Optimize sharing test connection
  tests/Functional/PortabilityTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Test Suite, Connections

#4992 Merge 3.1.x into 3.2.x
  src/Platforms/AbstractPlatform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Query/QueryBuilder.php
  tests/Functional/PortabilityTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
Labels: Merge Up

#4995 Fix getServerVersion for OCI8 when assertions are disabled
  src/Driver/OCI8/Connection.php
Labels: Bug, oci8

#4996 Merge 3.2.x into 4.0.x
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLite/Driver.php
  src/Platforms/DB2Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Query/QueryBuilder.php
  tests/Functional/PortabilityTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#5003 Always cache the full result
  docs/en/reference/caching.rst
  psalm.xml.dist
  src/Cache/CachingResult.php
  src/Connection.php
  tests/Functional/QueryCacheTest.php
Labels: Bug, Improvement, Cache

#5009 PHPStan 1.2.0, Psalm 4.13.0
  composer.json
  psalm.xml.dist
Labels: Static Analysis, Dependencies

#5008 Refactor query caching tests
  tests/Connection/CachedQueryTest.php
  tests/Functional/QueryCacheTest.php
Labels: Test Suite, Cache

#5011 Merge 2.13.x into 3.1.x
  composer.json
  psalm.xml.dist
Labels: Merge Up

#5012 Merge 3.1.x into 3.2.x
  composer.json
  psalm.xml.dist
  src/Driver/OCI8/Connection.php
Labels: Merge Up

#5013 Merge 3.2.x into 4.0.x
  composer.json
  docs/en/reference/caching.rst
  psalm.xml.dist
  src/Cache/CachingResult.php
  src/Connection.php
  src/Driver/OCI8/Connection.php
  tests/Connection/CachedQueryTest.php
  tests/Functional/ResultCacheTest.php
Labels: Merge Up

#4967 Introduce logging middleware
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  psalm.xml.dist
  src/Logging/Connection.php
  src/Logging/DebugStack.php
  src/Logging/Driver.php
  src/Logging/LoggerChain.php
  src/Logging/Middleware.php
  src/Logging/SQLLogger.php
  src/Logging/Statement.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Functional/PortabilityTest.php
  tests/Logging/MiddlewareTest.php
Labels: Improvement, Logging

#5015 Merge 3.2.x into 4.0.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  psalm.xml.dist
  src/Logging/Connection.php
  src/Logging/DebugStack.php
  src/Logging/Driver.php
  src/Logging/LoggerChain.php
  src/Logging/Middleware.php
  src/Logging/SQLLogger.php
  src/Logging/Statement.php
  tests/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Functional/PortabilityTest.php
  tests/Logging/MiddlewareTest.php
Labels: Merge Up

#5016 Remove SQLLogger interface, its implementations and usage
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Configuration.php
  src/Connection.php
  src/Logging/DebugStack.php
  src/Logging/LoggerChain.php
  src/Logging/NullLogger.php
  src/Logging/SQLLogger.php
  src/Statement.php
  tests/Connection/LoggingTest.php
  tests/ConnectionTest.php
  tests/Logging/DebugStackTest.php
  tests/Logging/LoggerChainTest.php
  tests/StatementTest.php
Labels: Logging, BC Break

#5017 Cast decimals integers to string on SQLite [PHP 8.1]
  lib/Doctrine/DBAL/Types/DecimalType.php
  tests/Doctrine/Tests/DBAL/Functional/Types/DecimalTest.php
Labels: pdo_sqlite, PHP

#4999 Use sprintf('%d') like in DB2, SQLServer and Oracle to harden against wrong limit and offset
  src/Platforms/AbstractPlatform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/SqlitePlatform.php
Labels: Query Limit/Offset Modification

#5019 Discourage the usage of Connection::quote()
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/security.rst
  src/Connection.php
  src/Driver/Connection.php
  src/Query/Expression/ExpressionBuilder.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: SQLite, SQL Server, Documentation, Quoting

#5020 Fix hardcoded varchar default length
  src/Platforms/AbstractPlatform.php
Labels: Platforms

#5021 Remove references to Doctrine 2
  docs/en/reference/known-vendor-issues.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/types.rst
Labels: Documentation

#5022 docs: fix docs for the json type
  docs/en/reference/types.rst
Labels: Documentation

#5023 Merge 2.13.x into 3.1.x
  docs/en/reference/types.rst
  src/Types/DecimalType.php
  tests/Functional/Types/DecimalTest.php
Labels: Merge Up

#5024 Let `json_encode()` and `json_decode()` throw on error
  src/Types/ConversionException.php
  src/Types/JsonType.php
  tests/Types/JsonTest.php
Labels: Improvement

#5028 Merge 3.1.x up into 3.2.x
  docs/en/reference/known-vendor-issues.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/types.rst
  src/Types/DecimalType.php
  tests/Functional/Types/DecimalTest.php
Labels: Merge Up

#5029 Display the metrics of the 3.2 branch
  README.md
Labels: Documentation

#5031 Merge 2.13.x into 3.2.x
  README.md
Labels: Merge Up

#5033 Merge 3.3.x into 4.0.x
  .doctrine-project.json
  README.md
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/known-vendor-issues.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/security.rst
  docs/en/reference/types.rst
  src/Connection.php
  src/Driver/Connection.php
  src/Platforms/MySQLPlatform.php
  src/Query/Expression/ExpressionBuilder.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Types/DecimalType.php
  src/Types/JsonType.php
  tests/Functional/Types/DecimalTest.php
  tests/Types/JsonTest.php
Labels: Merge Up

#5035 Provide abstract middleware classes
  src/Driver/Middleware/AbstractConnectionMiddleware.php
  src/Driver/Middleware/AbstractDriverMiddleware.php
  src/Driver/Middleware/AbstractResultMiddleware.php
  src/Driver/Middleware/AbstractStatementMiddleware.php
  src/Logging/Connection.php
  src/Logging/Driver.php
  src/Logging/Statement.php
  src/Portability/Connection.php
  src/Portability/Driver.php
  src/Portability/Result.php
  src/Portability/Statement.php
  tests/Driver/Middleware/AbstractConnectionMiddlewareTest.php
  tests/Driver/Middleware/AbstractDriverMiddlewareTest.php
  tests/Driver/Middleware/AbstractResultMiddlewareTest.php
  tests/Driver/Middleware/AbstractStatementMiddlewareTest.php
Labels: Improvement

#5037 Add `Connection::getNativeConnection()`
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Middleware/AbstractConnectionMiddleware.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Portability/Driver.php
  tests/Driver/Middleware/AbstractConnectionMiddlewareTest.php
  tests/Driver/PDO/PgSQL/DriverTest.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/AbstractDriverTest.php
  tests/Functional/Driver/PDO/SQLSrv/DriverTest.php
  tests/Portability/ConnectionTest.php
Labels: New Feature, Connections, Deprecation

#4966 Deprecate Connection::getWrappedConnection(), mark Connection::connect() internal
  UPGRADE.md
  psalm.xml.dist
  src/Connection.php
Labels: Connections, Deprecation

#5039 Merge 3.3.x into 4.0.x
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Middleware/AbstractConnectionMiddleware.php
  src/Driver/Middleware/AbstractDriverMiddleware.php
  src/Driver/Middleware/AbstractResultMiddleware.php
  src/Driver/Middleware/AbstractStatementMiddleware.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Logging/Connection.php
  src/Logging/Driver.php
  src/Logging/Statement.php
  src/Portability/Connection.php
  src/Portability/Driver.php
  src/Portability/Result.php
  src/Portability/Statement.php
  tests/Driver/Middleware/AbstractConnectionMiddlewareTest.php
  tests/Driver/Middleware/AbstractDriverMiddlewareTest.php
  tests/Driver/Middleware/AbstractResultMiddlewareTest.php
  tests/Driver/Middleware/AbstractStatementMiddlewareTest.php
  tests/Driver/PDO/PgSQL/DriverTest.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/AbstractDriverTest.php
  tests/Functional/Driver/PDO/SQLSrv/DriverTest.php
  tests/Portability/ConnectionTest.php
Labels: Merge Up

#5042 Add missing `unix_socket` option to the array shape for the connection params
  lib/Doctrine/DBAL/DriverManager.php
Labels: Static Analysis

#5038 Use abstract middleware classes for PDO_sqlsrv
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/PDO/SQLSrv/Statement.php
Labels: Improvement, pdo_sqlsrv

#5040 Fix coding standard violation in the IBM DB2 driver
  src/Driver/IBMDB2/Driver.php
Labels: Code Style

#5041 Remove Connection::getWrappedConnection(), make Connection::connect() protected
  UPGRADE.md
  psalm.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  tests/ConnectionTest.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Driver/IBMDB2/StatementTest.php
  tests/Functional/Driver/SQLSrv/StatementTest.php
  tests/Functional/ExceptionTest.php
Labels: Connections, BC Break

#5045 Fix return type of `_getNestedTransactionSavePointName()`
  src/Connection.php
Labels: Static Analysis

#5044 Remove getWrappedConnection() and add getNativeConnection() to the interface
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/Middleware/AbstractConnectionMiddleware.php
  src/Driver/Mysqli/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Portability/Driver.php
  tests/Driver/Middleware/AbstractConnectionMiddlewareTest.php
  tests/Portability/ConnectionTest.php
Labels: Connections, BC Break

#5050 Remove exception coverter unit tests
  tests/Driver/API/ExceptionConverterTest.php
  tests/Driver/API/MySQL/ExceptionConverterTest.php
  tests/Driver/API/OCI/ExceptionConverterTest.php
  tests/Driver/API/PostgreSQL/ExceptionConverterTest.php
  tests/Driver/API/SQLite/ExceptionConverterTest.php
Labels: Test Suite, Error Handling

#5053 Workaround for "mixed is a reserved word" error
  psalm.xml.dist
Labels: Static Analysis

#5052 Fix doc block
  src/Driver/SQLSrv/Statement.php
Labels: Static Analysis

#5055 Merge 3.2.x into 3.3.x
  psalm.xml.dist
  src/Connection.php
  src/Driver/IBMDB2/Driver.php
  src/Driver/SQLSrv/Statement.php
  tests/Driver/API/ExceptionConverterTest.php
  tests/Driver/API/MySQL/ExceptionConverterTest.php
  tests/Driver/API/OCI/ExceptionConverterTest.php
  tests/Driver/API/PostgreSQL/ExceptionConverterTest.php
  tests/Driver/API/SQLite/ExceptionConverterTest.php
Labels: Merge Up

#5057 Explain what DC2Type SQL comments are about
  docs/en/explanation/dc2type-comments.rst
  docs/en/sidebar.rst
Labels: Documentation
