Repository doctrine/dbal, pull requests merged in 2021-07, with the labels that each got.

#4697 Configure PHP version for PHP_CodeSniffer
  .github/workflows/coding-standards.yml
  phpcs.xml.dist
Labels: Code Style

#4699 Update Psalm to 4.8.1
  composer.json
  lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  lib/Doctrine/DBAL/Platforms/DB2Platform.php
  lib/Doctrine/DBAL/Platforms/OraclePlatform.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  tests/Doctrine/Tests/DBAL/Functional/Connection/BackwardCompatibility/Connection.php
Labels: Bug, Static Analysis

#4701 Merge 3.1.x into 3.2.x
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Platforms/PostgreSQL94Platform.php
  tests/Platforms/PostgreSQL94PlatformTest.php
Labels: Merge Up

#4703 Temporarily remove PHP 8.1 jobs from CI
  .github/workflows/continuous-integration.yml
Labels: CI, PHP

#4698 Add alterSchema() methods in AbstractSchemaManager
  src/Schema/AbstractSchemaManager.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Improvement, Schema Managers

#4710 Update .gitattributes
  .gitattributes
Labels: Packaging

#4707 Introduce consistent Comparator API
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/Schema.php
  src/Schema/SchemaDiff.php
Labels: Deprecation, Improvement, Schema Comparison

#4714 Merge 3.1.x into 3.2.x
  .github/workflows/coding-standards.yml
  composer.json
  phpcs.xml.dist
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Portability/Converter.php
Labels: Merge Up

#4716 Clarify ExpressionBuilder arguments
  src/Query/Expression/ExpressionBuilder.php
Labels: Bug, Documentation

#4715 Merge 3.2.x into 4.0.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  UPGRADE.md
  composer.json
  phpcs.xml.dist
  phpstan.neon.dist
  psalm.xml.dist
  src/Driver/OCI8/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Portability/Converter.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/Schema.php
  src/Schema/SchemaDiff.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/PostgreSQL94PlatformTest.php
Labels: Merge Up

#4717 PHPStan check fails on PHP 8
  .github/workflows/static-analysis.yml
  phpstan.neon.dist
  src/Driver/Mysqli/Result.php
Labels: Static Analysis

#4719 Reset transaction nesting level when closing connection
  src/Connection.php
  tests/Functional/ConnectionTest.php
Labels: Bug, Connections, Transactions

#4720 Merge 3.1.x into 3.2.x
  .github/workflows/static-analysis.yml
  phpstan.neon.dist
  src/Connection.php
  src/Driver/Mysqli/Result.php
  src/Query/Expression/ExpressionBuilder.php
  tests/Functional/ConnectionTest.php
Labels: Merge Up

#4721 Merge 3.2.x into 4.0.x
  .github/workflows/static-analysis.yml
  phpstan.neon.dist
  src/Connection.php
  src/Driver/Mysqli/Result.php
  src/Query/Expression/ExpressionBuilder.php
  tests/Functional/ConnectionTest.php
Labels: Merge Up

#4722 Remove deprecated Comparator::compare()
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Schema/Comparator.php
  tests/Functional/Platform/NewPrimaryKeyWithNewAutoIncrementColumnTest.php
  tests/Schema/ComparatorTest.php
Labels: BC Break, Improvement, Schema Comparison

#4713 Handle lost connection during commit
  src/Connection.php
  src/Driver/PDO/Connection.php
  tests/Functional/TransactionTest.php
Labels: Connections, Error Handling, Improvement, Transactions

#4723 Declare abstract methods in AbstractPlatform as abstract
  UPGRADE.md
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
Labels: BC Break, Improvement, Platforms

#4724 Deprecate redundant AbstractPlatform methods
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Types/GuidType.php
Labels: Deprecation, Platforms, Types

#4726 Revert GUID type deprecation
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Types/GuidType.php
  tests/Functional/Types/GuidTest.php
Labels: Platforms, Types

#4727 Merge 3.2.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/SQLServer2012Platform.php
  tests/Functional/Types/GuidTest.php
Labels: Merge Up

#4728 Remove redundant platform methods
  UPGRADE.md
  psalm.xml.dist
  src/Connection.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/SQLServer2012Platform.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: BC Break, Platforms

#4729 Test exception handling in wrapper Result
  src/Connection.php
  src/Result.php
  tests/Functional/ResultTest.php
Labels: Connections, Error Handling, Prepared Statements, Test Suite

#4730 Merge 3.2.x into 4.0.x
  src/Connection.php
  src/Result.php
  tests/Functional/ResultTest.php
Labels: Merge Up

#4731 Fix tests in random order
  tests/Functional/Connection/FetchEmptyTest.php
  tests/Functional/DataAccessTest.php
  tests/Functional/Platform/BitwiseExpressionTest.php
  tests/Functional/TableGeneratorTest.php
Labels: Connections, Platforms, Test Suite

#4733 Fix auto_increment implementation for Oracle
  src/Platforms/OraclePlatform.php
  tests/Functional/AutoIncrementColumnTest.php
  tests/Platforms/OraclePlatformTest.php
Labels: Bug, Oracle, Sequences
