Repository doctrine/dbal, pull requests merged in 2021-06, with the labels that each got.

#4663 Bump doctrine/coding-standard
  composer.json
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
  lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php
  lib/Doctrine/DBAL/DriverManager.php
  lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
  phpcs.xml.dist
  tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php
  tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/PrimaryReadReplicaConnectionTest.php
  tests/Doctrine/Tests/DBAL/Schema/MySqlInheritCharsetTest.php
Labels: Code Style

#4665 Merge 3.2.x into 4.0.x
  .doctrine-project.json
  README.md
  UPGRADE.md
  composer.json
  docs/en/reference/caching.rst
  docs/en/reference/configuration.rst
  docs/en/reference/events.rst
  phpstan.neon.dist
  psalm.xml.dist
  src/Cache/CachingResult.php
  src/Cache/QueryCacheProfile.php
  src/Configuration.php
  src/Connection.php
  src/Event/TransactionBeginEventArgs.php
  src/Event/TransactionCommitEventArgs.php
  src/Event/TransactionEventArgs.php
  src/Event/TransactionRollBackEventArgs.php
  src/Events.php
  tests/ConnectionTest.php
  tests/Functional/ResultCacheTest.php
Labels: Merge Up

#4644 Remove defaults for MySQL table charset, collation and engine
  UPGRADE.md
  src/Platforms/MySQLPlatform.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Schema/MySQLInheritCharsetTest.php
Labels: BC Break, Improvement, MySQL, Platforms

#4667 Make Table::removeUniqueConstraint() actually work
  src/Schema/Table.php
  tests/Schema/TableTest.php
Labels: Bug

#4626 Remove support for Doctrine Cache
  UPGRADE.md
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Cache/QueryCacheProfile.php
  src/Configuration.php
  tests/Functional/ResultCacheTest.php
Labels: BC Break, Cache

#4672 Fixed generated SQL for UniqueConstraint objects
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Bug, Indexes, Platforms

#4673 Document a non-deprecated way to interact with prepared statements
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/security.rst
Labels: Documentation

#4679 Update PHPUnit to 9.5.5
  composer.json
Labels: Test Suite

#4680 Disable DebugStack logger in the test suite
  tests/FunctionalTestCase.php
Labels: Test Suite

#4681 Deprecate TableGenerator
  psalm.xml.dist
  src/Id/TableGenerator.php
  src/Id/TableGeneratorSchemaVisitor.php
Labels: Deprecation, Sequences

#4684 Merge 3.1.x into 3.2.x
  composer.json
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/security.rst
  src/Platforms/AbstractPlatform.php
  tests/FunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Merge Up

#4683 Merge 2.13.x into 3.1.x
  composer.json
Labels: Merge Up

#4682 Initial support for PHP 8.1
  .github/workflows/continuous-integration.yml
  src/Platforms/PostgreSQL94Platform.php
  src/Schema/AbstractAsset.php
  src/Schema/SqliteSchemaManager.php
  src/Statement.php
  tests/Functional/BlobTest.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Functional/TypeConversionTest.php
  tests/Tools/DumperTest.php
  tests/Types/VarDateTimeTest.php
Labels: PHP, Tools, pdo_sqlite

#4685 Support for more drivers on PHP 8.1
  .github/workflows/continuous-integration.yml
  src/Driver/Mysqli/Connection.php
  src/Schema/OracleSchemaManager.php
Labels: Improvement, PHP, mysqli, oci8, pdo_mysql, pdo_oci, pdo_pgsql

#4688 [GH-4687] Deprecate Connection::lastInsertId($name)
  UPGRADE.md
  src/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Portability/Connection.php
Labels: Connections, Deprecation, PDO, Sequences

#4690 Merge 3.2.x into 4.0.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/security.rst
  psalm.xml.dist
  src/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Id/TableGenerator.php
  src/Id/TableGeneratorSchemaVisitor.php
  src/Platforms/AbstractPlatform.php
  src/Portability/Connection.php
  src/Schema/OracleSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Statement.php
  tests/Functional/BlobTest.php
  tests/Functional/TypeConversionTest.php
  tests/FunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Tools/DumperTest.php
  tests/Types/VarDateTimeTest.php
Labels: Merge Up

#4662 Add ReturnTypeWillChange to PDO implementations
  lib/Doctrine/DBAL/Driver/PDOConnection.php
  lib/Doctrine/DBAL/Driver/PDOQueryImplementation.php
  lib/Doctrine/DBAL/Driver/PDOStatement.php
  lib/Doctrine/DBAL/Driver/PDOStatementImplementations.php
Labels: Bug, PDO

#4691 [GH-4687] Remove support for Connection::lastInsertId($name)
  UPGRADE.md
  src/Connection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Portability/Connection.php
  tests/Functional/Driver/OCI8/ConnectionTest.php
  tests/Functional/Ticket/DBAL630Test.php
  tests/Functional/WriteTest.php
Labels: BC Break, Connections, PDO, Sequences

#4692 [GH-4681] Remove TableGenerator
  UPGRADE.md
  psalm.xml.dist
  src/Id/TableGenerator.php
  src/Id/TableGeneratorSchemaVisitor.php
  tests/Functional/TableGeneratorTest.php
Labels: BC Break, Sequences

#4621 Move fix for user provided pdo connection
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/DriverManager.php
  phpstan.neon.dist
  tests/Doctrine/Tests/DBAL/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
Labels: BC Fix, Configuration, Connections, PDO

#4695 Ignore errors about missing ReturnTypeWillChange class
  phpstan.neon.dist
  psalm.xml.dist
Labels: Static Analysis

#4694 Update JetBrains PhpStorm stubs to 2021.1
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
Labels: PHP, SQL Server, Static Analysis

#4696 Merge 2.13.x into 3.1.x
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
Labels: Merge Up

#4677 Create tables with unique constraints on PostgreSQL
  src/Platforms/PostgreSQL94Platform.php
  tests/Platforms/PostgreSQL94PlatformTest.php
Labels: Bug, PostgreSQL, Schema
