Repository doctrine/dbal, pull requests merged in 2021-12, with the labels that each got.

#5056 Merge 3.3.x into 4.0.x
  psalm.xml.dist
  src/Connection.php
  src/Driver/IBMDB2/Driver.php
  src/Driver/PDO/SQLSrv/Connection.php
  src/Driver/PDO/SQLSrv/Statement.php
  src/Driver/SQLSrv/Statement.php
  tests/Driver/API/ExceptionConverterTest.php
  tests/Driver/API/MySQL/ExceptionConverterTest.php
  tests/Driver/API/OCI/ExceptionConverterTest.php
  tests/Driver/API/PostgreSQL/ExceptionConverterTest.php
  tests/Driver/API/SQLite/ExceptionConverterTest.php
Labels: Merge Up

#5062 Remove psr/log downgrade from CI
  .github/workflows/continuous-integration.yml
Labels: CI, Logging

#5063 Fix array types on ArrayResult
  src/Cache/ArrayResult.php
Labels: Static Analysis

#5060 Deprecate support for Postgres 9
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/Keywords/PostgreSQL100Keywords.php
  src/Platforms/PostgreSQL100Platform.php
Labels: PostgreSQL, Deprecation

#5061 Add deprecation annotation to `SQLServer2012Platform`
  src/Platforms/SQLServer2012Platform.php
Labels: SQL Server, Deprecation

#5058 Deprecate AbstractPlatform commented type APIs
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Types/BooleanType.php
Labels: Deprecation

#5059 Document minor BC Break about cache keys
  UPGRADE.md
Labels: Documentation

#5064 Use see instead of link for references to structural elements
  src/Connection.php
  src/Driver/API/ExceptionConverter.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractException.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
  src/Driver/Connection.php
  src/Driver/ServerInfoAwareConnection.php
  src/Driver/Statement.php
  src/DriverManager.php
  src/Event/SchemaAlterTableAddColumnEventArgs.php
  src/Event/SchemaAlterTableChangeColumnEventArgs.php
  src/Event/SchemaAlterTableEventArgs.php
  src/Event/SchemaAlterTableRemoveColumnEventArgs.php
  src/Event/SchemaAlterTableRenameColumnEventArgs.php
  src/Event/SchemaColumnDefinitionEventArgs.php
  src/Event/SchemaCreateTableColumnEventArgs.php
  src/Event/SchemaCreateTableEventArgs.php
  src/Event/SchemaDropTableEventArgs.php
  src/Event/SchemaIndexDefinitionEventArgs.php
  src/Logging/SQLLogger.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/PostgreSQL94Keywords.php
  src/Platforms/Keywords/SQLServer2012Keywords.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Portability/Converter.php
  src/Query/Expression/ExpressionBuilder.php
  src/Query/QueryBuilder.php
  src/Result.php
  src/Schema/AbstractAsset.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/Constraint.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SqliteSchemaManager.php
  src/Statement.php
  src/Types/Type.php
Labels: Documentation

#5068 Merge 3.2.x into 3.3.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  docs/en/explanation/dc2type-comments.rst
  docs/en/sidebar.rst
  src/Cache/ArrayResult.php
  src/Connection.php
  src/Driver/API/ExceptionConverter.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractException.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
  src/Driver/Connection.php
  src/Driver/ServerInfoAwareConnection.php
  src/Driver/Statement.php
  src/DriverManager.php
  src/Event/SchemaAlterTableAddColumnEventArgs.php
  src/Event/SchemaAlterTableChangeColumnEventArgs.php
  src/Event/SchemaAlterTableEventArgs.php
  src/Event/SchemaAlterTableRemoveColumnEventArgs.php
  src/Event/SchemaAlterTableRenameColumnEventArgs.php
  src/Event/SchemaColumnDefinitionEventArgs.php
  src/Event/SchemaCreateTableColumnEventArgs.php
  src/Event/SchemaCreateTableEventArgs.php
  src/Event/SchemaDropTableEventArgs.php
  src/Event/SchemaIndexDefinitionEventArgs.php
  src/Logging/SQLLogger.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/PostgreSQL94Keywords.php
  src/Platforms/Keywords/SQLServer2012Keywords.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Portability/Converter.php
  src/Query/Expression/ExpressionBuilder.php
  src/Query/QueryBuilder.php
  src/Result.php
  src/Schema/AbstractAsset.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/Constraint.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SqliteSchemaManager.php
  src/Statement.php
  src/Types/Type.php
Labels: Merge Up

#5067 Remove Platform API about commented types
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
Labels: BC Break

#5072 Deprecate support for MySQL 5.6 and older
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/Keywords/MySQL57Keywords.php
  src/Platforms/MySQL57Platform.php
Labels: MySQL, Platforms, Deprecation

#5069 Drop support for Postgres 9
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/Keywords/PostgreSQL100Keywords.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  tests/Driver/AbstractPostgreSQLDriverTest.php
  tests/Platforms/PostgreSQL100PlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: PostgreSQL, Platforms, BC Break

#5074 Add return types to Command::execute() overrides
  src/Tools/Console/Command/ReservedWordsCommand.php
  src/Tools/Console/Command/RunSqlCommand.php
Labels: BC Break

#5071 Clean up SQL generation in MySQL platform
  src/Platforms/MySQLPlatform.php
Labels: MySQL

#5077 Honor requiresSQLCommentHint() for overriding types
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Bug

#5070 RunSqlCommand: Render results as table
  UPGRADE.md
  composer.json
  phpcs.xml.dist
  phpstan.neon.dist
  psalm.xml.dist
  src/Tools/Console/Command/RunSqlCommand.php
  src/Tools/Dumper.php
  tests/Tools/Console/Fixtures/select-1.txt
  tests/Tools/Console/RunSqlCommandTest.php
  tests/Tools/DumperTest.php
Labels: Improvement, Deprecation

#5079 Fix typos
  src/Result.php
Labels: Bug

#5080 Modernize `strpos()` calls
  src/Driver/API/PostgreSQL/ExceptionConverter.php
  src/Driver/API/SQLite/ExceptionConverter.php
  src/Driver/IBMDB2/DataSourceName.php
  src/DriverManager.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/AbstractAsset.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SqliteSchemaManager.php
  tests/TestUtil.php
Labels: Improvement, PHP

#5081 Typo fix : "enviroment" ➤ "environment"
  docs/en/reference/events.rst
Labels: Documentation

#5078 Remove package-versions-deprecated dependency
  composer.json
  src/Tools/Console/ConsoleRunner.php
Labels: Dependencies

#5083 Deprecate Graphviz visitor
  UPGRADE.md
  src/Schema/Visitor/Graphviz.php
Labels: Tools, Deprecation

#5087 Merge 3.3.x into 4.0.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  docs/en/explanation/dc2type-comments.rst
  docs/en/sidebar.rst
  phpcs.xml.dist
  phpstan.neon.dist
  psalm.xml.dist
  src/Cache/ArrayResult.php
  src/Connection.php
  src/Driver/API/ExceptionConverter.php
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractException.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
  src/Driver/Connection.php
  src/Driver/Statement.php
  src/DriverManager.php
  src/Event/SchemaAlterTableAddColumnEventArgs.php
  src/Event/SchemaAlterTableChangeColumnEventArgs.php
  src/Event/SchemaAlterTableEventArgs.php
  src/Event/SchemaAlterTableRemoveColumnEventArgs.php
  src/Event/SchemaAlterTableRenameColumnEventArgs.php
  src/Event/SchemaColumnDefinitionEventArgs.php
  src/Event/SchemaCreateTableColumnEventArgs.php
  src/Event/SchemaCreateTableEventArgs.php
  src/Event/SchemaDropTableEventArgs.php
  src/Event/SchemaIndexDefinitionEventArgs.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/Keywords/MySQL57Keywords.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Portability/Converter.php
  src/Query/Expression/ExpressionBuilder.php
  src/Query/QueryBuilder.php
  src/Result.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/Visitor/Graphviz.php
  src/Statement.php
  src/Tools/Console/Command/RunSqlCommand.php
  src/Tools/Console/ConsoleRunner.php
  src/Tools/Dumper.php
  src/Types/Type.php
  tests/Cache/ArrayStatementTest.php
  tests/Tools/Console/Fixtures/select-1.txt
  tests/Tools/Console/RunSqlCommandTest.php
  tests/Tools/DumperTest.php
Labels: Merge Up

#5088 Remove suppression of the deprecated class error needed for Composer 1
  psalm.xml.dist
Labels: Static Analysis, Dependencies

#5090 Update Psalm to 4.14.0
  composer.json
  lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
Labels: Static Analysis, Dependencies

#5084 Deprecate the `doctrine-dbal` binary
  UPGRADE.md
  bin/doctrine-dbal.php
  docs/en/reference/cli-tools.rst
  src/Tools/Console/ConsoleRunner.php
Labels: Tools, Deprecation

#5085 Use gvenzl/oracle-xe service
  .github/workflows/continuous-integration.yml
Labels: Improvement, CI, Oracle

#5094 Add healthcheck default options for Oracle test runs
  .github/workflows/continuous-integration.yml
Labels: CI, Oracle

#5092 Merge 2.13.x into 3.2.x
  .github/workflows/continuous-integration.yml
  composer.json
  docs/en/reference/events.rst
  src/DriverManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: Merge Up

#5095 Merge 3.2.x into 3.3.x
  .github/workflows/continuous-integration.yml
  composer.json
  docs/en/reference/events.rst
  src/DriverManager.php
  src/Platforms/AbstractPlatform.php
  src/Result.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Merge Up

#5096 Merge 3.3.x into 4.0.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  bin/doctrine-dbal.php
  composer.json
  docs/en/reference/cli-tools.rst
  docs/en/reference/events.rst
  psalm.xml.dist
  src/DriverManager.php
  src/Result.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Tools/Console/ConsoleRunner.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Merge Up

#5097 Deprecate support for MariaDB 10.1 and older
  UPGRADE.md
Labels: MariaDB, Platforms, Deprecation

#5098 Forward compatibility for MySQL-like platforms
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MariaDb102Keywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL/Comparator.php
  src/Platforms/MySQLPlatform.php
  src/Schema/MySQLSchemaManager.php
  tests/Functional/Connection/ConnectionLostTest.php
  tests/Functional/Platform/DefaultExpressionTest.php
  tests/Functional/Platform/NewPrimaryKeyWithNewAutoIncrementColumnTest.php
  tests/Functional/PrimaryReadReplicaConnectionTest.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/TransactionTest.php
  tests/Schema/MySQLSchemaManagerTest.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
Labels: MySQL, MariaDB, Platforms

#5101 Merge 3.3.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MariaDb102Keywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL/Comparator.php
  src/Platforms/MySQLPlatform.php
  src/Schema/MySQLSchemaManager.php
  tests/Functional/Connection/ConnectionLostTest.php
  tests/Functional/Platform/DefaultExpressionTest.php
  tests/Functional/Platform/NewPrimaryKeyWithNewAutoIncrementColumnTest.php
  tests/Functional/PrimaryReadReplicaConnectionTest.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/TransactionTest.php
  tests/Schema/MySQLSchemaManagerTest.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
Labels: Merge Up

#5099 Remove Graphviz visitor
  UPGRADE.md
  src/Schema/Visitor/Graphviz.php
Labels: Tools, BC Break

#5102 Deprecate support for MariaDB 10.2.6 and older
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MariaDb102Keywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MariaDb1027Platform.php
Labels: MariaDB, Platforms, Deprecation

#5104 Merge 3.3.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MariaDb102Keywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MariaDb1027Platform.php
Labels: Merge Up

#5106 Mark AbstractSchemaManager::extractDoctrineTypeFromComment() and ::removeDoctrineTypeFromComment() internal
  src/Schema/AbstractSchemaManager.php
Labels: Schema Management, Documentation, Type Mapping

#5108 Do not use quotes to represent a boolean default
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Improvement, Default Values

#5089 Drop support for MySQL 5.6 and older and MariaDB 10.2.6 and older
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  docs/en/reference/platforms.rst
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/Keywords/MariaDb102Keywords.php
  src/Platforms/Keywords/MySQL57Keywords.php
  src/Platforms/Keywords/MySQL80Keywords.php
  src/Platforms/Keywords/MySQLKeywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Schema/MySQLSchemaManager.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  tests/Driver/AbstractMySQLDriverTest.php
  tests/Functional/Platform/ColumnTest/MySQL.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/MariaDBPlatformTest.php
  tests/Platforms/MySQL57PlatformTest.php
  tests/Platforms/MySQLPlatformTest.php
Labels: MySQL, Platforms, BC Break

#5109 Deprecate support for Oracle 12c and older
  UPGRADE.md
Labels: Oracle, Deprecation

#5110 PHPCS 3.6.2, Psalm 4.15.0
  composer.json
Labels: Dependencies

#5112 Merge 3.2.x into 3.3.x
  composer.json
Labels: Merge Up

#5111 Merge 2.13.x into 3.2.x
  composer.json
Labels: Merge Up

#5113 Merge 3.3.x into 4.0.x
  UPGRADE.md
  composer.json
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Merge Up

#5114 Drop support for Oracle 12c and older
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  docs/en/reference/platforms.rst
Labels: Oracle, Platforms, BC Break

#5119 Deprecate AbstractPlatform::prefersIdentityColumns()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  tests/Functional/WriteTest.php
Labels: Platforms, Sequences, Deprecation

#5118 Fix return docblock
  lib/Doctrine/DBAL/Query/QueryBuilder.php
Labels: Static Analysis

#5121 Remove DB2Platform::supportsReleaseSavepoints()
  src/Platforms/DB2Platform.php
Labels: IBM DB2, Transactions

#5122 Merge 3.3.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
Labels: Merge Up

#5123 Remove AbstractPlatform::prefersIdentityColumns()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Platforms, BC Break, Sequences

#5127 Test AbstractPlatform::getModExpression()
  tests/Functional/Platform/ModExpressionTest.php
Labels: Test Suite, Platforms

#5128 Merge 3.3.x into 4.0.x
  src/Platforms/AbstractPlatform.php
  tests/Functional/Platform/ModExpressionTest.php
Labels: Platforms, Merge Up

#5129 Accept strings in AbstractPlatform::get*Expression() methods
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
Labels: Bug, Documentation

#5131 Remove redundant @throws tags from AbstractPlatform
  src/Platforms/AbstractPlatform.php
Labels: Documentation, Static Analysis

#5136 Deprecate Type::canRequireSQLConversion()
  UPGRADE.md
  psalm.xml.dist
  src/Types/Type.php
Labels: Types, Deprecation

#5124 Improve performance of Oracle constraint query.
  src/Platforms/OraclePlatform.php
Labels: Improvement, Oracle, Schema Introspection

#4919 run workflow only if modified file matches the configured paths
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
Labels: CI

#5139 Specify allowed plugins for Composer 2.2
  composer.json
Labels: Dependencies

#5140 Merge 2.13.x into 3.2.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: Merge Up

#5141 Merge 3.2.x into 3.3.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
Labels: Merge Up

#5142 Merge 3.3.x into 4.0.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  UPGRADE.md
  composer.json
  psalm.xml.dist
  src/Platforms/OraclePlatform.php
  src/Types/Type.php
Labels: Merge Up

#5138 Make the SQL parser regular expression less greedy
  src/SQL/Parser.php
Labels: Bug, SQL Parser

#5143 Remove Type::canRequireSQLConversion()
  UPGRADE.md
  psalm.xml.dist
  src/Types/Type.php
  tests/Types/StringTest.php
Labels: Types, BC Break

#5145 Use $maxLength = 0 by default when calling PDOStatement::bindParam()
  src/Driver/PDO/Statement.php
  tests/Functional/StatementTest.php
Labels: Bug, PHP, PDO

#5148 Bump PHPStan, Psalm & PHPUnit
  composer.json
  phpstan.neon.dist
Labels: Static Analysis, Dependencies

#4817 Use original case to index renamed columns
  src/Schema/Comparator.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Schema/ComparatorTest.php
Labels: Bug, SQL Server, Schema Comparison

#5150 Use native Oracle 12c syntax for Top-N queries
  src/Platforms/OraclePlatform.php
  tests/Platforms/OraclePlatformTest.php
Labels: Improvement, Oracle, Query Limit/Offset Modification

#5153 Merge 3.2.x into 3.3.x
  composer.json
  phpstan.neon.dist
  src/Driver/PDO/Statement.php
  src/SQL/Parser.php
  tests/Functional/StatementTest.php
Labels: Merge Up

#5152 Deprecate support for IBM DB2 10.5 and older
  UPGRADE.md
  docs/en/reference/platforms.rst
Labels: IBM DB2, Deprecation

#5154 Merge 3.3.x into 4.0.x
  UPGRADE.md
  composer.json
  docs/en/reference/platforms.rst
  phpstan.neon.dist
  src/SQL/Parser.php
  src/Schema/Comparator.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/StatementTest.php
  tests/Schema/ComparatorTest.php
Labels: Merge Up
