Repository doctrine/dbal, pull requests merged in 2021-04, with the labels that each got.

#4573 Upmerge 2.12 in 2.13
  lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php
Labels: Merge Up

#4568 Trigger runtime deprecations for previously deprecated APIs
  src/Connection.php
  src/Driver/PDO/SQLSrv/Statement.php
  src/Driver/PDO/Statement.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
Labels: Deprecation

#4576 Merge 3.1.x into 4.0.x
  .github/workflows/static-analysis.yml
  UPGRADE.md
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
  src/Query/QueryBuilder.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Tools/Console/Command/RunSqlCommand.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#4577 Remove deprecated schema- and namespace-related APIs
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: BC Break, PostgreSQL, Schema Managers

#4584 [GH-4503] Mark OracleSchemaManager methods internal
  UPGRADE.md
  src/Schema/OracleSchemaManager.php
Labels: Deprecation, Oracle, Schema Managers

#4583 [GH-4510] Remove AbstractPlatform::getReservedKeywordsClass()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQL94Platform.php
  src/Platforms/SQLServer2012Platform.php
  src/Platforms/SqlitePlatform.php
Labels: BC Break, Platforms, Reserved Keywords

#4579 Add missing runtime deprecations related to FC Result API (#4529, #4571)
  UPGRADE.md
  lib/Doctrine/DBAL/ForwardCompatibility/Result.php
Labels: Deprecation, Prepared Statements

#4587 [GH-4510] Deprecate ReservedWordsCommand::setKeywordListClass()
  UPGRADE.md
  src/Tools/Console/Command/ReservedWordsCommand.php
Labels: Deprecation, Documentation, Reserved Keywords

#4578 Predictable `QueryBuilder::executeQuery()` and `QueryBuilder::executeStatement()`
  UPGRADE.md
  src/Query/QueryBuilder.php
  tests/Query/QueryBuilderTest.php
Labels: Deprecation, Improvement, QueryBuilder

#4589 Reference methods using parentheses
  src/Query/QueryBuilder.php
  src/Schema/AbstractSchemaManager.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Deprecation, Documentation

#4590 Fix user provided pdo connection
  lib/Doctrine/DBAL/DriverManager.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
Labels: BC Fix, Connections, PDO

#4593 Add direct dependency on PHP_CodeSniffer
  composer.json
  phpcs.xml.dist
Labels: Code Style

#4594 Merge 2.13.x into 3.0.x
  UPGRADE.md
  composer.json
  phpcs.xml.dist
Labels: Merge Up

#4595 Merge 3.0.x into 3.1.x
  UPGRADE.md
  composer.json
  phpcs.xml.dist
Labels: Merge Up

#4592 Merge 3.1.x into 4.0.x
  UPGRADE.md
  composer.json
  phpcs.xml.dist
  src/Query/QueryBuilder.php
  src/Schema/OracleSchemaManager.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  tests/Platforms/SqlitePlatformTest.php
  tests/Query/QueryBuilderTest.php
Labels: Merge Up

#4581 Fix truncated oracle fetch result
  src/Driver/OCI8/Exception/PHPError.php
  src/Driver/OCI8/Result.php
  tests/Functional/Driver/OCI8/ResultTest.php
Labels: Error Handling, Improvement, oci8

#4597 [GH-4510] Remove ReservedWordsCommand::setKeywordListClass()
  UPGRADE.md
  psalm.xml.dist
  src/Tools/Console/Command/ReservedWordsCommand.php
Labels: BC Break, Reserved Keywords

#4598 [GH-4503] Make OracleSchemaManager::dropAutoincrement() protected
  src/Schema/OracleSchemaManager.php
Labels: Oracle, Schema Managers

#4580 Deprecate Statement::execute in favor of Statement::executeStatement/executeQuery
  lib/Doctrine/DBAL/Statement.php
  tests/Doctrine/Tests/DBAL/Functional/StatementTest.php
Labels: Compatibility, Deprecation

#4599 [GH-4553] Simplify error handling in the OCI8 driver
  src/Driver/OCI8/Exception/PHPError.php
  src/Driver/OCI8/Result.php
  tests/Functional/Driver/OCI8/ResultTest.php
Labels: Error Handling, Prepared Statements, oci8

#4596 Fix BC break on QueryBuilder::execute()
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/ForwardCompatibility/DriverResultStatement.php
  lib/Doctrine/DBAL/ForwardCompatibility/DriverStatement.php
  lib/Doctrine/DBAL/ForwardCompatibility/Result.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  tests/Doctrine/Tests/DBAL/ForwardCompatibility/ResultTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
Labels: BC Fix, Prepared Statements, QueryBuilder

#4605 Merge 2.13.x into 3.0.x
  psalm.xml.dist
  src/Statement.php
  tests/Functional/StatementTest.php
  tests/Query/QueryBuilderTest.php
Labels: Merge Up

#4606 Merge 3.0.x into 3.1.x
  psalm.xml.dist
  src/Statement.php
  tests/Functional/StatementTest.php
  tests/Query/QueryBuilderTest.php
Labels: Merge Up

#4604 Collect type coverage metrics, add badge to README
  .github/workflows/static-analysis.yml
  README.md
Labels: Documentation, Static Analysis

#4608 Attribute type coverage metric to 3.1.x instead of 2.13.x
  README.md
Labels: Documentation, Static Analysis

#4611 Merge 3.0.x into 3.1.x
  .github/workflows/static-analysis.yml
  README.md
Labels: Merge Up

#4614 [GH-4613] Use utf8mb4 instead of utf8 for testing connection charset
  tests/Functional/PrimaryReadReplicaConnectionTest.php
Labels: Character Encoding, Connections, MySQL, Test Suite

#4615 Remove docs about user-provided PDO instance
  docs/en/reference/configuration.rst
Labels: Documentation

#4625 [GH-4613] Use utf8mb4 instead of utf8 for testing connection charset
  tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/PrimaryReadReplicaConnectionTest.php
Labels: Character Encoding, Connections, MySQL, Test Suite

#4620 Use `psr/cache` for result caching
  UPGRADE.md
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Cache/CachingResult.php
  src/Cache/QueryCacheProfile.php
  src/Configuration.php
  src/Connection.php
  tests/ConnectionTest.php
  tests/Functional/ResultCacheTest.php
Labels: Deprecation
