Repository doctrine/dbal, pull requests merged in 2021-02, with the labels that each got.

#4498 Update Psalm to 4.5.2
  .github/workflows/static-analysis.yml
  composer.json
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
  lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
  lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
  lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
  lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php
  psalm.xml.dist
  tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Doctrine/Tests/DBAL/Platforms/DB2PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSQL92PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/PostgreSqlPlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywhere11PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywhere12PlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
  tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
  tests/Doctrine/Tests/DbalFunctionalTestCase.php
Labels: Platforms, Schema Managers, Static Analysis, Test Suite, mysqli

#4499 Manually merge 2.12.x into 3.0.x
  .gitattributes
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  README.md
  SECURITY.md
  ci/github/phpunit/mysqli-tls.xml
  composer.json
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Platforms/SQLServer2012Platform.php
  src/Types/Type.php
  src/Types/TypeRegistry.php
  tests/Functional/ExceptionTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Merge Up

#4500 Manually merge 3.0.x into 3.1.x
  .gitattributes
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  README.md
  SECURITY.md
  ci/github/phpunit/mysqli-tls.xml
  composer.json
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Platforms/SQLServer2012Platform.php
  src/Types/Type.php
  src/Types/TypeRegistry.php
  tests/Functional/ExceptionTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Merge Up

#4501 Manually merge 3.1.x into 4.0.x
  .gitattributes
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/workflows/static-analysis.yml
  README.md
  ci/github/phpunit/mysqli-tls.xml
  composer.json
  phpstan.neon.dist
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Platforms/SQLServer2012Platform.php
  src/Types/Type.php
  src/Types/TypeRegistry.php
  tests/Functional/ExceptionTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/AbstractPostgreSQLPlatformTestCase.php
  tests/Platforms/AbstractSQLServerPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Merge Up

#4502 Fix Example Code
  docs/en/reference/data-retrieval-and-manipulation.rst
Labels: Documentation

#4489 Introduce fetch* methods in query builder
  src/Connection.php
  src/Query/QueryBuilder.php
  tests/Query/QueryBuilderTest.php
Labels: Improvement, QueryBuilder, Static Analysis

#4505 Use better example for data retrieval
  docs/en/reference/data-retrieval-and-manipulation.rst
Labels: Documentation

#4516 Remove Connection::$_expr
  UPGRADE.md
  src/Connection.php
Labels: BC Break, Bug, Connections

#4514 Remove SQLSrv\LastInsertId
  src/Driver/SQLSrv/Connection.php
  src/Driver/SQLSrv/LastInsertId.php
  src/Driver/SQLSrv/Statement.php
Labels: Prepared Statements, Static Analysis, sqlsrv

#4517 Deprecate Connection::$_expr
  UPGRADE.md
  src/Connection.php
Labels: Connections, Deprecation

#4521 Rework handling shared connection in the test suite
  tests/Doctrine/Tests/DBAL/Functional/Connection/ConnectionLostTest.php
  tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/IBMDB2/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Driver/PDO/ConnectionTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php
  tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Doctrine/Tests/DBAL/Functional/TransactionTest.php
  tests/Doctrine/Tests/DbalFunctionalTestCase.php
Labels: Bug, Connections, Test Suite
