Repository doctrine/dbal, pull requests merged in 2022-11, with the labels that each got.

#5806 Bump dev tools
  composer.json
Labels: Test Suite, Static Analysis

#5807 PHPStan 1.9.1
  composer.json
  phpstan.neon.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/DriverManager.php
Labels: Static Analysis

#5811 Merge 3.5.x into 4.0.x
  .doctrine-project.json
  .github/workflows/continuous-integration.yml
  README.md
  composer.json
  phpstan.neon.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver/SQLite3/Driver.php
  src/DriverManager.php
  tests/Cache/QueryCacheProfileTest.php
  tests/Functional/Driver/SQLite3/DriverTest.php
Labels: Merge Up

#5810 Merge tests for fetch behavior of freed results
  tests/Functional/ResultTest.php
  tests/Functional/StatementTest.php
Labels: Test Suite

#5797 Document breaking changes about serverVersion
  UPGRADE.md
  docs/en/reference/configuration.rst
Labels: Documentation
