Repository doctrine/dbal, pull requests merged in 2022-03, with the labels that each got.

#5314 Merge release 3.3.3 into 3.4.x
  .appveyor.yml
  .github/workflows/stale.yml
  composer.json
  psalm-strict.xml
  psalm.xml.dist
Labels: Merge Up

#5316 Merge 3.4.x into 4.0.x
  .appveyor.yml
  .github/workflows/stale.yml
  composer.json
  docs/en/reference/configuration.rst
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/events.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/security.rst
  psalm-strict.xml
  psalm.xml.dist
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
Labels: Merge Up

#5325 Fix assertion in AbstractPostgreSQLDriver::getSchemaManager()
  src/Driver/AbstractPostgreSQLDriver.php
Labels: Bug, PostgreSQL, Platforms, Schema Management, Static Analysis

#5326 Source column defaults from its own table
  src/Platforms/MySQL/Comparator.php
  tests/Functional/Schema/ComparatorTestUtils.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
Labels: Bug, MySQL, Schema Comparison

#5327 Add MariaDB 10.7 to the build matrix
  .github/workflows/continuous-integration.yml
  tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php
Labels: CI, MariaDB

#5329 Merge 2.13.x into 3.3.x
  .github/workflows/continuous-integration.yml
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
Labels: Merge Up

#5330 Merge 3.3.x into 3.4.x
  .github/workflows/continuous-integration.yml
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/MySQL/Comparator.php
  tests/Functional/Schema/ComparatorTestUtils.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
Labels: Merge Up

#5331 Merge 3.4.x into 4.0.x
  .github/workflows/continuous-integration.yml
  src/Platforms/MySQL/Comparator.php
  tests/Functional/Schema/ComparatorTestUtils.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
Labels: Merge Up

#5333 Leverage int-mask-of to make types more precise
  src/Platforms/AbstractPlatform.php
  src/Platforms/SqlitePlatform.php
Labels: Static Analysis

#5332 Support TEXT/BLOB default values on MariaDB
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDBPlatform.php
  tests/Functional/Schema/ComparatorTest.php
Labels: Improvement, MariaDB, Default Values

#5337 Remove the `doctrine-dbal` binary
  UPGRADE.md
  bin/doctrine-dbal
  bin/doctrine-dbal.php
  composer.json
  phpcs.xml.dist
  src/Tools/Console/ConsoleRunner.php
Labels: BC Break
