Repository doctrine/dbal, pull requests merged in 2022-10, with the labels that each got.

#5706 Update Doctrine Coding Standard to 10.0
  composer.json
  src/Exception/ColumnPrecisionRequired.php
  src/Exception/ColumnScaleRequired.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/ColumnDiff.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Code Style

#5705 Deprecate PostgreSQL-specific connection parameters and behavior
  UPGRADE.md
  docs/en/reference/configuration.rst
  src/Driver/PDO/PgSQL/Driver.php
Labels: PostgreSQL, Connections, Configuration, Deprecation

#5707 Deprecate fallback connection to determine platform
  UPGRADE.md
  src/Connection.php
Labels: Connections, Configuration, Platform Detection

#5708 Merge 3.5.x into 4.0.x
  UPGRADE.md
  docs/en/reference/configuration.rst
  src/Connection.php
  src/Driver/PDO/PgSQL/Driver.php
Labels: Merge Up

#5710 Remove property-based false-positive diff workaround from SQLite schema manager
  src/Platforms/SQLitePlatform.php
Labels: SQLite, Schema Management, Schema Comparison

#5709 Remove platform detection fallback
  UPGRADE.md
  src/Connection.php
Labels: Connections, Configuration, BC Break, Platform Detection

#5713 Update PHPStan to 1.8.6
  composer.json
Labels: Dependencies

#5714 Rework some tests that instantiate TableDiff
  tests/Functional/Platform/AddColumnWithDefaultTest.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Schema/Platforms/MySQLSchemaTest.php
Labels: Test Suite, Schema Management, Schema Comparison

#5712 Remove exception handling in server version detection
  src/Connection.php
  src/Driver/OCI8/Connection.php
Labels: Connections, Error Handling, Platform Detection

#5711 Remove PostgreSQL-specific connection parameters and behavior
  UPGRADE.md
  src/Driver/PDO/PgSQL/Driver.php
  src/DriverManager.php
  tests/Functional/Driver/PDO/PgSQL/DriverTest.php
Labels: PostgreSQL, Connections, Configuration, BC Break

#5715 Merge 3.4.x into 3.5.x
  composer.json
  docs/en/reference/introduction.rst
  src/Schema/PostgreSQLSchemaManager.php
Labels: Merge Up

#5717 Mark TableDiff public properties internal
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/Comparator.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/TableDiff.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Schema Comparison, Deprecation

#5718 Use latest versions of Github actions
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/stale.yml
  .github/workflows/static-analysis.yml
Labels: CI

#5719 Merge 3.5.x into 4.0.x
  UPGRADE.md
  composer.json
  docs/en/reference/introduction.rst
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/Comparator.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLiteSchemaManager.php
  src/Schema/TableDiff.php
  tests/Functional/Platform/AddColumnWithDefaultTest.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/Platforms/MySQLSchemaTest.php
Labels: Merge Up

#5721 Deprecating misspelled isFullfilledBy() method
  UPGRADE.md
  src/Schema/Index.php
Labels: Deprecation

#5722 Merge 3.5.x up into 4.0.x
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/stale.yml
  .github/workflows/static-analysis.yml
  UPGRADE.md
  docs/en/reference/portability.rst
  psalm.xml.dist
  src/Schema/Comparator.php
  src/Schema/Index.php
  src/Schema/Table.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Schema/IndexTest.php
Labels: Merge Up

#5724 Removing deprecated `isFullfilledBy()` method
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Index.php
  src/Schema/Table.php
Labels: BC Break

#5725 Improve ergonomics of invalid colum declaration exceptions
  src/Exception/ColumnPrecisionRequired.php
  src/Exception/ColumnScaleRequired.php
  src/Exception/InvalidColumnDeclaration.php
  src/Exception/InvalidColumnType.php
  src/Exception/InvalidColumnType/ColumnLengthRequired.php
  src/Exception/InvalidColumnType/ColumnPrecisionRequired.php
  src/Exception/InvalidColumnType/ColumnScaleRequired.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/SQLServerPlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
Labels: Error Handling, Schema Definition

#5727 Clarify semantics of logic exceptions
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/DriverManager.php
  src/Exception/DriverRequired.php
  src/Exception/InvalidColumnDeclaration.php
  src/Exception/InvalidColumnType.php
  src/Exception/InvalidDriverClass.php
  src/Exception/InvalidWrapperClass.php
  src/Exception/UnknownDriver.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Exception/NotSupported.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/SQL/Builder/CreateSchemaObjectsSQLBuilder.php
  src/SQL/Builder/DropSchemaObjectsSQLBuilder.php
  src/Schema/AbstractSchemaManager.php
  src/Types/Type.php
Labels: Improvement, Error Handling

#5728 Deprecate SchemaException codes
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Exception/ColumnAlreadyExists.php
  src/Schema/Exception/ColumnDoesNotExist.php
  src/Schema/Exception/ForeignKeyDoesNotExist.php
  src/Schema/Exception/IndexAlreadyExists.php
  src/Schema/Exception/IndexDoesNotExist.php
  src/Schema/Exception/IndexNameInvalid.php
  src/Schema/Exception/NamedForeignKeyRequired.php
  src/Schema/Exception/NamespaceAlreadyExists.php
  src/Schema/Exception/SequenceAlreadyExists.php
  src/Schema/Exception/SequenceDoesNotExist.php
  src/Schema/Exception/TableAlreadyExists.php
  src/Schema/Exception/TableDoesNotExist.php
  src/Schema/Exception/UniqueConstraintDoesNotExist.php
  src/Schema/SchemaException.php
Labels: Schema Management, Error Handling, Deprecation

#5729 Merge 3.5.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Schema/SchemaException.php
Labels: Merge Up

#5730 Remove SchemaException error codes
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Exception/ColumnAlreadyExists.php
  src/Schema/Exception/ColumnDoesNotExist.php
  src/Schema/Exception/ForeignKeyDoesNotExist.php
  src/Schema/Exception/IndexAlreadyExists.php
  src/Schema/Exception/IndexDoesNotExist.php
  src/Schema/Exception/IndexNameInvalid.php
  src/Schema/Exception/NamedForeignKeyRequired.php
  src/Schema/Exception/NamespaceAlreadyExists.php
  src/Schema/Exception/SequenceAlreadyExists.php
  src/Schema/Exception/SequenceDoesNotExist.php
  src/Schema/Exception/TableAlreadyExists.php
  src/Schema/Exception/TableDoesNotExist.php
  src/Schema/Exception/UniqueConstraintDoesNotExist.php
  src/Schema/SchemaException.php
Labels: Schema Management, Error Handling, BC Break

#5731 Deprecate Table methods
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Schema/Comparator.php
  src/Schema/Table.php
Labels: Schema Management, Foreign Keys, Primary Keys, Deprecation

#5732 Merge 3.5.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Schema/Comparator.php
  src/Schema/Table.php
Labels: Merge Up

#5733 Remove Table methods
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Table.php
  tests/Functional/Platform/NewPrimaryKeyWithNewAutoIncrementColumnTest.php
  tests/Functional/Platform/PlatformRestrictionsTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Schema/TableTest.php
Labels: Schema Management, BC Break, Foreign Keys, Primary Keys

#5735 Convert Doctrine\DBAL\Schema\SchemaException to an interface
  UPGRADE.md
  src/Schema/Column.php
  src/Schema/Comparator.php
  src/Schema/Exception/ColumnAlreadyExists.php
  src/Schema/Exception/ColumnDoesNotExist.php
  src/Schema/Exception/ForeignKeyDoesNotExist.php
  src/Schema/Exception/IndexAlreadyExists.php
  src/Schema/Exception/IndexDoesNotExist.php
  src/Schema/Exception/IndexNameInvalid.php
  src/Schema/Exception/InvalidTableName.php
  src/Schema/Exception/NamespaceAlreadyExists.php
  src/Schema/Exception/SequenceAlreadyExists.php
  src/Schema/Exception/SequenceDoesNotExist.php
  src/Schema/Exception/TableAlreadyExists.php
  src/Schema/Exception/TableDoesNotExist.php
  src/Schema/Exception/UniqueConstraintDoesNotExist.php
  src/Schema/Exception/UnknownColumnOption.php
  src/Schema/Schema.php
  src/Schema/SchemaException.php
  src/Schema/Table.php
Labels: Improvement, Error Handling, BC Break

#5736 Bump dev dependencies
  composer.json
  phpstan.neon.dist
Labels: Test Suite, Static Analysis, Dependencies

#5740 Merge 3.4.x into 3.5.x
  composer.json
  phpstan.neon.dist
  tests/Functional/Driver/PDO/SQLite/DriverTest.php
Labels: Merge Up

#5742 Deprecated the `userDefinedFunctions` driver option for `pdo_sqlite`
  UPGRADE.md
  src/Driver/PDO/SQLite/Driver.php
  tests/Functional/Driver/PDO/SQLite/DriverTest.php
Labels: pdo_sqlite, Drivers, Deprecation

#5743 Merge 3.5.x into 4.0.x
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/sqlite3.xml
  docs/en/reference/configuration.rst
  phpcs.xml.dist
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/SQLite3/Connection.php
  src/Driver/SQLite3/Driver.php
  src/Driver/SQLite3/Exception.php
  src/Driver/SQLite3/Result.php
  src/Driver/SQLite3/Statement.php
  src/DriverManager.php
  tests/Functional/Driver/PDO/SQLite/DriverTest.php
  tests/Functional/Driver/SQLite3/DriverTest.php
  tests/Functional/StatementTest.php
  tests/TestUtil.php
Labels: Merge Up

#5744 Remove deprecated API to register custom SQLite functions
  UPGRADE.md
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/SQLite3/Driver.php
  tests/Functional/Driver/PDO/SQLite/DriverTest.php
Labels: SQLite, pdo_sqlite, Drivers, BC Break

#5747 Deprecate Table::changeColumn()
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Table.php
Labels: Schema Management, Deprecation

#5746 Rework some tests that instantiate TableDiff
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Test Suite, Schema Management, Schema Comparison

#5748 Merge 3.5.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Table.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#5749 Deprecate `LOCATE()` emulation on SQLite
  UPGRADE.md
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Platforms/SqlitePlatform.php
  tests/Functional/DataAccessTest.php
Labels: SQLite, Platforms, Deprecation

#5754 Merge 3.5.x into 4.0.x
  UPGRADE.md
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Platforms/SQLitePlatform.php
  tests/Functional/DataAccessTest.php
Labels: Merge Up

#5755 Use the `%` operator instead of `MOD()` in SQLite
  src/Platforms/SqlitePlatform.php
Labels: SQLite, Platforms

#5756 Merge 3.4.x into 3.5.x
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Test Suite, Merge Up

#5753 Declare internal properties of TableDiff as private
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDBPlatform.php
  src/Schema/Comparator.php
  src/Schema/SQLiteSchemaManager.php
  src/Schema/TableDiff.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/ComparatorTest.php
Labels: Schema Comparison

#5757 Merge 3.5.x into 4.0.x
  src/Platforms/SQLitePlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SQLitePlatformTest.php
Labels: Test Suite, Merge Up

#5750 Allow doctrine/event-manager 2
  composer.json
Labels: Dependencies

#5759 Remove user defined SQLite functions
  UPGRADE.md
  src/Driver/API/SQLite/UserDefinedFunctions.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/SQLite3/Driver.php
  tests/Functional/DataAccessTest.php
Labels: SQLite, BC Break

#5758 Mark SchemaDiff public properties internal
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
Labels: Schema Comparison, Deprecation

#5762 Merge 3.5.x into 4.0.x
  UPGRADE.md
  composer.json
  psalm.xml.dist
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
Labels: Merge Up

#5763 Remove handling orphaned foreign keys
  UPGRADE.md
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
  src/Schema/TableDiff.php
  tests/Schema/ComparatorTest.php
Labels: Schema Management, BC Break, Schema Comparison

#5767 Declare internal properties of SchemaDiff as private
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Schema/ComparatorTest.php
Labels: Schema Comparison

#5766 Deprecate SchemaDiff::toSql() and SchemaDiff::toSaveSql()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/SchemaDiff.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Schema Management, Schema Comparison, Deprecation

#5769 Remove the APIs deprecated in DBAL 3.x
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Table.php
  src/Types/Types.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
Labels: Schema Management, BC Break

#5770 Non-nullabe result of comparing tables
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
  src/Schema/TableDiff.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Improvement, Schema Comparison

#5772 PHPStan 1.8.10, Psalm 4.29.0
  composer.json
Labels: Static Analysis

#5771 Add 3.5 and 4.0 to .doctrine-project.json
  .doctrine-project.json
Labels: Documentation

#5773 Merge 3.5.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/SchemaDiff.php
  src/Schema/TableDiff.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#5774 Remove SchemaDiff::toSql() and SchemaDiff::toSaveSql()
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Schema/SchemaDiff.php
Labels: Schema Management, BC Break, Schema Comparison

#5775 Remove Comparator::diffTable()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/MySQL/Comparator.php
  src/Platforms/SQLServer/Comparator.php
  src/Platforms/SQLite/Comparator.php
  src/Schema/Comparator.php
  tests/Functional/Platform/AddColumnWithDefaultTest.php
  tests/Functional/Platform/AlterColumnTest.php
  tests/Functional/Platform/AlterDecimalColumnTest.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/ColumnCommentTest.php
  tests/Functional/Schema/ComparatorTest.php
  tests/Functional/Schema/ComparatorTestUtils.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/Oracle/ComparatorTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQL/ComparatorTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Functional/Ticket/DBAL510Test.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Schema/ComparatorTest.php
  tests/Schema/Platforms/MySQLSchemaTest.php
Labels: BC Break, Schema Comparison

#5777 Remove irrelevant @throws annotations
  src/Platforms/AbstractPlatform.php
  src/Platforms/Exception/NoColumnsSpecifiedForTable.php
  src/SQL/Builder/CreateSchemaObjectsSQLBuilder.php
  src/Schema/Comparator.php
Labels: Error Handling

#5765 Use default schema if `$tableName` has no namespace.
  src/Schema/PostgreSQLSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: Bug, Regression, PostgreSQL, Schema Introspection

#5779 Clean up MySQL version detection logic
  src/Driver/AbstractMySQLDriver.php
  tests/Driver/AbstractDriverTest.php
  tests/Driver/AbstractMySQLDriverTest.php
Labels: MySQL, MariaDB, Platform Detection

#5780 Deprecate QueryBuilder::getConnection()
  UPGRADE.md
  psalm.xml.dist
  src/Query/QueryBuilder.php
Labels: QueryBuilder, Deprecation

#5782 Run tests with Postgres 15
  .github/workflows/continuous-integration.yml
Labels: CI, PostgreSQL

#5783 Merge 3.4.x into 3.5.x
  .doctrine-project.json
  .github/workflows/continuous-integration.yml
  composer.json
  src/Schema/PostgreSQLSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: Merge Up

#5785 Deprecate extension via certain types of events
  UPGRADE.md
  docs/en/reference/events.rst
  psalm.xml.dist
  src/Connection.php
  src/Event/SchemaAlterTableAddColumnEventArgs.php
  src/Event/SchemaAlterTableChangeColumnEventArgs.php
  src/Event/SchemaAlterTableEventArgs.php
  src/Event/SchemaAlterTableRemoveColumnEventArgs.php
  src/Event/SchemaAlterTableRenameColumnEventArgs.php
  src/Event/SchemaColumnDefinitionEventArgs.php
  src/Event/SchemaCreateTableColumnEventArgs.php
  src/Event/SchemaCreateTableEventArgs.php
  src/Event/SchemaDropTableEventArgs.php
  src/Event/SchemaEventArgs.php
  src/Event/SchemaIndexDefinitionEventArgs.php
  src/Event/TransactionBeginEventArgs.php
  src/Event/TransactionCommitEventArgs.php
  src/Event/TransactionEventArgs.php
  src/Event/TransactionRollBackEventArgs.php
  src/Events.php
  src/Platforms/AbstractPlatform.php
  src/Schema/AbstractSchemaManager.php
Labels: Schema Management, Events, Deprecation

#5786 Deprecate extension via Doctrine Event Manager
  UPGRADE.md
  ci/github/phpunit/oci8.xml
  ci/github/phpunit/pdo_oci.xml
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/sqlite3.xml
  docs/en/reference/events.rst
  docs/en/sidebar.rst
  psalm.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver/AbstractSQLiteDriver/Middleware/EnableForeignKeys.php
  src/Driver/OCI8/Middleware/InitializeSession.php
  src/Event/ConnectionEventArgs.php
  src/Event/Listeners/OracleSessionInit.php
  src/Event/Listeners/SQLSessionInit.php
  src/Event/Listeners/SQLiteSessionInit.php
  src/Events.php
  src/Platforms/AbstractPlatform.php
  tests/TestUtil.php
Labels: Events, Deprecation

#5787 Merge 3.5.x into 4.0.x
  .doctrine-project.json
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  ci/github/phpunit/oci8.xml
  ci/github/phpunit/pdo_oci.xml
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/sqlite3.xml
  composer.json
  docs/en/reference/events.rst
  docs/en/sidebar.rst
  psalm.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractSQLiteDriver/Middleware/EnableForeignKeys.php
  src/Driver/OCI8/Middleware/InitializeSession.php
  src/Event/ConnectionEventArgs.php
  src/Event/Listeners/OracleSessionInit.php
  src/Event/Listeners/SQLSessionInit.php
  src/Event/Listeners/SQLiteSessionInit.php
  src/Event/SchemaAlterTableAddColumnEventArgs.php
  src/Event/SchemaAlterTableChangeColumnEventArgs.php
  src/Event/SchemaAlterTableEventArgs.php
  src/Event/SchemaAlterTableRemoveColumnEventArgs.php
  src/Event/SchemaAlterTableRenameColumnEventArgs.php
  src/Event/SchemaColumnDefinitionEventArgs.php
  src/Event/SchemaCreateTableColumnEventArgs.php
  src/Event/SchemaCreateTableEventArgs.php
  src/Event/SchemaDropTableEventArgs.php
  src/Event/SchemaEventArgs.php
  src/Event/SchemaIndexDefinitionEventArgs.php
  src/Event/TransactionBeginEventArgs.php
  src/Event/TransactionCommitEventArgs.php
  src/Event/TransactionEventArgs.php
  src/Event/TransactionRollBackEventArgs.php
  src/Events.php
  src/Platforms/AbstractPlatform.php
  src/Query/QueryBuilder.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/Driver/AbstractDriverTest.php
  tests/Driver/AbstractMySQLDriverTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/TestUtil.php
Labels: Merge Up

#5790 Update project metadata
  .doctrine-project.json
  README.md
Labels: Documentation

#5789 Remove QueryBuilder::getConnection()
  UPGRADE.md
  src/Query/QueryBuilder.php
  tests/Query/QueryBuilderTest.php
Labels: QueryBuilder, BC Break

#5795 Revert "Clean up MySQL version detection logic"
  src/Driver/AbstractMySQLDriver.php
  tests/Driver/AbstractDriverTest.php
  tests/Driver/AbstractMySQLDriverTest.php
Labels: Bug, Regression

#5799 Fix typo in exception message
  src/Driver/SQLite3/Driver.php
  tests/Functional/Driver/SQLite3/DriverTest.php
Labels: Bug, sqlite3

#5798 Run tests with MariaDB 10.9
  .github/workflows/continuous-integration.yml
Labels: CI, MariaDB

#5801 Remove unwanted suffix
  docs/en/sidebar.rst
Labels: Documentation
