Repository doctrine/dbal, pull requests merged in 2022-05, with the labels that each got.

#5370 Psalm 4.23, PHPStan 1.6.3
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
Labels: Static Analysis

#5371 Allow doctrine/deprecations 1.0
  composer.json
Labels: Dependencies

#5372 Merge 3.3.x into 3.4.x
  composer.json
  docs/en/reference/transactions.rst
  phpstan.neon.dist
  psalm.xml.dist
  src/DriverManager.php
Labels: Merge Up

#5374 Remove CA bundle from AppVeyor
  .appveyor.yml
Labels: CI

#5375 Merge 3.3.x into 3.4.x
  .appveyor.yml
Labels: Merge Up

#5373 Deprecate AbstractPlatform::getVarcharTypeDeclarationSQL()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Types/DateIntervalType.php
  src/Types/StringType.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
  tests/Types/StringTest.php
Labels: Platforms, Deprecation

#5377 Add runtime deprecations for default string column length
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/SQLServerPlatform.php
Labels: MySQL, SQL Server, IBM DB2, Oracle, Schema Definition, Deprecation

#5378 Use more precise phpdoc
  src/Connection.php
  src/Platforms/AbstractPlatform.php
Labels: Static Analysis

#5380 Merge 3.3.x up into 3.4.x
  docs/en/reference/transactions.rst
Labels: Merge Up

#5383 Deprecate transaction nesting without savepoints
  UPGRADE.md
  docs/en/reference/transactions.rst
  src/Connection.php
  tests/ConnectionTest.php
  tests/Functional/ConnectionTest.php
Labels: Deprecation

#5385 Deprecate passing date interval parameters as integers
  UPGRADE.md
  src/Platforms/AbstractPlatform.php
Labels: Platforms, Deprecation

#5384 Merge 3.4.x into 4.0.x
  .appveyor.yml
  UPGRADE.md
  composer.json
  docs/en/reference/transactions.rst
  phpstan.neon.dist
  src/Connection.php
  src/DriverManager.php
  src/Platforms/AbstractPlatform.php
  tests/Functional/ConnectionTest.php
  tests/Types/StringTest.php
Labels: Merge Up

#5387 Deprecate AbstractSchemaManager::getDatabasePlatform()
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/FunctionalTestCase.php
Labels: Schema Management, Deprecation

#5388 Deprecate AbstractPlatform methods exposing quote characters
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
Labels: Platforms, Deprecation

#5393 Remove hard-coded string column length
  src/Platforms/SqlitePlatform.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Platforms, Schema Management

#5392 Addition documentation for prior deprecations
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
Labels: Platforms, Deprecation

#5395 Check integer types via PhpIntegerMappingType
  src/Platforms/PostgreSQLPlatform.php
Labels: Bug, PostgreSQL, Schema Management

#5394 Remove PostgreSQLPlatform::isNumericType()
  src/Platforms/PostgreSQLPlatform.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: Bug, PostgreSQL, Schema Management

#5396 Autoincrement via identity columns on PostgreSQL
  UPGRADE.md
  docs/en/how-to/postgresql-identity-migration.rst
  docs/en/sidebar.rst
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: Improvement, PostgreSQL, BC Break

#5399 Merge 3.3.x into 3.4.x
  docs/en/reference/upgrading.rst
  docs/en/sidebar.rst
Labels: Merge Up

#5400 Merge 3.4.x into 4.0.x
  UPGRADE.md
  docs/en/reference/transactions.rst
  docs/en/reference/upgrading.rst
  docs/en/sidebar.rst
  psalm.xml.dist
  src/Connection.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  src/Schema/Table.php
  tests/Functional/ConnectionTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/FunctionalTestCase.php
Labels: Merge Up

#5401 Remove support for transaction nesting without savepoints
  UPGRADE.md
  docs/en/reference/transactions.rst
  src/Connection.php
  src/Exception/MayNotAlterNestedTransactionWithSavepointsInTransaction.php
  tests/ConnectionTest.php
  tests/Functional/ConnectionTest.php
Labels: Deprecation

#5402 Natural order of SQLite foreign keys
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Improvement, SQLite, Schema Introspection

#5404 Run more foreign key tests on SQLite
  src/Driver/API/SQLite/ExceptionConverter.php
  src/Event/Listeners/SQLiteSessionInit.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Functional/ExceptionTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/TestUtil.php
Labels: Bug, Improvement, SQLite, Foreign Keys

#5407 Create sequences before tables
  src/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Functional/Schema/PostgreSQL/SchemaTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
Labels: Bug, PostgreSQL, Schema Management, Sequences

#5409 Improve foreign key introspection on SQLite
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Improvement, SQLite, Schema Introspection, Foreign Keys, Deprecation

#5410 Merge 3.4.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Event/Listeners/SQLiteSessionInit.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
  tests/TestUtil.php
Labels: Merge Up

#5411 Mark SQLite platform as not supporting foreign keys
  src/Platforms/AbstractPlatform.php
  src/Platforms/SqlitePlatform.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: SQLite, Foreign Keys

#5412 Merge 3.4.x up into 4.0.x
  src/Platforms/AbstractPlatform.php
  src/Platforms/SqlitePlatform.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
Labels: Merge Up

#5414 Deprecate ignoring foreign keys DDL on non-InnoDB MySQL
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
Labels: MySQL, Schema Management, Foreign Keys, Deprecation

#5415 Update documentation for the `guid` type
  docs/en/reference/types.rst
Labels: Documentation, Type Mapping

#5417 Run Psalm with language level PHP 8.1
  psalm-strict.xml
  psalm.xml.dist
Labels: Static Analysis

#5418 Merge 3.3.x into 3.4.x
  docs/en/reference/types.rst
  psalm-strict.xml
  psalm.xml.dist
  src/Schema/Visitor/CreateSchemaSqlCollector.php
  tests/Functional/Schema/PostgreSQL/SchemaTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Schema/Visitor/SchemaSqlCollectorTest.php
Labels: Merge Up
