Repository doctrine/dbal, pull requests merged in 2022-02, with the labels that each got.

#5229 Add section on result types not being guaranteed
  docs/en/reference/data-retrieval-and-manipulation.rst
Labels: Documentation

#5230 Deprecated AbstractPlatform::getListTableConstraintsSQL()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SqlitePlatform.php
Labels: Platforms, Deprecation

#5226 Oracle: Convert array keys to lowercase
  src/Schema/OracleSchemaManager.php
Labels: Bug, Oracle, Schema Management

#5238 Run PHP 7.4 on AppVeyor
  .appveyor.yml
Labels: CI

#5239 Merge 2.13.x into 3.3.x
  .appveyor.yml
Labels: Merge Up

#5240 Merge 3.3.x into 3.4.x
  .appveyor.yml
  docs/en/reference/data-retrieval-and-manipulation.rst
  src/Schema/OracleSchemaManager.php
Labels: Merge Up

#5224 Ignore columnDefinition in schema comparison
  src/Platforms/AbstractPlatform.php
  tests/Schema/ComparatorTest.php
Labels: Bug, Schema, Schema Comparison, Schema Definition, Columns

#5232 Consider CASE_LOWER being equal to 0 in portability middleware
  src/Portability/Driver.php
  tests/Functional/PortabilityTest.php
Labels: Bug, IBM DB2, Oracle, Portability

#5241 Merge 3.4.x into 4.0.x
  UPGRADE.md
  docs/en/reference/data-retrieval-and-manipulation.rst
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/OracleSchemaManager.php
Labels: Merge Up

#5245 Fix typo
  src/Connection.php
Labels: Static Analysis

#5246 Add support for collation option to MySQL
  src/Platforms/AbstractMySQLPlatform.php
  tests/Platforms/MySQLPlatformTest.php
Labels: Bug

#5036 Drop Flyweight pattern
  docs/en/reference/types.rst
  src/Types/Exception/TypeAlreadyRegistered.php
  src/Types/Type.php
  src/Types/TypeRegistry.php
  tests/Types/Exception/TypeAlreadyRegisteredTest.php
  tests/Types/TypeRegistryTest.php
Labels: Type Mapping

#5248 Merge 3.3.x into 3.4.x
  src/Connection.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Portability/Driver.php
  tests/Functional/PortabilityTest.php
  tests/Platforms/MySQLPlatformTest.php
  tests/Schema/ComparatorTest.php
Labels: Merge Up

#5249 Deprecate collate option
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Platforms/MySQLPlatformTest.php
Labels: Deprecation

#5251 Merge 2.13.x up into 3.3.x
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Merge Up

#5253 Make phpdoc accurate
  tests/Functional/PortabilityTest.php
Labels: Test Suite

#5254 Merge 3.3.x up into 3.4.x
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/PULL_REQUEST_TEMPLATE.md
  tests/Functional/PortabilityTest.php
Labels: Merge Up

#5252 Merge 3.4.x into 4.0.x
  .github/ISSUE_TEMPLATE/BC_Break.md
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/PULL_REQUEST_TEMPLATE.md
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Portability/Driver.php
  tests/Functional/PortabilityTest.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Platforms/MySQLPlatformTest.php
  tests/Schema/ComparatorTest.php
Labels: Merge Up

#5255 Drop support for collate option
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  tests/Platforms/MySQLPlatformTest.php
Labels: BC Break

#5261 More accurate params
  src/Connection.php
  src/DriverManager.php
Labels: Static Analysis

#5263 Remove obsolete PHPStan rules regarding `compareSchemas()` calls
  phpstan.neon.dist
Labels: Static Analysis

#5262 PHPStan 1.4.6, Psalm 4.20.0, PHPUnit 9.5.13
  composer.json
  psalm.xml.dist
Labels: Static Analysis

#5256 Single PostgreSQLPlatform::getListSequencesSQL
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/Platforms/PostgreSQL100PlatformTest.php
Labels: Improvement, PostgreSQL, Platforms

#5264 Merge 2.13.x into 3.3.x
  composer.json
Labels: Merge Up

#5266 Add CI Job for testing with SQLite on Ubuntu 18.04
  .github/workflows/continuous-integration.yml
Labels: CI, pdo_sqlite

#5269 Run static analysis jobs on PHP 8.1
  .github/workflows/static-analysis.yml
  lib/Doctrine/DBAL/Cache/ResultCacheStatement.php
  lib/Doctrine/DBAL/Connection.php
  lib/Doctrine/DBAL/Driver/Connection.php
  lib/Doctrine/DBAL/Driver/Mysqli/Exception/ConnectionFailed.php
  lib/Doctrine/DBAL/Driver/Result.php
  lib/Doctrine/DBAL/Driver/Statement.php
  lib/Doctrine/DBAL/Query/QueryBuilder.php
  lib/Doctrine/DBAL/Statement.php
  phpstan.neon.dist
  psalm.xml.dist
Labels: mysqli, Error Handling, Static Analysis

#5270 Remove enforcement of consistent constructor from KeywordList
  src/Platforms/Keywords/KeywordList.php
Labels: Reserved Keywords, Static Analysis

#5273 Merge 3.4.x into 4.0.x
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Connection.php
  src/Driver/Mysqli/Exception/ConnectionFailed.php
  src/Driver/PDO/Connection.php
  src/DriverManager.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/DriverManagerTest.php
Labels: Merge Up

#5274 Return number of affected rows greater than PHP_INT_MAX as string
  UPGRADE.md
  phpstan.neon.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver/Connection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/Middleware/AbstractConnectionMiddleware.php
  src/Driver/Mysqli/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/SQLSrv/Connection.php
  src/Logging/Connection.php
  src/Query/QueryBuilder.php
Labels: Improvement, BC Break, Prepared Statements

#5268 Optimize schema managers' ::listTables() methods
  UPGRADE.md
  psalm.xml.dist
  src/Exception/DatabaseRequired.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: Improvement, Performance, Schema Introspection, Deprecation

#5276 Merge 3.4.x into 4.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: Merge Up

#5279 Nest deprecations for 3.4 under 3.4
  UPGRADE.md
Labels: Documentation

#5277 Recommend a better charset by default
  docs/en/reference/configuration.rst
Labels: MySQL, Documentation

#5280 Declare abstract AbstractSchemaManager methods as such
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: BC Break, Schema Introspection

#5281 Reimplement more Schema Manager listTable*() methods with the new API
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Schema/MySQLSchemaManagerTest.php
Labels: Schema Introspection

#5282 Merge 3.4.x into 4.0.x
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Schema/MySQLSchemaManagerTest.php
Labels: Merge Up

#5283 Remove schema introspection methods from AbstractPlatform
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SqliteSchemaManager.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTestCase.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Platforms, BC Break, Schema Introspection

#5287 Deprecate passing $database to AbstractSchemaManager::list*()
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
Labels: Schema Introspection, Deprecation

#5288 Merge 3.4.x into 4.0.x
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
Labels: Merge Up

#5289 Remove $database from AbstractSchemaManager::list*() methods
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: BC Break, Schema Introspection

#5290 Remove user related methods from the schema manager
  src/Schema/AbstractSchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
Labels: Platforms

#5292 OFFSET keyword for MariaDB
  src/Platforms/Keywords/MariaDBKeywords.php
Labels: Bug, MariaDB, Reserved Keywords

#5296 Fix #4869: PHP 8.1 deprecated passing null to #7 flags parameter for …
  lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php
Labels: Bug, mysqli, PHP

#5294 Modernize array syntax used in code examples
  docs/en/reference/configuration.rst
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/events.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/security.rst
Labels: Documentation

#5299 Merge 3.3.x into 3.4.x
  docs/en/reference/configuration.rst
  docs/en/reference/data-retrieval-and-manipulation.rst
  docs/en/reference/events.rst
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/schema-representation.rst
  docs/en/reference/security.rst
  src/Platforms/Keywords/MariaDBKeywords.php
Labels: Merge Up

#5300 Psalm 4.22.0, PHPUnit 9.5.16
  composer.json
  psalm-strict.xml
  psalm.xml.dist
Labels: Static Analysis, Dependencies

#5301 Merge 2.13.x into 3.3.x
  composer.json
  psalm-strict.xml
  psalm.xml.dist
Labels: Merge Up

#5303 Run workflow on AppVeyor only if certain files changed
  .appveyor.yml
Labels: CI, SQL Server

#5304 Merge 2.13.x into 3.3.x
  .appveyor.yml
Labels: Merge Up
