Repository doctrine/dbal, pull requests merged in 2023-11, with the labels that each got.

#6189 MySQLSchemaManager. Check expected database type for json columns only.
  src/Schema/MySQLSchemaManager.php
  tests/Functional/Schema/CustomIntrospectionTest.php
  tests/Functional/Schema/Types/Money.php
  tests/Functional/Schema/Types/MoneyType.php
Labels: Bug, MariaDB, Schema Introspection

#6207 Run tests on MySQL 8.2
  .github/workflows/continuous-integration.yml
Labels: CI, MySQL

#6210 Generalize CustomIntrospectionTest
  tests/Functional/Schema/CustomIntrospectionTest.php
Labels: Test Suite

#6208 Merge 3.8.x into 4.0.x
  .github/workflows/continuous-integration.yml
  src/Query/Expression/CompositeExpression.php
  tests/Functional/Schema/CustomIntrospectionTest.php
  tests/Functional/Schema/Types/Money.php
  tests/Functional/Schema/Types/MoneyType.php
Labels: Merge Up

#6211 PHPStan 1.10.41
  composer.json
Labels: Static Analysis

#6212 PHPUnit 10.4.2
  composer.json
Labels: Test Suite

#6202 Fix MariaDB list columns performance
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDb1043Platform.php
  src/Schema/MySQLSchemaManager.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
Labels: Bug, MariaDB, Performance, Schema Introspection

#6213 Deprecate AbstractMySQLPlatform::getColumnTypeSQLSnippets()
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
Labels: Deprecation

#6215 Extend `AbstractMySQLPlatform::getColumnTypeSQLSnippets()` deprecation layer
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDb1043Platform.php
Labels: MariaDB, Platforms, Deprecation

#6216 Move `getJsonTypeDeclarationSQL()` to `AbstractMySQLPlatform`
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MySQLPlatform.php
Labels: Improvement, MySQL, MariaDB, Platforms

#6191 Enable skipping locked rows in QueryBuilder
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Driver/OCI8/Driver.php
  src/Id/TableGenerator.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/MariaDb1060Platform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/PostgreSQL100Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServer/SQL/Builder/SQLServerSelectSQLBuilder.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SqlitePlatform.php
  src/Query/ForUpdate.php
  src/Query/ForUpdate/ConflictResolutionMode.php
  src/Query/Limit.php
  src/Query/QueryBuilder.php
  src/Query/SelectQuery.php
  src/SQL/Builder/DefaultSelectSQLBuilder.php
  src/SQL/Builder/SelectSQLBuilder.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Query/QueryBuilderTest.php
  tests/Query/QueryBuilderTest.php
Labels: New Feature, QueryBuilder, Locking, Deprecation

#6219 Remove deprecated lock-related methods
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Query/ForUpdate.php
  src/Query/ForUpdate/ConflictResolutionMode.php
  src/Query/QueryBuilder.php
  tests/Platforms/DB2PlatformTest.php
Labels: BC Break

#6214 Remove AbstractMySQLPlatform::getColumnTypeSQLSnippets()
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  src/Schema/MySQLSchemaManager.php
Labels: MariaDB, Platforms, BC Break

#6221 Relax return types of getExceptionConverter() implementations
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
  src/Driver/AbstractSQLServerDriver.php
  src/Driver/AbstractSQLiteDriver.php
Labels: Drivers, Static Analysis

#6223 PHPStan 1.10.42
  composer.json
Labels: Static Analysis

#6222 Remove API to disable column comments
  psalm.xml.dist
  src/Configuration.php
  src/Connection.php
  src/Platforms/AbstractPlatform.php
Labels: Improvement, Types, Configuration

#6224 Bump Symfony dependencies
  composer.json
Labels: CI

#6229 CI: Drop MariaDB 10.10, add MariaDB 11.2
  .github/workflows/continuous-integration.yml
Labels: CI, MariaDB

#6226 Move schema part to the index
  psalm.xml.dist
  src/Platforms/SqlitePlatform.php
  tests/Functional/Platform/OtherSchemaTest.php
Labels: Bug, SQLite

#6148 Allow Symfony 7 in require-dev
  composer.json
Labels: CI
