Repository doctrine/dbal, pull requests merged in 2023-07, with the labels that each got.

#6086 Use Deprecation::triggerIfCalledFromOutside in listTableDetails
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
Labels: Bug

#6095 Merge 3.6.x into 3.7.x
  UPGRADE.md
  src/Schema/AbstractSchemaManager.php
  src/Schema/DB2SchemaManager.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Types/Type.php
Labels: Merge Up

#6069 Add documentation for #6044
  docs/en/reference/schema-representation.rst
Labels: Documentation

#6082 Optimize TypeRegistry::lookupName() from O(N) to O(1)
  src/Types/TypeRegistry.php
  tests/Types/TypeRegistryTest.php
Labels: Improvement, Types, Performance

#6093 Fix blob binding overwrite on DB2
  src/Driver/IBMDB2/Statement.php
  tests/Functional/BlobTest.php
Labels: Bug, ibm_db2, Prepared Statements

#6108 Avoid self deprecation about listTableColumn
  src/Schema/AbstractSchemaManager.php
Labels: Bug

#6096 Merge 3.7.x into 4.0.x
  UPGRADE.md
  docs/en/reference/schema-representation.rst
  src/Driver/IBMDB2/Statement.php
  src/Types/TypeRegistry.php
  tests/Functional/BlobTest.php
  tests/Types/TypeRegistryTest.php
Labels: Merge Up

#6111 Pin Slevomat Coding Standard
  composer.json
Labels: Code Style

#6116 PHPStan 1.10.26
  composer.json
  phpstan.neon.dist
Labels: Static Analysis
