Repository doctrine/dbal, pull requests merged in 2023-06, with the labels that each got.

#6051 Reference the right argument
  UPGRADE.md
  src/Schema/TableDiff.php
  tests/Schema/TableDiffTest.php
Labels: Bug

#6053 Fix deprecation layer in Table
  src/Schema/Table.php
Labels: Bug, Schema

#6054 Merge 3.6.x into 3.7.x
  UPGRADE.md
  src/Schema/Table.php
  src/Schema/TableDiff.php
  tests/Schema/TableDiffTest.php
Labels: Merge Up

#5917 Add test for `Mysqli\Result`
  phpcs.xml.dist
  tests/Functional/Driver/Mysqli/ResultTest.php
Labels: Test Suite, mysqli

#6059 Allow `DsnParser` to parse `driverClass` via `$schemeMapping`
  docs/en/reference/configuration.rst
  src/Tools/DsnParser.php
  tests/Tools/DsnParserTest.php
Labels: New Feature, Configuration, DSN Parser

#6061 Update Psalm to 5.12.0
  composer.json
  phpstan.neon.dist
  psalm-strict.xml
  psalm.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver/IBMDB2/Connection.php
  src/Driver/IBMDB2/Exception/CannotCopyStreamToStream.php
  src/Driver/IBMDB2/Exception/CannotCreateTemporaryFile.php
  src/Driver/IBMDB2/Exception/PrepareFailed.php
  src/Driver/IBMDB2/Result.php
  src/Driver/Mysqli/Exception/ConnectionError.php
  src/Driver/Mysqli/Exception/ConnectionFailed.php
  src/Driver/Mysqli/Exception/InvalidCharset.php
  src/Driver/Mysqli/Exception/StatementError.php
  src/Driver/OCI8/Connection.php
  src/DriverManager.php
  src/ExpandArrayParameters.php
  src/Logging/Driver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/SQLitePlatform.php
  src/Query/QueryBuilder.php
  src/Result.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/ConnectionTest.php
  tests/Driver/Middleware/AbstractDriverMiddlewareTest.php
  tests/DriverManagerTest.php
  tests/Functional/BlobTest.php
  tests/Functional/Platform/LengthExpressionTest.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/PrimaryReadReplicaConnectionTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Logging/MiddlewareTest.php
  tests/Schema/MySQLInheritCharsetTest.php
  tests/TestUtil.php
Labels: Static Analysis

#6025 Fix incorrect syntax for dropping primary indexes in PostgreSQL
  src/Platforms/PostgreSQLPlatform.php
  tests/Functional/Driver/DBAL6024Test.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: Bug, PostgreSQL, Schema Management

#6067 Merge 3.6.x into 3.7.x
  .github/workflows/continuous-integration.yml
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  tests/Functional/Driver/DBAL6024Test.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: Merge Up

#6065 Update PHPUnit to 10
  ci/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  ci/github/phpunit/ibm_db2.xml
  ci/github/phpunit/mysqli-tls.xml
  ci/github/phpunit/mysqli.xml
  ci/github/phpunit/oci8.xml
  ci/github/phpunit/pdo_mysql.xml
  ci/github/phpunit/pdo_oci.xml
  ci/github/phpunit/pdo_pgsql.xml
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/pdo_sqlsrv.xml
  ci/github/phpunit/pgsql.xml
  ci/github/phpunit/sqlite3.xml
  ci/github/phpunit/sqlsrv.xml
  composer.json
  phpunit.xml.dist
  tests/Driver/IBMDB2/DriverTest.php
  tests/Driver/Mysqli/DriverTest.php
  tests/Driver/OCI8/DriverTest.php
  tests/Driver/PDO/MySQL/DriverTest.php
  tests/Driver/PDO/OCI/DriverTest.php
  tests/Driver/PDO/SQLSrv/DriverTest.php
  tests/Driver/PDO/SQLite/DriverTest.php
  tests/Driver/SQLSrv/DriverTest.php
  tests/Functional/Platform/AbstractColumnTestCase.php
  tests/Functional/Platform/AlterDecimalColumnTest.php
  tests/Functional/Platform/ColumnTest/IBMDB2.php
  tests/Functional/Platform/ColumnTest/MySQL.php
  tests/Functional/Platform/ColumnTest/Oracle.php
  tests/Functional/Platform/ColumnTest/PostgreSQL.php
  tests/Functional/Platform/ColumnTest/SQLServer.php
  tests/Functional/Platform/ColumnTest/SQLite.php
  tests/Types/BinaryTest.php
Labels: Test Suite, Dependencies

#6072 Fix binding unused parameter
  src/Schema/SQLServerSchemaManager.php
Labels: Bug, SQL Server, Schema Management, Schema Introspection

#6073 PHPStan 1.10.21, PHPUnit 9.6.9, JetBrains Stubs 2023.1
  composer.json
Labels: Test Suite, Static Analysis

#6074 Merge 3.7.x into 4.0.x
  composer.json
  src/Schema/SQLServerSchemaManager.php
Labels: Merge Up

#6075 Psalm 5.13.1
  composer.json
Labels: Static Analysis

#6077 Document alternative to Type::getName
  UPGRADE.md
  src/Types/Type.php
Labels: Documentation
