Repository doctrine/dbal, pull requests merged in 2023-01, with the labels that each got.

#5850 Remove the `url` connection param
  UPGRADE.md
  src/DriverManager.php
  src/Exception/MalformedDsnException.php
  src/Tools/DsnParser.php
  tests/DriverManagerTest.php
Labels: BC Break

#5851 Allow to explicitly set the wrapper class to the default one
  src/DriverManager.php
  tests/DriverManagerTest.php
Labels: Bug

#5853 Use a narrower return type for DriverManager::getAvailableDrivers()
  src/DriverManager.php
Labels: Static Analysis

#5854 Test the return type of DriverManager::getAvailableDrivers()
  phpstan.neon.dist
  static-analysis/driver-manager-get-available-drivers-return-type.php
Labels: Static Analysis

#5855 Reuse the Params type alias for getConnection()
  src/DriverManager.php
Labels: Static Analysis

#5857 Formally allow `url` in `DriverManager::getConnection()`
  src/DriverManager.php
Labels: Static Analysis

#5858 Merge 3.5.x into 3.6.x
  src/DriverManager.php
  tests/DriverManagerTest.php
Labels: Merge Up

#5861 fix platform comparator issues when using compareTables
  src/Platforms/MySQL/Comparator.php
  src/Platforms/SQLServer/Comparator.php
  src/Platforms/SQLite/Comparator.php
Labels: Bug, Schema Comparison

#5862 Allow passing url to override params
  src/DriverManager.php
Labels: Static Analysis

#5859 Merge 3.6.x into 4.0.x
  phpstan.neon.dist
  psalm.xml.dist
  src/DriverManager.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Types/BigIntType.php
  src/Types/BooleanType.php
  src/Types/DateImmutableType.php
  src/Types/DateIntervalType.php
  src/Types/DateTimeImmutableType.php
  src/Types/DateTimeType.php
  src/Types/DateTimeTzImmutableType.php
  src/Types/DateTimeTzType.php
  src/Types/DateType.php
  src/Types/FloatType.php
  src/Types/IntegerType.php
  src/Types/JsonType.php
  src/Types/SimpleArrayType.php
  src/Types/SmallIntType.php
  src/Types/TimeImmutableType.php
  src/Types/TimeType.php
  src/Types/VarDateTimeImmutableType.php
  src/Types/VarDateTimeType.php
  static-analysis/driver-manager-get-available-drivers-return-type.php
  tests/DriverManagerTest.php
Labels: Merge Up

#5864 PHPStan 1.9.11, PHPUnit 9.5.28, Doctrine CS 11.1
  composer.json
Labels: Test Suite, Static Analysis

#5865 Merge 3.5.x into 3.6.x
  composer.json
  src/DriverManager.php
  src/Platforms/MySQL/Comparator.php
  src/Platforms/SQLServer/Comparator.php
  src/Platforms/SQLite/Comparator.php
Labels: Merge Up

#5866 Flag parameters as sensitive if they could contain the database password
  phpstan.neon.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractSQLiteDriver/Middleware/EnableForeignKeys.php
  src/Driver/IBMDB2/DataSourceName.php
  src/Driver/IBMDB2/Driver.php
  src/Driver/Middleware/AbstractDriverMiddleware.php
  src/Driver/Mysqli/Driver.php
  src/Driver/Mysqli/Initializer/Secure.php
  src/Driver/OCI8/Driver.php
  src/Driver/OCI8/Middleware/InitializeSession.php
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/SQLSrv/Driver.php
  src/Driver/SQLite3/Driver.php
  src/DriverManager.php
  src/Exception.php
  src/Logging/Driver.php
  src/Portability/Driver.php
  src/Tools/DsnParser.php
  tests/ConnectionTest.php
Labels: New Feature, PHP, Configuration, Connecting

#5873 Merge 3.5.x into 3.6.x
  composer.json
  src/Query/QueryBuilder.php
Labels: Merge Up

#5874 Merge 3.6.x into 4.0.x
  composer.json
  phpstan.neon.dist
  psalm.xml.dist
  src/Connection.php
  src/Connections/PrimaryReadReplicaConnection.php
  src/Driver.php
  src/Driver/AbstractOracleDriver.php
  src/Driver/AbstractSQLiteDriver/Middleware/EnableForeignKeys.php
  src/Driver/IBMDB2/DataSourceName.php
  src/Driver/IBMDB2/Driver.php
  src/Driver/Middleware/AbstractDriverMiddleware.php
  src/Driver/Mysqli/Driver.php
  src/Driver/Mysqli/Initializer/Secure.php
  src/Driver/OCI8/Driver.php
  src/Driver/OCI8/Middleware/InitializeSession.php
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLite/Driver.php
  src/Driver/SQLSrv/Driver.php
  src/Driver/SQLite3/Driver.php
  src/DriverManager.php
  src/Logging/Driver.php
  src/Platforms/SQLServer/Comparator.php
  src/Platforms/SQLite/Comparator.php
  src/Portability/Driver.php
  src/Tools/DsnParser.php
  tests/ConnectionTest.php
  tests/Functional/Driver/Mysqli/ConnectionTest.php
Labels: Merge Up

#5875 Add missing doc blocks to Index and UniqueConstraint
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Schema/Index.php
  src/Schema/UniqueConstraint.php
Labels: Static Analysis

#5877 Use psalm-assert to get rid of `assert()` calls
  src/Connection.php
Labels: Static Analysis

#5872 Explain why the number of affected rows can be a string
  UPGRADE.md
  src/Driver/Connection.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/Connection.php
  src/Driver/SQLSrv/Connection.php
Labels: oci8, sqlsrv, Documentation, PDO, Static Analysis

#5881 [Docs] Add IBM DB2 to `configuration.rst`
  docs/en/reference/configuration.rst
Labels: Documentation

#5882 Merge 3.5.x into 3.6.x
  docs/en/reference/configuration.rst
Labels: Merge Up

#5883 Make sure only PDO parameter types are passed to PDO methods
  src/Driver/PDO/Connection.php
  src/Driver/PDO/ParameterTypeMap.php
  src/Driver/PDO/Result.php
  src/Driver/PDO/Statement.php
Labels: Static Analysis

#5884 Merge 3.5.x into 3.6.x
  src/Driver/PDO/Connection.php
  src/Driver/PDO/ParameterTypeMap.php
  src/Driver/PDO/Result.php
  src/Driver/PDO/Statement.php
Labels: Merge Up

#5880 Add the PgSQL driver
  .github/workflows/continuous-integration.yml
  ci/github/phpunit/pgsql.xml
  docs/en/reference/configuration.rst
  phpstan.neon.dist
  psalm.xml.dist
  src/Driver/PgSQL/Connection.php
  src/Driver/PgSQL/ConvertParameters.php
  src/Driver/PgSQL/Driver.php
  src/Driver/PgSQL/Exception.php
  src/Driver/PgSQL/Exception/UnexpectedValue.php
  src/Driver/PgSQL/Exception/UnknownParameter.php
  src/Driver/PgSQL/Result.php
  src/Driver/PgSQL/Statement.php
  src/DriverManager.php
  tests/Functional/BlobTest.php
  tests/Functional/Driver/AbstractPostgreSQLDriverTest.php
  tests/Functional/Driver/PDO/PgSQL/DriverTest.php
  tests/Functional/Driver/PgSQL/DriverTest.php
  tests/Functional/Driver/PgSQL/ResultTest.php
  tests/Functional/StatementTest.php
Labels: New Feature, PostgreSQL, Drivers, pgsql

#5876 Introduce the `SchemaManagerFactory` interface
  UPGRADE.md
  docs/en/reference/schema-manager.rst
  src/Configuration.php
  src/Connection.php
  src/Schema/DefaultSchemaManagerFactory.php
  src/Schema/LegacySchemaManagerFactory.php
  src/Schema/SchemaManagerFactory.php
  tests/ConnectionTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/TestUtil.php
Labels: New Feature, Deprecation
