Repository doctrine/dbal, pull requests merged in 2024-08, with the labels that each got.

#6334 Make AbstractSchemaManager covariant to its template argument
  src/Schema/AbstractSchemaManager.php
  static-analysis/abstract-schema-manager-covariant-template.php
Labels: Static Analysis

#6280 Add explicit renameColumn method
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/ColumnDiff.php
  src/Schema/Comparator.php
  src/Schema/SQLiteSchemaManager.php
  src/Schema/Table.php
  src/Schema/TableDiff.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/ComparatorTest.php
  tests/Functional/Schema/CustomIntrospectionTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
  tests/Schema/TableTest.php
Labels: New Feature, Schema Management

#6479 Merge 3.8.x into 4.0.x
  src/Schema/AbstractSchemaManager.php
  static-analysis/abstract-schema-manager-covariant-template.php
Labels: Merge Up

#6481 Fix tests
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Test Suite

#6480 Merge 4.1.x into 5.0.x
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/ColumnDiff.php
  src/Schema/Comparator.php
  src/Schema/SQLiteSchemaManager.php
  src/Schema/Table.php
  src/Schema/TableDiff.php
  static-analysis/abstract-schema-manager-covariant-template.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/ComparatorTest.php
  tests/Functional/Schema/CustomIntrospectionTest.php
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
  tests/Schema/TableTest.php
Labels: Merge Up

#6483 Make the schema manager aware of the disabling of type comments
  src/Schema/AbstractSchemaManager.php
  tests/Functional/Ticket/DBAL461Test.php
Labels: Bug

#6490 Ensure PostgreSQL field length change is executed again
  src/Platforms/PostgreSQLPlatform.php
  tests/Functional/Platform/AlterColumnLengthChangeTest.php
Labels: Bug

#6482 Add deprecation layer for TableDiff methods
  UPGRADE.md
  psalm.xml.dist
  src/Schema/TableDiff.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/ComparatorTest.php
Labels: New Feature, Schema Management, Deprecation

#6463 Add DBTypes that are missing for TypeMapping
  src/Platforms/SQLServerPlatform.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Bug, SQL Server, Schema Introspection

#6389 Fix condition on Ascii String for SQL Server
  src/Platforms/SQLServerPlatform.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Bug, SQL Server

#6199 fix #6198: stop considering generated column definition as being its default value
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/PostgreSQL120Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: Bug, PostgreSQL, Schema Introspection

#6494 Document the new PostgreSQL120Platform
  docs/en/reference/platforms.rst
Labels: Documentation

#6495 Deprecate support for Postgres 10 and 11
  UPGRADE.md
  docs/en/reference/platforms.rst
  psalm.xml.dist
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/PostgreSQL120Platform.php
  src/Platforms/PostgreSQLPlatform.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Deprecation

#6492 Prepare 3.9.0 and 4.1.0
  .doctrine-project.json
  README.md
Labels: Documentation

#6497 Remove obsolete PHP version check
  tests/Functional/TransactionTest.php
Labels: Test Suite

#6498 PHPStan 1.11.10
  composer.json
Labels: Static Analysis

#6496 Remove support for Postgres 10 and 11
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  docs/en/reference/platforms.rst
  psalm.xml.dist
  src/Driver/AbstractPostgreSQLDriver.php
  src/Platforms/PostgreSQL120Platform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/PostgreSQLSchemaManager.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: PostgreSQL, Platforms, BC Break

#6500 Psalm 5.25.0
  composer.json
Labels: Static Analysis

#6499 PHPUnit 10.5.30
  composer.json
Labels: Test Suite

#6501 Try removing quotes
  .github/workflows/continuous-integration.yml
Labels: CI

#6503 Remove beStrictAboutTodoAnnotatedTests from PHPUnit configuration
  ci/appveyor/mssql.sql2017.pdo_sqlsrv.appveyor.xml
  ci/appveyor/mssql.sql2017.sqlsrv.appveyor.xml
  ci/github/phpunit/ibm_db2.xml
  ci/github/phpunit/mysqli-tls.xml
  ci/github/phpunit/mysqli.xml
  ci/github/phpunit/oci8-21.xml
  ci/github/phpunit/oci8.xml
  ci/github/phpunit/pdo_mysql.xml
  ci/github/phpunit/pdo_oci-21.xml
  ci/github/phpunit/pdo_oci.xml
  ci/github/phpunit/pdo_pgsql.xml
  ci/github/phpunit/pdo_sqlite.xml
  ci/github/phpunit/pdo_sqlsrv.xml
  ci/github/phpunit/pgsql.xml
  ci/github/phpunit/sqlite3.xml
  ci/github/phpunit/sqlsrv.xml
  phpunit.xml.dist
Labels: Test Suite

#6505 Raise a proper exception when calling `getColumnName()` with negative index
  src/Cache/ArrayResult.php
  src/Driver/PDO/Result.php
  src/Exception/InvalidColumnIndex.php
  tests/Cache/ArrayStatementTest.php
  tests/Functional/ResultMetadataTest.php
Labels: Bug, Results

#6507 PHPStan 1.12
  composer.json
  src/Driver/AbstractDB2Driver.php
  src/Driver/AbstractMySQLDriver.php
  src/Driver/AbstractPostgreSQLDriver.php
Labels: Static Analysis

#6508 Use generators for large data providers
  tests/Connection/ExpandArrayParametersTest.php
Labels: Test Suite

#6504 Handle cached result column names and rows separately
  UPGRADE.md
  src/Cache/ArrayResult.php
  src/Connection.php
  tests/Cache/ArrayResultTest.php
  tests/Cache/ArrayStatementTest.php
  tests/Connection/CachedQueryTest.php
  tests/ConnectionTest.php
  tests/Functional/Connection/FetchTest.php
  tests/TestUtil.php
Labels: New Feature, Cache, Results
