Repository doctrine/dbal, pull requests merged in 2024-06, with the labels that each got.

#6413 Fix foreign key name change detection
  src/Schema/Comparator.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Bug

#6418 Fix foreign key name change detection
  src/Schema/Comparator.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Bug

#6326 Remove redundant variable
  src/Platforms/AbstractPlatform.php
Labels: Improvement

#6423 Fix: Skip type comparison if disableTypeComments is true
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Bug

#6429 Fix the portability documentation
  docs/en/reference/portability.rst
Labels: Documentation

#6425 Fix MariaDB fetching of default table character-set (#6361)
  src/Schema/MySQLSchemaManager.php
Labels: Bug, MariaDB, Schema Introspection

#6431 Display warnings when running PHPUnit in CI
  .github/workflows/continuous-integration.yml
Labels: Test Suite

#6432 CI MariaDB: add 11.4, remove 11.0
  .github/workflows/continuous-integration.yml
Labels: CI, MariaDB

#6426 CI: Update MariaDB versions
  .github/workflows/continuous-integration.yml
Labels: CI, MariaDB

#6369 Add `QueryBuilder` support for `UNION` clause
  docs/en/reference/query-builder.rst
  src/Platforms/AbstractPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Query/QueryBuilder.php
  src/Query/QueryType.php
  src/Query/Union.php
  src/Query/UnionQuery.php
  src/Query/UnionType.php
  src/SQL/Builder/DefaultUnionSQLBuilder.php
  src/SQL/Builder/UnionSQLBuilder.php
  tests/Functional/Query/QueryBuilderTest.php
  tests/Query/QueryBuilderTest.php
Labels: New Feature, QueryBuilder

#6439 Default to distinct union queries
  docs/en/reference/query-builder.rst
  src/Query/QueryBuilder.php
  tests/Functional/Query/QueryBuilderTest.php
  tests/Query/QueryBuilderTest.php
Labels: Improvement, QueryBuilder

#6446 PHPStan 1.11.5
  composer.json
  phpstan.neon.dist
Labels: Static Analysis

#6352 Move schema split for SQLite CREATE INDEX only
  src/Platforms/SqlitePlatform.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Bug, SQLite, Schema Management

#6447 PHPUnit 10.5.21
  composer.json
Labels: Test Suite

#6448 Merge 3.8.x into 3.9.x
  .github/workflows/continuous-integration.yml
  composer.json
  docs/en/reference/portability.rst
  phpstan.neon.dist
  src/Platforms/SqlitePlatform.php
  src/Schema/Comparator.php
  tests/Platforms/SqlitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Merge Up

#6449 Merge 3.8.x into 4.0.x
  composer.json
  phpstan.neon.dist
  src/Platforms/SQLitePlatform.php
  src/Schema/Comparator.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Merge Up

#6434 Add MariaDb1010Platform for fetchTableOptionsByTable
  docs/en/reference/platforms.rst
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/MariaDb1010Platform.php
  src/Schema/MySQLSchemaManager.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Query/QueryBuilderTest.php
Labels: Improvement, MariaDB, Platforms

#6451 Merge 4.1.x into 5.0.x
  .github/workflows/continuous-integration.yml
  composer.json
  docs/en/reference/platforms.rst
  docs/en/reference/portability.rst
  docs/en/reference/query-builder.rst
  phpstan.neon.dist
  src/Driver/AbstractMySQLDriver.php
  src/Driver/OCI8/Middleware/InitializeSession.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/MariaDB1010Platform.php
  src/Platforms/SQLitePlatform.php
  src/Query/QueryBuilder.php
  src/Query/QueryType.php
  src/Query/Union.php
  src/Query/UnionQuery.php
  src/Query/UnionType.php
  src/SQL/Builder/DefaultUnionSQLBuilder.php
  src/SQL/Builder/UnionSQLBuilder.php
  src/Schema/MySQLSchemaManager.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Query/QueryBuilderTest.php
  tests/Platforms/MySQL84PlatformTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Query/QueryBuilderTest.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Merge Up

#6428 Add the Result::getColumnName method
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Cache/ArrayResult.php
  src/Driver/IBMDB2/Result.php
  src/Driver/Middleware/AbstractResultMiddleware.php
  src/Driver/Mysqli/Result.php
  src/Driver/OCI8/Result.php
  src/Driver/PDO/Result.php
  src/Driver/PgSQL/Result.php
  src/Driver/Result.php
  src/Driver/SQLSrv/Result.php
  src/Driver/SQLite3/Result.php
  src/Exception/InvalidColumnIndex.php
  src/Portability/Converter.php
  src/Portability/Result.php
  src/Result.php
  tests/Cache/ArrayStatementTest.php
  tests/Functional/PortabilityTest.php
  tests/Functional/ResultMetadataTest.php
Labels: New Feature, Drivers, Results

#6453 PHP CodeSniffer 3.10.1
  composer.json
Labels: Code Style

#6452 Add the `getColumnName()` method to the `Result` interface
  UPGRADE.md
  phpstan.neon.dist
  src/Driver/Middleware/AbstractResultMiddleware.php
  src/Driver/Result.php
  src/Result.php
Labels: Improvement, Drivers, BC Break, Results

#6454 PHPUnit 10.5.22
  composer.json
Labels: Test Suite

#6435 mariadb: add nightly workflow to facilitate mariadb "nightlies"
  .github/workflows/nightly.yml
Labels: CI, MariaDB

#6457 ci: nightly - php-8.1 min version
  .github/workflows/nightly.yml
Labels: CI, MariaDB

#6460 Docs: update custom platform example to use middlewares
  docs/en/reference/platforms.rst
Labels: Documentation, Configuration
