Repository doctrine/dbal, pull requests merged in 2024-03, with the labels that each got.

#6320 Add gssencmode option to connection string for PgSQL & PDO PgSQL driver
  docs/en/reference/configuration.rst
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PgSQL/Driver.php
Labels: Bug, pdo_pgsql, Configuration, Connecting, pgsql

#6322 Merge 3.8.x into 4.0.x
  docs/en/reference/configuration.rst
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PgSQL/Driver.php
Labels: Merge Up

#6321 Make all mapped database types case insensitive
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Bug, Types, Type Mapping

#6323 Bump CI workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
  .github/workflows/static-analysis.yml
Labels: CI

#6324 Merge 3.8.x into 4.0.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
  .github/workflows/static-analysis.yml
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractPlatformTestCase.php
Labels: Merge Up

#6325 Fix double quote used wrongly for literal value in SqliteSchemaManager
  src/Schema/SqliteSchemaManager.php
Labels: Bug, SQLite, Schema Management

#6333 Update UPGRADE.md
  UPGRADE.md
Labels: Documentation

#6336 [Documentation] Adding "versionadded"
  docs/en/reference/types.rst
Labels: Documentation

#6340 [Documentation] Fixing markup
  docs/en/reference/types.rst
Labels: Documentation

#6342 Add MariaDB 11.3 to the test matrix
  .github/workflows/continuous-integration.yml
Labels: CI, MariaDB

#6343 Deprecate MariaDB 10.4 and MySQL 5.7 support
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/Keywords/MySQL80Keywords.php
  src/Platforms/MariaDB1052Platform.php
  src/Platforms/MySQL80Platform.php
Labels: MySQL, MariaDB, Platforms, Deprecation

#6345 Merge 3.8.x into 4.0.x
  .github/workflows/continuous-integration.yml
  src/Query/QueryBuilder.php
  src/Schema/SQLiteSchemaManager.php
Labels: Merge Up

#6346 Remove support for MariaDB 10.4 and MySQL 5.7
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MySQL80Keywords.php
  src/Platforms/Keywords/MySQLKeywords.php
  src/Platforms/MariaDB1052Platform.php
  src/Platforms/MariaDB1060Platform.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MySQL80Platform.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Query/QueryBuilderTest.php
  tests/Functional/Schema/MySQL/ComparatorTest.php
  tests/Platforms/MariaDB1052PlatformTest.php
  tests/Platforms/MariaDBPlatformTest.php
Labels: MySQL, MariaDB, Platforms, BC Break
