Repository doctrine/dbal, pull requests merged in 2024-04, with the labels that each got.

#6355 Document how to run integration tests locally
  ci/travis/install-mariadb.sh
  docs/en/reference/testing.rst
  phpunit.xml.dist
Labels: CI, Documentation

#6358 Ensure correct json default value normalization
  src/Schema/PostgreSQLSchemaManager.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: Bug, PostgreSQL, Schema Definition

#6359 Avoid calling deprecated Type::getName()
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
Labels: Test Suite, PostgreSQL

#6014 [Docs] Update docs regarding "datetimetz" type
  docs/en/reference/known-vendor-issues.rst
  docs/en/reference/types.rst
  src/Types/DateTimeTzType.php
Labels: Documentation

#6362 Connection::setNestTransactionsWithSavepoints() should not break lazy connection
  src/Connection.php
  tests/ConnectionTest.php
  tests/Functional/ConnectionTest.php
Labels: Bug, Connecting, Transactions

#6367 Merge 3.8.x into 4.0.x
  docs/en/reference/known-vendor-issues.rst
  docs/en/reference/types.rst
  src/Types/DateTimeTzType.php
Labels: Merge Up
