Repository doctrine/dbal, pull requests merged in 2024-10, with the labels that each got.

#6528 ci: Run tests with PHP 8.4
  .github/workflows/continuous-integration.yml
Labels: CI, PHP

#6531 Setup documentation workflow
  .github/workflows/documentation.yml
  docs/en/reference/testing.rst
  docs/en/sidebar.rst
Labels: CI, Documentation

#6535 PHPStan 1.12.6
  composer.json
Labels: Static Analysis

#6537 CI: remove duplicate key
  .github/workflows/continuous-integration.yml
Labels: CI

#6532 Leverage the new PDO subclasses
  UPGRADE.md
  phpstan.neon.dist
  psalm.xml.dist
  src/Driver/PDO/MySQL/Driver.php
  src/Driver/PDO/OCI/Driver.php
  src/Driver/PDO/PDOConnect.php
  src/Driver/PDO/PgSQL/Driver.php
  src/Driver/PDO/SQLSrv/Driver.php
  src/Driver/PDO/SQLite/Driver.php
  tests/Functional/Driver/PDO/PDOSubclassTest.php
Labels: New Feature, Connections, Connecting, PDO

#6540 Prepare the 4.2.0 release
  .doctrine-project.json
  README.md
Labels: Documentation

#6541 Remove broken links from php doc block
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Schema/OracleSchemaManager.php
  src/Schema/PostgreSQLSchemaManager.php
  src/Schema/SqliteSchemaManager.php
Labels: Documentation

#6543 Run risky code in finally block
  src/Connection.php
  tests/ConnectionTest.php
Labels: Bug, Connections, Error Handling

#6300 Make column and index renaming configurable
  docs/en/reference/schema-manager.rst
  src/Platforms/MySQL/Comparator.php
  src/Platforms/SQLServer/Comparator.php
  src/Platforms/SQLite/Comparator.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Comparator.php
  src/Schema/ComparatorConfig.php
  src/Schema/MySQLSchemaManager.php
  src/Schema/SQLServerSchemaManager.php
  src/Schema/SQLiteSchemaManager.php
  tests/Functional/Schema/ComparatorTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/MySQL/ComparatorTest.php
  tests/Platforms/MySQL/MariaDBJsonComparatorTest.php
  tests/Platforms/SQLServer/ComparatorTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SQLite/ComparatorTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractComparatorTestCase.php
  tests/Schema/Platforms/MySQLSchemaTest.php
Labels: New Feature, Schema Comparison

#6544 Merge 3.9.x into 4.2.x
  src/Connection.php
  tests/ConnectionTest.php
Labels: Merge Up

#6549 Remove handling unuique constraint column names as associative array
  src/Schema/Table.php
Labels: Improvement, Schema

#6547 test: cover nested transactions
  tests/Functional/TransactionTest.php
Labels: Test Suite

#6553 Acknowledge the existence of 3.10
  .doctrine-project.json
  README.md
Labels: Documentation

#6556 Fix typo in PostgreSql documentation reference
  docs/en/reference/schema-representation.rst
Labels: Documentation

#6558 test: remove ->expects(self::any())
  tests/ConnectionTest.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
  tests/StatementTest.php
  tests/Types/DateImmutableTypeTest.php
  tests/Types/DateTimeImmutableTypeTest.php
  tests/Types/GuidTypeTest.php
  tests/Types/TimeImmutableTypeTest.php
Labels: Test Suite

#6552 [Bug] Query Cache mangled if saved by-reference
  src/Connection.php
  tests/Connection/CachedQueryTest.php
Labels: Bug, Cache

#6564 Create stubs instead of mocks
  tests/ConnectionTest.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Schema/Visitor/DropSchemaSqlCollectorTest.php
Labels: Test Suite

#6567 Merge 3.9.x into 4.2.x
  docs/en/reference/schema-representation.rst
  tests/ConnectionTest.php
  tests/Query/Expression/ExpressionBuilderTest.php
  tests/Types/DateImmutableTypeTest.php
  tests/Types/DateTimeImmutableTypeTest.php
  tests/Types/TimeImmutableTypeTest.php
Labels: Merge Up

#6560 Deprecate Table::removeForeignKey() and ::removeUniqueConstraint()
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Table.php
Labels: Foreign Keys, Tables, Deprecation

#6562 Cover scenario `BEGIN TRANSACTION; COMMIT; BEGIN TRANSACTION; --failure`
  tests/ConnectionTest.php
Labels: Test Suite

#6559 Deprecate dropping columns referenced by constraints
  UPGRADE.md
  src/Schema/Table.php
  tests/Schema/TableTest.php
Labels: Foreign Keys, Tables, Columns, Deprecation

#6572 Fix broken links
  docs/en/reference/configuration.rst
Labels: Documentation

#6574 Remove non thrown exception from phpdoc
  src/Schema/Table.php
Labels: Static Analysis

#6410 Fix bigint PHP_INT_MIN/PHP_INT_MAX string to int convert
  psalm.xml.dist
  src/Types/BigIntType.php
  tests/Functional/Types/BigIntTypeTest.php
Labels: Bug, Type Conversion

#6575 Run tests against PostgreSQL 17
  .github/workflows/continuous-integration.yml
Labels: CI, PostgreSQL

#6578 Rename column in indexes and constraints
  src/Schema/Table.php
  tests/Functional/Schema/ColumnRenameTest.php
  tests/Schema/TableTest.php
Labels: Improvement, Foreign Keys, Indexes, Tables, Columns
