Repository doctrine/dbal, pull requests merged in 2024-11, with the labels that each got.

#6583 Remove deprecated
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractPlatform.php
  src/Schema/Table.php
  tests/Schema/AbstractComparatorTestCase.php
  tests/Schema/TableTest.php
Labels: Schema Management, BC Break, Foreign Keys, Tables

#6580 Distinguish between Appveyor and github-action
  .appveyor.yml
  .github/workflows/continuous-integration.yml
Labels: CI

#6545 Fix incorrect `transactional()` handling when DB auto-rolled back the transaction
  src/Connection.php
  src/Driver/API/OCI/ExceptionConverter.php
  src/Driver/OCI8/Connection.php
  src/Exception/TransactionRolledBack.php
  tests/ConnectionTest.php
  tests/Functional/ForeignKeyConstraintViolationsTest.php
  tests/Functional/UniqueConstraintViolationsTest.php
Labels: Bug

#6590 Deprecate AbstractPlatform::quoteIdentifier()
  UPGRADE.md
  psalm.xml.dist
  src/Connection.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/AbstractAsset.php
  src/Schema/OracleSchemaManager.php
  tests/Functional/Platform/QuotingTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/TestUtil.php
Labels: Quoting, Deprecation, Identifiers

#6594 Remove AbstractPlatform::quoteIdentifier()
  UPGRADE.md
  psalm.xml.dist
  src/Connection.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/SQLServerPlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: BC Break, Quoting, Identifiers

#6592 Deprecate relying on the current implementation of the database object name parser
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/AbstractAsset.php
  src/Schema/Name/Parser.php
  src/Schema/Name/Parser/Exception.php
  src/Schema/Name/Parser/Exception/ExpectedDot.php
  src/Schema/Name/Parser/Exception/ExpectedNextIdentifier.php
  src/Schema/Name/Parser/Exception/UnableToParseIdentifier.php
  src/Schema/Name/Parser/Identifier.php
  tests/Schema/AbstractAssetTest.php
  tests/Schema/Name/ParserTest.php
Labels: Quoting, Reserved Keywords, Deprecation, Identifiers

#6597 Merge 4.3.x up into 5.0.x
  UPGRADE.md
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/AbstractAsset.php
  src/Schema/Name/Parser.php
  src/Schema/Name/Parser/Exception.php
  src/Schema/Name/Parser/Exception/ExpectedDot.php
  src/Schema/Name/Parser/Exception/ExpectedNextIdentifier.php
  src/Schema/Name/Parser/Exception/UnableToParseIdentifier.php
  src/Schema/Name/Parser/Identifier.php
  tests/Schema/AbstractAssetTest.php
  tests/Schema/Name/ParserTest.php
Labels: Merge Up

#6599 Fix dropping the PK on a PostgreSQL table with quoted name
  src/Platforms/PostgreSQLPlatform.php
  tests/Platforms/PostgreSQLPlatformTest.php
Labels: Bug, PostgreSQL, Schema Management, Quoting

#6602 Fix renaming to quoted names on SQL Server
  src/Platforms/SQLServerPlatform.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Bug, SQL Server, Schema Management, Quoting

#6600 Fix parsing quoted table name on SQLite
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Bug, SQLite, Quoting, Schema Introspection

#6603 Merge 3.9.x up into 3.10.x
  .appveyor.yml
  src/Schema/SqliteSchemaManager.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
Labels: Merge Up

#6604 Merge 3.10.x up into 4.2.x
  .appveyor.yml
  src/Schema/SQLiteSchemaManager.php
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
Labels: Merge Up

#6605 Merge 4.2.x up into 4.3.x
  .appveyor.yml
  .github/workflows/continuous-integration.yml
  src/Connection.php
  src/Driver/API/OCI/ExceptionConverter.php
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Result.php
  src/Exception/TransactionRolledBack.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/SQLiteSchemaManager.php
  tests/ConnectionTest.php
  tests/Functional/ForeignKeyConstraintViolationsTest.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
  tests/Functional/UniqueConstraintViolationsTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Merge Up

#6606 Merge 4.3.x up into 5.0.x
  .appveyor.yml
  .github/workflows/continuous-integration.yml
  src/Connection.php
  src/Driver/API/OCI/ExceptionConverter.php
  src/Driver/OCI8/Connection.php
  src/Driver/OCI8/Result.php
  src/Exception/TransactionRolledBack.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Schema/SQLiteSchemaManager.php
  tests/ConnectionTest.php
  tests/Functional/ForeignKeyConstraintViolationsTest.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
  tests/Functional/UniqueConstraintViolationsTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Merge Up

#6607 Deprecate reserved keyword lists
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/DB2Keywords.php
  src/Platforms/Keywords/KeywordList.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MySQL80Keywords.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/Keywords/MySQLKeywords.php
  src/Platforms/Keywords/OracleKeywords.php
  src/Platforms/Keywords/PostgreSQLKeywords.php
  src/Platforms/Keywords/SQLServerKeywords.php
  src/Platforms/Keywords/SQLiteKeywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MySQL80Platform.php
  src/Platforms/MySQL84Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  tests/Schema/AbstractAssetTest.php
Labels: Platforms, Quoting, Reserved Keywords, Deprecation

#6608 Mark Identifier as internal
  UPGRADE.md
  src/Schema/Identifier.php
Labels: Deprecation

#6609 Merge 4.3.x up into 5.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/DB2Keywords.php
  src/Platforms/Keywords/KeywordList.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/Keywords/MySQLKeywords.php
  src/Platforms/Keywords/OracleKeywords.php
  src/Platforms/Keywords/PostgreSQLKeywords.php
  src/Platforms/Keywords/SQLServerKeywords.php
  src/Platforms/Keywords/SQLiteKeywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MySQL84Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/Identifier.php
Labels: Merge Up

#6610 Deprecate AbstractAsset::_setName()
  UPGRADE.md
  psalm.xml.dist
  src/Schema/AbstractAsset.php
  src/Schema/Column.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/Identifier.php
  src/Schema/Index.php
  src/Schema/Schema.php
  src/Schema/Sequence.php
  src/Schema/Table.php
  src/Schema/UniqueConstraint.php
  src/Schema/View.php
Labels: Schema Management, Deprecation

#6589 Rework handling quoted object names and reserved SQL keywords
  UPGRADE.md
  psalm.xml.dist
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/Keywords/DB2Keywords.php
  src/Platforms/Keywords/KeywordList.php
  src/Platforms/Keywords/MariaDBKeywords.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/Keywords/MySQLKeywords.php
  src/Platforms/Keywords/OracleKeywords.php
  src/Platforms/Keywords/PostgreSQLKeywords.php
  src/Platforms/Keywords/SQLServerKeywords.php
  src/Platforms/Keywords/SQLiteKeywords.php
  src/Platforms/MariaDBPlatform.php
  src/Platforms/MySQL84Platform.php
  src/Platforms/MySQLPlatform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/AbstractAsset.php
  src/Schema/AbstractSchemaManager.php
  src/Schema/Exception/IndexNameInvalid.php
  src/Schema/Exception/InvalidObjectName.php
  src/Schema/Exception/InvalidTableName.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Platform/RenameColumnTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/DB2PlatformTest.php
  tests/Platforms/MariaDBPlatformTest.php
  tests/Platforms/MySQL84PlatformTest.php
  tests/Platforms/MySQLPlatformTest.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/PostgreSQLPlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Platforms/SQLitePlatformTest.php
  tests/Schema/AbstractAssetTest.php
  tests/Schema/MySQLInheritCharsetTest.php
  tests/Schema/Platforms/MySQLSchemaTest.php
Labels: Improvement, BC Break, Quoting, Reserved Keywords, Identifiers

#6612 Merge 4.3.x up into 5.0.x
  UPGRADE.md
  psalm.xml.dist
  src/Schema/AbstractAsset.php
  src/Schema/Column.php
  src/Schema/ForeignKeyConstraint.php
  src/Schema/Identifier.php
  src/Schema/Index.php
  src/Schema/Schema.php
  src/Schema/Sequence.php
  src/Schema/Table.php
  src/Schema/UniqueConstraint.php
  src/Schema/View.php
Labels: Merge Up

#6614 Remove AbstractAsset::_setName()
  UPGRADE.md
  psalm.xml.dist
  src/Schema/AbstractAsset.php
  src/Schema/Identifier.php
Labels: Schema, BC Break

#6596 Use exception in OCI8 driver, instead of relying on assert
  src/Driver/OCI8/Connection.php
  tests/Functional/Driver/OCI8/ConnectionTest.php
Labels: Bug, oci8, Prepared Statements

#6593 Added support to override the protocol used when connecting to Oracle.
  docs/en/reference/configuration.rst
  src/Driver/AbstractOracleDriver/EasyConnectString.php
  tests/Driver/AbstractOracleDriver/EasyConnectStringTest.php
Labels: New Feature, Oracle, Drivers, Connecting

#6613 Rework the continuous integration jobs
  .github/workflows/continuous-integration.yml
Labels: CI

#6579 fix: max string length resolution in AbstractPlatform::getEnumDeclara…
  src/Platforms/AbstractPlatform.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Bug, Type Mapping

#6623 Revert workaround for persistent PDO connections
  src/Driver/PDO/PDOConnect.php
Labels: Bug, Connections, PHP, Connecting, PDO

#6625 Rework continuous integration for v4
  .github/workflows/continuous-integration.yml
Labels: CI

#6627 Merge 4.2.x up into 4.3.x
  .github/workflows/continuous-integration.yml
  docs/en/reference/configuration.rst
  src/Driver/AbstractOracleDriver/EasyConnectString.php
  src/Driver/OCI8/Connection.php
  src/Driver/PDO/PDOConnect.php
  src/Platforms/AbstractPlatform.php
  tests/Driver/AbstractOracleDriver/EasyConnectStringTest.php
  tests/Functional/Driver/OCI8/ConnectionTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Merge Up

#6632 Source IBM DB2 CLI driver from GitHub
  .github/workflows/continuous-integration.yml
Labels: CI

#6636 Merge 3.9.x up into 3.10.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
Labels: Merge Up

#6635 Deprecate altering table configuration
  UPGRADE.md
  psalm.xml.dist
  src/Schema/AbstractSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SchemaConfig.php
  src/Schema/Table.php
  src/Schema/TableConfiguration.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Tables, Deprecation, Identifiers

#6637 Merge 3.10.x up into 4.2.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
Labels: Merge Up

#6638 Merge 4.2.x up into 4.3.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
Labels: Merge Up

#6639 Merge 4.3.x up into 5.0.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
  UPGRADE.md
  psalm.xml.dist
  src/Schema/AbstractSchemaManager.php
  src/Schema/Schema.php
  src/Schema/SchemaConfig.php
  src/Schema/Table.php
  src/Schema/TableConfiguration.php
  tests/Functional/Schema/OracleSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Schema/AbstractComparatorTestCase.php
Labels: Merge Up

#6640 Remove support for altering table configuration
  UPGRADE.md
  psalm.xml.dist
  src/Schema/Schema.php
  src/Schema/Table.php
Labels: BC Break, Tables, Identifiers
