Repository doctrine/dbal, pull requests merged in 2024-02, with the labels that each got.

#6275 Avoid ambigous TABLE_NAME in query
  src/Platforms/MariaDb1043Platform.php
Labels: Improvement, MariaDB, Schema Introspection

#6289 Merge 3.8.x into 4.0.x
  src/Connection.php
  src/Platforms/MariaDBPlatform.php
Labels: Merge Up

#6290 PHPStan 1.10.57, PHPUnit 9.6.16
  composer.json
Labels: Test Suite, Static Analysis

#6291 Update branch metadata
  .doctrine-project.json
Labels: Documentation

#6292 Update branches in README.md
  README.md
Labels: Documentation

#6293 Update branch metadata
  .doctrine-project.json
Labels: Documentation

#6295 Move type coverage badge
  README.md
Labels: Documentation

#6294 Psalm 5.21.1
  composer.json
  src/Driver/OCI8/Driver.php
  src/Platforms/SQLitePlatform.php
  tests/Functional/Driver/OCI8/ResultTest.php
  tests/Functional/ExceptionTest.php
  tests/Functional/TransactionTest.php
Labels: Static Analysis

#6298 Update UPGRADE.md
  UPGRADE.md
Labels: Documentation

#6301 Establish link between isConnected() and _conn
  src/Connection.php
  static-analysis/non-null-connection.php
Labels: Static Analysis

#6302 [3.8.x] AbstractPlatform - allow any string in interval for date interval expression
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SqlitePlatform.php
  tests/Platforms/DB2PlatformTest.php
Labels: Bug, Platforms, Static Analysis

#6305 [Documentation] Adding exact command for Postgres serial migration
  docs/en/how-to/postgresql-identity-migration.rst
Labels: PostgreSQL, Documentation

#6307 PHPStan 1.10.58, PHPCS 3.9.0
  composer.json
Labels: Static Analysis

#6312 Use native intersection types in test suite
  tests/ConnectionTest.php
  tests/Driver/AbstractDriverTestCase.php
  tests/Portability/StatementTest.php
  tests/Query/QueryBuilderTest.php
  tests/Tools/Console/RunSqlCommandTest.php
  tests/Types/BinaryTest.php
  tests/Types/BlobTest.php
  tests/Types/BooleanTest.php
  tests/Types/DateImmutableTypeTest.php
  tests/Types/DateIntervalTest.php
  tests/Types/DateTimeImmutableTypeTest.php
  tests/Types/DateTimeTzImmutableTypeTest.php
  tests/Types/DecimalTest.php
  tests/Types/FloatTest.php
  tests/Types/GuidTypeTest.php
  tests/Types/IntegerTest.php
  tests/Types/JsonTest.php
  tests/Types/SmallIntTest.php
  tests/Types/StringTest.php
  tests/Types/TimeImmutableTypeTest.php
  tests/Types/VarDateTimeImmutableTypeTest.php
  tests/Types/VarDateTimeTest.php
Labels: Test Suite

#6318 Remove Type::canRequireSQLConversion from docs
  docs/en/reference/types.rst
Labels: Documentation
