Repository doctrine/dbal, pull requests merged in 2024-05, with the labels that each got.

#6373 Specify the minor version number for MySQL image
  .github/workflows/continuous-integration.yml
Labels: CI

#6372 Set fail_ci_if_error flag to true
  .github/workflows/continuous-integration.yml
Labels: CI

#6376 Remove internal flag on DriverException
  src/Exception/DriverException.php
Labels: Improvement

#6315 Fix SQLite temp table name must not contain dot
  src/Platforms/SqlitePlatform.php
  tests/Functional/Schema/SqliteSchemaManagerTest.php
  tests/Platforms/SqlitePlatformTest.php
Labels: Bug, SQLite, Schema Management

#6338 Fix DB name passing in SqliteSchemaManager::listTableForeignKeys()
  src/Schema/SqliteSchemaManager.php
  tests/Schema/SqliteSchemaManagerTest.php
Labels: Missing Tests, Bug, SQLite

#6353 Fix SQL Server "extended property" SQL generation
  src/Platforms/SQLServerPlatform.php
  tests/Functional/Schema/SQLServerSchemaManagerTest.php
  tests/Platforms/SQLServerPlatformTest.php
Labels: Bug, SQL Server

#6381 Fix SQLiteSchemaManagerTest case
  tests/Functional/Schema/SQLiteSchemaManagerTest.php
Labels: Code Style

#6384 Use 3.8.x as a target for dependabot version updates
  .github/dependabot.yml
Labels: CI

#6386 Run tests against MySQL 8.4
  .github/workflows/continuous-integration.yml
Labels: CI, MySQL

#6388 Fix "Plugin 'mysql_native_password' is not loaded"
  .github/workflows/continuous-integration.yml
Labels: CI, MySQL

#6387 PHPStan 1.10.67, PHPUnit 9.6.19, PHPCS 3.9.2
  composer.json
Labels: Test Suite, Static Analysis

#6394 Fix example for QB delete and update in doc block
  src/Query/QueryBuilder.php
Labels: Documentation

#6398 Merge 3.8.x into 4.0.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  composer.json
Labels: Merge Up

#6399 PHPStan 1.11.1
  composer.json
  phpstan.neon.dist
  src/Result.php
Labels: Static Analysis

#6400 PHPUnit 10.5.20
  composer.json
Labels: Test Suite

#6401 Psalm 5.24.0
  composer.json
Labels: Static Analysis

#6402 Fix return type of iterateKeyValue()
  src/Result.php
Labels: Static Analysis

#6385 MySQL 8.4 Platform
  docs/en/reference/platforms.rst
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/MySQL84Platform.php
  src/Tools/Console/Command/ReservedWordsCommand.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Improvement, MySQL, Reserved Keywords

#6405 Merge 3.9.x into 4.1.x
  docs/en/reference/platforms.rst
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/MySQL84Platform.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Merge Up

#6406 Merge 4.1.x into 5.0.x
  docs/en/reference/platforms.rst
  src/Driver/AbstractMySQLDriver.php
  src/Platforms/Keywords/MySQL84Keywords.php
  src/Platforms/MySQL84Platform.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Merge Up

#6407 Fix documentation of supported MariaDB releases
  docs/en/reference/platforms.rst
  src/Platforms/MariaDb1027Platform.php
  src/Platforms/MariaDb1043Platform.php
  src/Platforms/MariaDb1052Platform.php
  src/Platforms/MariaDb1060Platform.php
  src/Platforms/MySQL57Platform.php
  src/Platforms/MySQL80Platform.php
Labels: MariaDB, Documentation

#6408 MySQL 8.4 removed keywords
  src/Platforms/Keywords/MySQL84Keywords.php
  tests/Platforms/MySQL84PlatformTest.php
Labels: Improvement, MySQL, Reserved Keywords

#6412 remove duplicate set NLS_DATE_FORMAT
  src/Driver/OCI8/Middleware/InitializeSession.php
Labels: Improvement
