Repository doctrine/dbal, pull requests merged in 2024-07, with the labels that each got.

#6461 Complete sentence
  src/Schema/AbstractAsset.php
Labels: Documentation

#6470 Fix update/delete aliases in documentation
  docs/en/reference/query-builder.rst
  src/Query/QueryBuilder.php
Labels: Documentation

#6462 CI: Add MySQL 9, reduce test matrix
  .github/workflows/continuous-integration.yml
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Test Suite, CI, MySQL

#6471 Add SmallFloat type
  docs/en/reference/types.rst
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Schema/OracleSchemaManager.php
  src/Types/SmallFloatType.php
  src/Types/Type.php
  src/Types/Types.php
  tests/Functional/Driver/PgSQL/ResultTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/TypeConversionTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Types/SmallFloatTest.php
Labels: New Feature, Types, Type Mapping

#6363 Properly handle MySQL error code 4031 from PHP 8.4
  src/Driver/API/MySQL/ExceptionConverter.php
Labels: Bug, MySQL, Error Handling, PHP

#6472 Merge 3.8.x into 3.9.x
  .github/workflows/continuous-integration.yml
  .github/workflows/nightly.yml
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Schema/AbstractAsset.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Merge Up

#6473 Merge 3.8.x into 4.0.x
  .github/workflows/continuous-integration.yml
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Schema/AbstractAsset.php
  tests/Driver/VersionAwarePlatformDriverTest.php
Labels: Merge Up

#6475 Merge 4.1.x into 5.0.x
  .github/workflows/continuous-integration.yml
  .github/workflows/nightly.yml
  docs/en/reference/platforms.rst
  docs/en/reference/query-builder.rst
  docs/en/reference/types.rst
  src/Driver/API/MySQL/ExceptionConverter.php
  src/Platforms/AbstractMySQLPlatform.php
  src/Platforms/AbstractPlatform.php
  src/Platforms/DB2Platform.php
  src/Platforms/OraclePlatform.php
  src/Platforms/PostgreSQLPlatform.php
  src/Platforms/SQLServerPlatform.php
  src/Platforms/SQLitePlatform.php
  src/Query/QueryBuilder.php
  src/Schema/AbstractAsset.php
  src/Schema/OracleSchemaManager.php
  src/Types/SmallFloatType.php
  src/Types/Type.php
  src/Types/Types.php
  tests/Driver/VersionAwarePlatformDriverTest.php
  tests/Functional/Driver/PgSQL/ResultTest.php
  tests/Functional/Schema/MySQLSchemaManagerTest.php
  tests/Functional/Schema/PostgreSQLSchemaManagerTest.php
  tests/Functional/Schema/SchemaManagerFunctionalTestCase.php
  tests/Functional/TypeConversionTest.php
  tests/Platforms/AbstractMySQLPlatformTestCase.php
  tests/Platforms/AbstractPlatformTestCase.php
  tests/Platforms/OraclePlatformTest.php
  tests/Platforms/SQLServerPlatformTest.php
  tests/Types/SmallFloatTest.php
Labels: Merge Up

#6476 Bump dev tools
  composer.json
Labels: Code Style, Static Analysis

#6477 PHPUnit 10.5.28
  composer.json
Labels: Test Suite
